// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/pkgmanager/v1/pkg_manager.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.iface.pkgmanager.v1;

public interface InstallRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nervus.interface.pkgmanager.v1.InstallRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * .nspkg 在调用方【私有数据目录】中的相对路径。
   *
   * 【刻意不是绝对路径】。绝对路径等于让调用方指定文件系统上任意位置，而
   * Provider 跑在自己的沙箱里（ProtectSystem=strict + 独立 UID），能读到的
   * 只有自己的数据目录——一个它读不到的绝对路径只会得到一个含义模糊的
   * "打不开"。用相对路径把交接位置写进协议：App 先把包放进约定位置。
   *
   * 必须是不含 ".." 的相对路径；Provider 与 nervud 都会再校验一次。
   * </pre>
   *
   * <code>string nspkg_relpath = 1 [json_name = "nspkgRelpath"];</code>
   * @return The nspkgRelpath.
   */
  java.lang.String getNspkgRelpath();
  /**
   * <pre>
   * .nspkg 在调用方【私有数据目录】中的相对路径。
   *
   * 【刻意不是绝对路径】。绝对路径等于让调用方指定文件系统上任意位置，而
   * Provider 跑在自己的沙箱里（ProtectSystem=strict + 独立 UID），能读到的
   * 只有自己的数据目录——一个它读不到的绝对路径只会得到一个含义模糊的
   * "打不开"。用相对路径把交接位置写进协议：App 先把包放进约定位置。
   *
   * 必须是不含 ".." 的相对路径；Provider 与 nervud 都会再校验一次。
   * </pre>
   *
   * <code>string nspkg_relpath = 1 [json_name = "nspkgRelpath"];</code>
   * @return The bytes for nspkgRelpath.
   */
  com.google.protobuf.ByteString
      getNspkgRelpathBytes();

  /**
   * <pre>
   * 用户在安装确认屏上同意的敏感权限 ID 列表。
   *
   * # 它解决的是什么
   *
   * USER_CONSENT 权限（perm.camera.capture 一类）在安装期能进
   * GrantedPermissions，但运行期 AllowedAt 要求 GrantState == GRANTED，默认是
   * NOT_REQUESTED。也就是说一个普通应用装上之后，它申请的敏感权限【永远】拿
   * 不到——应用无法自救（SDK 没有请求权限的 API），用户也没有界面可批。本字段
   * 让安装动作把这一问补上：装之前先把该包申请的敏感权限摊给用户看，用户同意
   * 哪些，安装成功后那些权限的运行期状态就直接落成 GRANTED。
   *
   * # 谁有资格填它
   *
   * 【只有系统的确认界面】。经 IPC 装包必须穿过 nervus.interface.permission.ui
   * 的 ConfirmInstall：INSTALL 的 needs_user_confirmation 是 true，而 nervud 的
   * 那道门只对持有 perm.permission.admin 的调用方放行，全系统只有
   * nervus.permissionui 持有它。因此普通应用填不进来——它连 INSTALL 都调不到。
   *
   * # 内核还会再过滤一遍
   *
   * nervud 只对【同意清单 ∩ 安装期授予集合 ∩ USER_CONSENT】三者的交集落库，
   * 越界的条目静默忽略：一条没申请过的、或不是 USER_CONSENT 的权限出现在这里，
   * 不该因为确认界面写错就变成一次真实授予。因此本字段是「用户同意了什么」的
   * 陈述，不是「请授予什么」的命令。
   * </pre>
   *
   * <code>repeated string consented_permissions = 2 [json_name = "consentedPermissions"];</code>
   * @return A list containing the consentedPermissions.
   */
  java.util.List<java.lang.String>
      getConsentedPermissionsList();
  /**
   * <pre>
   * 用户在安装确认屏上同意的敏感权限 ID 列表。
   *
   * # 它解决的是什么
   *
   * USER_CONSENT 权限（perm.camera.capture 一类）在安装期能进
   * GrantedPermissions，但运行期 AllowedAt 要求 GrantState == GRANTED，默认是
   * NOT_REQUESTED。也就是说一个普通应用装上之后，它申请的敏感权限【永远】拿
   * 不到——应用无法自救（SDK 没有请求权限的 API），用户也没有界面可批。本字段
   * 让安装动作把这一问补上：装之前先把该包申请的敏感权限摊给用户看，用户同意
   * 哪些，安装成功后那些权限的运行期状态就直接落成 GRANTED。
   *
   * # 谁有资格填它
   *
   * 【只有系统的确认界面】。经 IPC 装包必须穿过 nervus.interface.permission.ui
   * 的 ConfirmInstall：INSTALL 的 needs_user_confirmation 是 true，而 nervud 的
   * 那道门只对持有 perm.permission.admin 的调用方放行，全系统只有
   * nervus.permissionui 持有它。因此普通应用填不进来——它连 INSTALL 都调不到。
   *
   * # 内核还会再过滤一遍
   *
   * nervud 只对【同意清单 ∩ 安装期授予集合 ∩ USER_CONSENT】三者的交集落库，
   * 越界的条目静默忽略：一条没申请过的、或不是 USER_CONSENT 的权限出现在这里，
   * 不该因为确认界面写错就变成一次真实授予。因此本字段是「用户同意了什么」的
   * 陈述，不是「请授予什么」的命令。
   * </pre>
   *
   * <code>repeated string consented_permissions = 2 [json_name = "consentedPermissions"];</code>
   * @return The count of consentedPermissions.
   */
  int getConsentedPermissionsCount();
  /**
   * <pre>
   * 用户在安装确认屏上同意的敏感权限 ID 列表。
   *
   * # 它解决的是什么
   *
   * USER_CONSENT 权限（perm.camera.capture 一类）在安装期能进
   * GrantedPermissions，但运行期 AllowedAt 要求 GrantState == GRANTED，默认是
   * NOT_REQUESTED。也就是说一个普通应用装上之后，它申请的敏感权限【永远】拿
   * 不到——应用无法自救（SDK 没有请求权限的 API），用户也没有界面可批。本字段
   * 让安装动作把这一问补上：装之前先把该包申请的敏感权限摊给用户看，用户同意
   * 哪些，安装成功后那些权限的运行期状态就直接落成 GRANTED。
   *
   * # 谁有资格填它
   *
   * 【只有系统的确认界面】。经 IPC 装包必须穿过 nervus.interface.permission.ui
   * 的 ConfirmInstall：INSTALL 的 needs_user_confirmation 是 true，而 nervud 的
   * 那道门只对持有 perm.permission.admin 的调用方放行，全系统只有
   * nervus.permissionui 持有它。因此普通应用填不进来——它连 INSTALL 都调不到。
   *
   * # 内核还会再过滤一遍
   *
   * nervud 只对【同意清单 ∩ 安装期授予集合 ∩ USER_CONSENT】三者的交集落库，
   * 越界的条目静默忽略：一条没申请过的、或不是 USER_CONSENT 的权限出现在这里，
   * 不该因为确认界面写错就变成一次真实授予。因此本字段是「用户同意了什么」的
   * 陈述，不是「请授予什么」的命令。
   * </pre>
   *
   * <code>repeated string consented_permissions = 2 [json_name = "consentedPermissions"];</code>
   * @param index The index of the element to return.
   * @return The consentedPermissions at the given index.
   */
  java.lang.String getConsentedPermissions(int index);
  /**
   * <pre>
   * 用户在安装确认屏上同意的敏感权限 ID 列表。
   *
   * # 它解决的是什么
   *
   * USER_CONSENT 权限（perm.camera.capture 一类）在安装期能进
   * GrantedPermissions，但运行期 AllowedAt 要求 GrantState == GRANTED，默认是
   * NOT_REQUESTED。也就是说一个普通应用装上之后，它申请的敏感权限【永远】拿
   * 不到——应用无法自救（SDK 没有请求权限的 API），用户也没有界面可批。本字段
   * 让安装动作把这一问补上：装之前先把该包申请的敏感权限摊给用户看，用户同意
   * 哪些，安装成功后那些权限的运行期状态就直接落成 GRANTED。
   *
   * # 谁有资格填它
   *
   * 【只有系统的确认界面】。经 IPC 装包必须穿过 nervus.interface.permission.ui
   * 的 ConfirmInstall：INSTALL 的 needs_user_confirmation 是 true，而 nervud 的
   * 那道门只对持有 perm.permission.admin 的调用方放行，全系统只有
   * nervus.permissionui 持有它。因此普通应用填不进来——它连 INSTALL 都调不到。
   *
   * # 内核还会再过滤一遍
   *
   * nervud 只对【同意清单 ∩ 安装期授予集合 ∩ USER_CONSENT】三者的交集落库，
   * 越界的条目静默忽略：一条没申请过的、或不是 USER_CONSENT 的权限出现在这里，
   * 不该因为确认界面写错就变成一次真实授予。因此本字段是「用户同意了什么」的
   * 陈述，不是「请授予什么」的命令。
   * </pre>
   *
   * <code>repeated string consented_permissions = 2 [json_name = "consentedPermissions"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the consentedPermissions at the given index.
   */
  com.google.protobuf.ByteString
      getConsentedPermissionsBytes(int index);
}
