// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/transfer/v1/transfer_control.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.iface.transfer.v1;

public interface AbortTransferResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nervus.interface.transfer.v1.AbortTransferResponse)
    com.google.protobuf.MessageOrBuilder {
}
