// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/transfer/v1/transfer_control.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.iface.transfer.v1;

public interface AbortTransferRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nervus.interface.transfer.v1.AbortTransferRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 放弃 PREPARED Transfer。handler 失败、route 被取消或连接断开时 nervud 也必须
   * 自动 Abort；重复 Abort 必须幂等。
   * </pre>
   *
   * <code>bytes transfer_id = 1 [json_name = "transferId"];</code>
   * @return The transferId.
   */
  com.google.protobuf.ByteString getTransferId();
}
