// Nervus IPC v1 —— 通用 Method Registry 机制  [REWRITE-v1 / experimental]
//
// 本文件定义一套【与具体接口无关】的机制：把每个 method 的元数据
// （权限 / 风险级 / 是否需 ControlLease / 是否 operation / 是否需用户确认 /
// 请求响应消息类型）用 protobuf【自定义 option】挂在该接口的 method_id
// 枚举值上。一次 `buf generate`，这些元数据对 Go / Java / Kotlin 三语言同时
// 可见；nervud 与各 SDK 从生成的 descriptor 里【只读抽取】出 Method Registry，
// 而不是在各自语言里另抄一份清单。
//
// 为什么长在 proto 里（`00` 红线 #3/#4，NRCP §22.6）：
//   proto 是唯一 wire 真源。method_id → 权限/是否 operation 这类【清单】若写成
//   nervud 的编译期 Go 常量表，就等于把「加一个方法 / 加一个 OEM 接口」变成
//   「改内核、重编 nervud」。把清单挂在 option 上、由 descriptor 驱动，才能做到
//   ——OEM 只在自己的 .proto 挂 option，nervud 一行 Go 都不用改，新方法/新接口
//   就自动进 Registry（B1 dispatch 据此做 method 级权限 + operation 判定）。
//
// 自检：OEM 加一个 operation-returning 方法，要不要改 nervus-ipc 之外的代码？
//   ——不应该。只在它自己的 .proto 定义 method_id 枚举值并挂 (method_meta)。
//
// [REWRITE-v1] experimental：冻结前允许破坏性调整。扩展号 60001 一经发布
// 【永不改动、永不复用】——它是三语言 option 抽取的锚点，改了等于让所有已
// 生成代码里的 method_meta 失联。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nervus/ipc/v1/method_registry.proto

package ipcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RiskClass 是方法/资源的物理与隐私风险级别。它同时服务两个消费者：
//  1. Method Registry 的 method_meta.risk_class —— 逐方法的风险，喂给
//     Agent 工具目录与系统确认框决策（危险动作 Agent 只能请求，确认框由
//     系统持有，`00` 红线 #6）。
//  2. A4 的 ProviderDescriptor（ManagedResource.risk_class /
//     ProvidedInterface.resource_risk_floor）—— 接口/资源级的最低保护级。
//
// 因此它定义在这个【机制层】文件里，供接口 schema 与 Provider Descriptor 共同
// import，而不是塞进某一个具体接口。
//
// 所有枚举以 *_UNSPECIFIED = 0 起始并 fail closed：未知/漏填一律按「最保守」
// 处理（调用方不得把 UNSPECIFIED 当作 NORMAL 放行）。
type RiskClass int32

const (
	RiskClass_RISK_CLASS_UNSPECIFIED RiskClass = 0
	// 只读或无物理/隐私副作用（如 GetState / Subscribe）。
	RiskClass_RISK_CLASS_NORMAL RiskClass = 1
	// 触及隐私敏感数据（如麦克风/摄像头原始流）。
	RiskClass_RISK_CLASS_PRIVACY_SENSITIVE RiskClass = 2
	// 驱动物理执行器（如运动/机械臂/夹爪）。危险动作，Agent 需系统确认框。
	RiskClass_RISK_CLASS_PHYSICAL_CONTROL RiskClass = 3
	// 触及安全关键路径（Safety re-arm 等）。最高风险。
	RiskClass_RISK_CLASS_CRITICAL_SAFETY RiskClass = 4
)

// Enum value maps for RiskClass.
var (
	RiskClass_name = map[int32]string{
		0: "RISK_CLASS_UNSPECIFIED",
		1: "RISK_CLASS_NORMAL",
		2: "RISK_CLASS_PRIVACY_SENSITIVE",
		3: "RISK_CLASS_PHYSICAL_CONTROL",
		4: "RISK_CLASS_CRITICAL_SAFETY",
	}
	RiskClass_value = map[string]int32{
		"RISK_CLASS_UNSPECIFIED":       0,
		"RISK_CLASS_NORMAL":            1,
		"RISK_CLASS_PRIVACY_SENSITIVE": 2,
		"RISK_CLASS_PHYSICAL_CONTROL":  3,
		"RISK_CLASS_CRITICAL_SAFETY":   4,
	}
)

func (x RiskClass) Enum() *RiskClass {
	p := new(RiskClass)
	*p = x
	return p
}

func (x RiskClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskClass) Descriptor() protoreflect.EnumDescriptor {
	return file_nervus_ipc_v1_method_registry_proto_enumTypes[0].Descriptor()
}

func (RiskClass) Type() protoreflect.EnumType {
	return &file_nervus_ipc_v1_method_registry_proto_enumTypes[0]
}

func (x RiskClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskClass.Descriptor instead.
func (RiskClass) EnumDescriptor() ([]byte, []int) {
	return file_nervus_ipc_v1_method_registry_proto_rawDescGZIP(), []int{0}
}

// MethodMeta 是挂在【某个接口的 method_id 枚举值】上的元数据。
//
// 真相源永远是 proto：Go / SDK / Agent 只从生成的 EnumValueOptions 里读它，
// 不在别处另写清单。字段一经发布遵循 §10.12 兼容规则（号不复用、删除写
// reserved、新增字段须有安全默认）。
type MethodMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 稳定的数字 method_id，进 Request.method_id / Dispatch.method_id。
	//
	// 【必须等于所在枚举值的数字值】——枚举值本身承载 wire 上的 method_id，
	// 这里冗余一份是为了让「只拿到一条 MethodMeta」的消费者也自带 id，不必
	// 回查枚举。抽取工具会校验两者一致，不一致即 schema 错误。
	MethodId uint32 `protobuf:"varint,1,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
	// 调用该方法所需的 Permission id（如 nervus.permission.manipulator.control）。
	// 空 = 接口级 Resolve 已足够，method 级不再额外要权限（如只读状态查询）。
	//
	// 这是 method 级权限的【真相源】：B1 dispatch 据此在转发前做 method 级裁决。
	RequiredPermission string `protobuf:"bytes,2,opt,name=required_permission,json=requiredPermission,proto3" json:"required_permission,omitempty"`
	// 该方法的风险级，喂给 Agent 工具目录与系统确认框（见 RiskClass 注释）。
	RiskClass RiskClass `protobuf:"varint,3,opt,name=risk_class,json=riskClass,proto3,enum=nervus.ipc.v1.RiskClass" json:"risk_class,omitempty"`
	// 是否要求调用方持有该 Resource 的 ControlLease 才能调用。
	// 只读方法为 false；驱动执行器的方法为 true。
	RequiresControlLease bool `protobuf:"varint,4,opt,name=requires_control_lease,json=requiresControlLease,proto3" json:"requires_control_lease,omitempty"`
	// true → 该方法是长任务，dispatch 走 operation.Create（B5 Operation Manager），
	// 成功以 STATUS_CODE_ACCEPTED + operation_id 应答，终态另行查询/订阅。
	// false → 普通 request/response，成功以 OK 应答。
	ReturnsOperation bool `protobuf:"varint,5,opt,name=returns_operation,json=returnsOperation,proto3" json:"returns_operation,omitempty"`
	// Agent 工具元数据：调用前是否需要【系统持有的】用户确认框。
	//
	// 危险动作（如机械臂移动）应置 true。Agent Service 的 MCP adapter【只投影
	// 不产生】这个标记，Provider 也【不能自报调低】（Agent 文档 §4.3，A4 §3）。
	NeedsUserConfirmation bool `protobuf:"varint,6,opt,name=needs_user_confirmation,json=needsUserConfirmation,proto3" json:"needs_user_confirmation,omitempty"`
	// 请求消息的 Protobuf 全名，如
	// "nervus.interface.manipulator.v1.MoveToPoseRequest"。
	// SDK/Agent 据此定位请求类型；空表示无请求体（极少见）。
	RequestType string `protobuf:"bytes,7,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`
	// 响应/终态消息的 Protobuf 全名。
	//
	//	returns_operation=false → 普通 Success payload 的类型（可空 = 空 success）
	//	returns_operation=true  → operation 成功 result 的类型
	ResponseType string `protobuf:"bytes,8,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`
	// 是否为只读方法（不改任何状态、无副作用）。Agent 工具目录据此把「安全查询」
	// 与「有副作用的动作」分开呈现给模型；GetXxxState / SubscribeXxx 为 true。
	IsReadOnly bool `protobuf:"varint,9,opt,name=is_read_only,json=isReadOnly,proto3" json:"is_read_only,omitempty"`
	// 是否会驱动执行器产生物理运动。供 Agent/确认框/UI 对「会不会动起来」做快速判断。
	// 通常与 risk_class = RISK_CLASS_PHYSICAL_CONTROL 同现，但把它显式化避免消费者
	// 反推风险级。
	IsMotion      bool `protobuf:"varint,10,opt,name=is_motion,json=isMotion,proto3" json:"is_motion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodMeta) Reset() {
	*x = MethodMeta{}
	mi := &file_nervus_ipc_v1_method_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodMeta) ProtoMessage() {}

func (x *MethodMeta) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_ipc_v1_method_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodMeta.ProtoReflect.Descriptor instead.
func (*MethodMeta) Descriptor() ([]byte, []int) {
	return file_nervus_ipc_v1_method_registry_proto_rawDescGZIP(), []int{0}
}

func (x *MethodMeta) GetMethodId() uint32 {
	if x != nil {
		return x.MethodId
	}
	return 0
}

func (x *MethodMeta) GetRequiredPermission() string {
	if x != nil {
		return x.RequiredPermission
	}
	return ""
}

func (x *MethodMeta) GetRiskClass() RiskClass {
	if x != nil {
		return x.RiskClass
	}
	return RiskClass_RISK_CLASS_UNSPECIFIED
}

func (x *MethodMeta) GetRequiresControlLease() bool {
	if x != nil {
		return x.RequiresControlLease
	}
	return false
}

func (x *MethodMeta) GetReturnsOperation() bool {
	if x != nil {
		return x.ReturnsOperation
	}
	return false
}

func (x *MethodMeta) GetNeedsUserConfirmation() bool {
	if x != nil {
		return x.NeedsUserConfirmation
	}
	return false
}

func (x *MethodMeta) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *MethodMeta) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

func (x *MethodMeta) GetIsReadOnly() bool {
	if x != nil {
		return x.IsReadOnly
	}
	return false
}

func (x *MethodMeta) GetIsMotion() bool {
	if x != nil {
		return x.IsMotion
	}
	return false
}

var file_nervus_ipc_v1_method_registry_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*MethodMeta)(nil),
		Field:         60001,
		Name:          "nervus.ipc.v1.method_meta",
		Tag:           "bytes,60001,opt,name=method_meta",
		Filename:      "nervus/ipc/v1/method_registry.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional nervus.ipc.v1.MethodMeta method_meta = 60001;
	E_MethodMeta = &file_nervus_ipc_v1_method_registry_proto_extTypes[0]
)

var File_nervus_ipc_v1_method_registry_proto protoreflect.FileDescriptor

const file_nervus_ipc_v1_method_registry_proto_rawDesc = "" +
	"\n" +
	"#nervus/ipc/v1/method_registry.proto\x12\rnervus.ipc.v1\x1a google/protobuf/descriptor.proto\"\xb5\x03\n" +
	"\n" +
	"MethodMeta\x12\x1b\n" +
	"\tmethod_id\x18\x01 \x01(\rR\bmethodId\x12/\n" +
	"\x13required_permission\x18\x02 \x01(\tR\x12requiredPermission\x127\n" +
	"\n" +
	"risk_class\x18\x03 \x01(\x0e2\x18.nervus.ipc.v1.RiskClassR\triskClass\x124\n" +
	"\x16requires_control_lease\x18\x04 \x01(\bR\x14requiresControlLease\x12+\n" +
	"\x11returns_operation\x18\x05 \x01(\bR\x10returnsOperation\x126\n" +
	"\x17needs_user_confirmation\x18\x06 \x01(\bR\x15needsUserConfirmation\x12!\n" +
	"\frequest_type\x18\a \x01(\tR\vrequestType\x12#\n" +
	"\rresponse_type\x18\b \x01(\tR\fresponseType\x12 \n" +
	"\fis_read_only\x18\t \x01(\bR\n" +
	"isReadOnly\x12\x1b\n" +
	"\tis_motion\x18\n" +
	" \x01(\bR\bisMotion*\xa1\x01\n" +
	"\tRiskClass\x12\x1a\n" +
	"\x16RISK_CLASS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RISK_CLASS_NORMAL\x10\x01\x12 \n" +
	"\x1cRISK_CLASS_PRIVACY_SENSITIVE\x10\x02\x12\x1f\n" +
	"\x1bRISK_CLASS_PHYSICAL_CONTROL\x10\x03\x12\x1e\n" +
	"\x1aRISK_CLASS_CRITICAL_SAFETY\x10\x04:_\n" +
	"\vmethod_meta\x12!.google.protobuf.EnumValueOptions\x18\xe1\xd4\x03 \x01(\v2\x19.nervus.ipc.v1.MethodMetaR\n" +
	"methodMetaBk\n" +
	"\x19io.github.nervusos.ipc.v1B\x13MethodRegistryProtoP\x01Z7github.com/nervus-os/nervus-ipc/go/protocol/ipcv1;ipcv1b\x06proto3"

var (
	file_nervus_ipc_v1_method_registry_proto_rawDescOnce sync.Once
	file_nervus_ipc_v1_method_registry_proto_rawDescData []byte
)

func file_nervus_ipc_v1_method_registry_proto_rawDescGZIP() []byte {
	file_nervus_ipc_v1_method_registry_proto_rawDescOnce.Do(func() {
		file_nervus_ipc_v1_method_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nervus_ipc_v1_method_registry_proto_rawDesc), len(file_nervus_ipc_v1_method_registry_proto_rawDesc)))
	})
	return file_nervus_ipc_v1_method_registry_proto_rawDescData
}

var file_nervus_ipc_v1_method_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nervus_ipc_v1_method_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nervus_ipc_v1_method_registry_proto_goTypes = []any{
	(RiskClass)(0),                        // 0: nervus.ipc.v1.RiskClass
	(*MethodMeta)(nil),                    // 1: nervus.ipc.v1.MethodMeta
	(*descriptorpb.EnumValueOptions)(nil), // 2: google.protobuf.EnumValueOptions
}
var file_nervus_ipc_v1_method_registry_proto_depIdxs = []int32{
	0, // 0: nervus.ipc.v1.MethodMeta.risk_class:type_name -> nervus.ipc.v1.RiskClass
	2, // 1: nervus.ipc.v1.method_meta:extendee -> google.protobuf.EnumValueOptions
	1, // 2: nervus.ipc.v1.method_meta:type_name -> nervus.ipc.v1.MethodMeta
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nervus_ipc_v1_method_registry_proto_init() }
func file_nervus_ipc_v1_method_registry_proto_init() {
	if File_nervus_ipc_v1_method_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nervus_ipc_v1_method_registry_proto_rawDesc), len(file_nervus_ipc_v1_method_registry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_nervus_ipc_v1_method_registry_proto_goTypes,
		DependencyIndexes: file_nervus_ipc_v1_method_registry_proto_depIdxs,
		EnumInfos:         file_nervus_ipc_v1_method_registry_proto_enumTypes,
		MessageInfos:      file_nervus_ipc_v1_method_registry_proto_msgTypes,
		ExtensionInfos:    file_nervus_ipc_v1_method_registry_proto_extTypes,
	}.Build()
	File_nervus_ipc_v1_method_registry_proto = out.File
	file_nervus_ipc_v1_method_registry_proto_goTypes = nil
	file_nervus_ipc_v1_method_registry_proto_depIdxs = nil
}
