// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/manipulator/v1/manipulator.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.iface.manipulator.v1;

/**
 * <pre>
 * ManipulatorMethod 的每个枚举值【就是】该方法的 wire method_id（进
 * Request.method_id）。逐值挂 (nervus.ipc.v1.method_meta)，让 nervud 与 SDK
 * 从 descriptor 抽取 Registry，不在 Go/Kotlin 里另写清单。
 *
 * method_meta.method_id 冗余等于枚举数字值（抽取工具会校验一致）。
 * </pre>
 *
 * Protobuf enum {@code nervus.interface.manipulator.v1.ManipulatorMethod}
 */
public enum ManipulatorMethod
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MANIPULATOR_METHOD_UNSPECIFIED = 0;</code>
   */
  MANIPULATOR_METHOD_UNSPECIFIED(0),
  /**
   * <pre>
   * 只读：关节位 / 末端位姿 / readiness / limits / epoch。
   * </pre>
   *
   * <code>MANIPULATOR_METHOD_GET_ARM_STATE = 1 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  MANIPULATOR_METHOD_GET_ARM_STATE(1),
  /**
   * <pre>
   * 状态事件流（订阅，非 request/response）。响应类型即事件 payload 类型。
   * </pre>
   *
   * <code>MANIPULATOR_METHOD_SUBSCRIBE_ARM_STATE = 2 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  MANIPULATOR_METHOD_SUBSCRIBE_ARM_STATE(2),
  /**
   * <pre>
   * 末端移到笛卡尔位姿（含 frame）。长任务 → operation。
   * </pre>
   *
   * <code>MANIPULATOR_METHOD_MOVE_TO_POSE = 3 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  MANIPULATOR_METHOD_MOVE_TO_POSE(3),
  /**
   * <pre>
   * 关节空间轨迹。长任务 → operation。
   * </pre>
   *
   * <code>MANIPULATOR_METHOD_MOVE_JOINT_TRAJECTORY = 4 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  MANIPULATOR_METHOD_MOVE_JOINT_TRAJECTORY(4),
  /**
   * <pre>
   * 回零 / 收拢位。长任务 → operation。
   * </pre>
   *
   * <code>MANIPULATOR_METHOD_GO_HOME = 5 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  MANIPULATOR_METHOD_GO_HOME(5),
  /**
   * <pre>
   * 夹爪开合（短命令，非 operation），但仍驱动执行器 → 需 lease。
   * </pre>
   *
   * <code>MANIPULATOR_METHOD_SET_GRIPPER = 6 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  MANIPULATOR_METHOD_SET_GRIPPER(6),
  /**
   * <pre>
   * 普通受控停止（非 SafetyHalt）。需 lease，短命令。
   * </pre>
   *
   * <code>MANIPULATOR_METHOD_STOP = 7 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  MANIPULATOR_METHOD_STOP(7),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ManipulatorMethod.class.getName());
  }
  /**
   * <code>MANIPULATOR_METHOD_UNSPECIFIED = 0;</code>
   */
  public static final int MANIPULATOR_METHOD_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * 只读：关节位 / 末端位姿 / readiness / limits / epoch。
   * </pre>
   *
   * <code>MANIPULATOR_METHOD_GET_ARM_STATE = 1 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  public static final int MANIPULATOR_METHOD_GET_ARM_STATE_VALUE = 1;
  /**
   * <pre>
   * 状态事件流（订阅，非 request/response）。响应类型即事件 payload 类型。
   * </pre>
   *
   * <code>MANIPULATOR_METHOD_SUBSCRIBE_ARM_STATE = 2 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  public static final int MANIPULATOR_METHOD_SUBSCRIBE_ARM_STATE_VALUE = 2;
  /**
   * <pre>
   * 末端移到笛卡尔位姿（含 frame）。长任务 → operation。
   * </pre>
   *
   * <code>MANIPULATOR_METHOD_MOVE_TO_POSE = 3 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  public static final int MANIPULATOR_METHOD_MOVE_TO_POSE_VALUE = 3;
  /**
   * <pre>
   * 关节空间轨迹。长任务 → operation。
   * </pre>
   *
   * <code>MANIPULATOR_METHOD_MOVE_JOINT_TRAJECTORY = 4 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  public static final int MANIPULATOR_METHOD_MOVE_JOINT_TRAJECTORY_VALUE = 4;
  /**
   * <pre>
   * 回零 / 收拢位。长任务 → operation。
   * </pre>
   *
   * <code>MANIPULATOR_METHOD_GO_HOME = 5 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  public static final int MANIPULATOR_METHOD_GO_HOME_VALUE = 5;
  /**
   * <pre>
   * 夹爪开合（短命令，非 operation），但仍驱动执行器 → 需 lease。
   * </pre>
   *
   * <code>MANIPULATOR_METHOD_SET_GRIPPER = 6 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  public static final int MANIPULATOR_METHOD_SET_GRIPPER_VALUE = 6;
  /**
   * <pre>
   * 普通受控停止（非 SafetyHalt）。需 lease，短命令。
   * </pre>
   *
   * <code>MANIPULATOR_METHOD_STOP = 7 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  public static final int MANIPULATOR_METHOD_STOP_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ManipulatorMethod valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ManipulatorMethod forNumber(int value) {
    switch (value) {
      case 0: return MANIPULATOR_METHOD_UNSPECIFIED;
      case 1: return MANIPULATOR_METHOD_GET_ARM_STATE;
      case 2: return MANIPULATOR_METHOD_SUBSCRIBE_ARM_STATE;
      case 3: return MANIPULATOR_METHOD_MOVE_TO_POSE;
      case 4: return MANIPULATOR_METHOD_MOVE_JOINT_TRAJECTORY;
      case 5: return MANIPULATOR_METHOD_GO_HOME;
      case 6: return MANIPULATOR_METHOD_SET_GRIPPER;
      case 7: return MANIPULATOR_METHOD_STOP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ManipulatorMethod>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ManipulatorMethod> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ManipulatorMethod>() {
          public ManipulatorMethod findValueByNumber(int number) {
            return ManipulatorMethod.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.github.nervusos.iface.manipulator.v1.ManipulatorProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final ManipulatorMethod[] VALUES = values();

  public static ManipulatorMethod valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ManipulatorMethod(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:nervus.interface.manipulator.v1.ManipulatorMethod)
}

