// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/manipulator/v1/manipulator.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.iface.manipulator.v1;

/**
 * <pre>
 * MoveJointTrajectoryPoint —— 关节轨迹上的一个途经点。
 * </pre>
 *
 * Protobuf type {@code nervus.interface.manipulator.v1.MoveJointTrajectoryPoint}
 */
public final class MoveJointTrajectoryPoint extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:nervus.interface.manipulator.v1.MoveJointTrajectoryPoint)
    MoveJointTrajectoryPointOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      MoveJointTrajectoryPoint.class.getName());
  }
  // Use MoveJointTrajectoryPoint.newBuilder() to construct.
  private MoveJointTrajectoryPoint(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MoveJointTrajectoryPoint() {
    positionRad_ = emptyDoubleList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.nervusos.iface.manipulator.v1.ManipulatorProto.internal_static_nervus_interface_manipulator_v1_MoveJointTrajectoryPoint_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.nervusos.iface.manipulator.v1.ManipulatorProto.internal_static_nervus_interface_manipulator_v1_MoveJointTrajectoryPoint_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint.class, io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint.Builder.class);
  }

  public static final int POSITION_RAD_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.DoubleList positionRad_ =
      emptyDoubleList();
  /**
   * <pre>
   * 各关节目标角，rad（索引对齐 ArmState）
   * </pre>
   *
   * <code>repeated double position_rad = 1 [json_name = "positionRad"];</code>
   * @return A list containing the positionRad.
   */
  @java.lang.Override
  public java.util.List<java.lang.Double>
      getPositionRadList() {
    return positionRad_;
  }
  /**
   * <pre>
   * 各关节目标角，rad（索引对齐 ArmState）
   * </pre>
   *
   * <code>repeated double position_rad = 1 [json_name = "positionRad"];</code>
   * @return The count of positionRad.
   */
  public int getPositionRadCount() {
    return positionRad_.size();
  }
  /**
   * <pre>
   * 各关节目标角，rad（索引对齐 ArmState）
   * </pre>
   *
   * <code>repeated double position_rad = 1 [json_name = "positionRad"];</code>
   * @param index The index of the element to return.
   * @return The positionRad at the given index.
   */
  public double getPositionRad(int index) {
    return positionRad_.getDouble(index);
  }
  private int positionRadMemoizedSerializedSize = -1;

  public static final int TIME_FROM_START_NANOS_FIELD_NUMBER = 2;
  private long timeFromStartNanos_ = 0L;
  /**
   * <pre>
   * 相对轨迹起点的时间，ns，单调递增
   * </pre>
   *
   * <code>int64 time_from_start_nanos = 2 [json_name = "timeFromStartNanos"];</code>
   * @return The timeFromStartNanos.
   */
  @java.lang.Override
  public long getTimeFromStartNanos() {
    return timeFromStartNanos_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getPositionRadList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(positionRadMemoizedSerializedSize);
    }
    for (int i = 0; i < positionRad_.size(); i++) {
      output.writeDoubleNoTag(positionRad_.getDouble(i));
    }
    if (timeFromStartNanos_ != 0L) {
      output.writeInt64(2, timeFromStartNanos_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      dataSize = 8 * getPositionRadList().size();
      size += dataSize;
      if (!getPositionRadList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      positionRadMemoizedSerializedSize = dataSize;
    }
    if (timeFromStartNanos_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timeFromStartNanos_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint)) {
      return super.equals(obj);
    }
    io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint other = (io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint) obj;

    if (!getPositionRadList()
        .equals(other.getPositionRadList())) return false;
    if (getTimeFromStartNanos()
        != other.getTimeFromStartNanos()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPositionRadCount() > 0) {
      hash = (37 * hash) + POSITION_RAD_FIELD_NUMBER;
      hash = (53 * hash) + getPositionRadList().hashCode();
    }
    hash = (37 * hash) + TIME_FROM_START_NANOS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeFromStartNanos());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * MoveJointTrajectoryPoint —— 关节轨迹上的一个途经点。
   * </pre>
   *
   * Protobuf type {@code nervus.interface.manipulator.v1.MoveJointTrajectoryPoint}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nervus.interface.manipulator.v1.MoveJointTrajectoryPoint)
      io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPointOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.nervusos.iface.manipulator.v1.ManipulatorProto.internal_static_nervus_interface_manipulator_v1_MoveJointTrajectoryPoint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.nervusos.iface.manipulator.v1.ManipulatorProto.internal_static_nervus_interface_manipulator_v1_MoveJointTrajectoryPoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint.class, io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint.Builder.class);
    }

    // Construct using io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      positionRad_ = emptyDoubleList();
      timeFromStartNanos_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.nervusos.iface.manipulator.v1.ManipulatorProto.internal_static_nervus_interface_manipulator_v1_MoveJointTrajectoryPoint_descriptor;
    }

    @java.lang.Override
    public io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint getDefaultInstanceForType() {
      return io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint build() {
      io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint buildPartial() {
      io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint result = new io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        positionRad_.makeImmutable();
        result.positionRad_ = positionRad_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timeFromStartNanos_ = timeFromStartNanos_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint) {
        return mergeFrom((io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint other) {
      if (other == io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint.getDefaultInstance()) return this;
      if (!other.positionRad_.isEmpty()) {
        if (positionRad_.isEmpty()) {
          positionRad_ = other.positionRad_;
          positionRad_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensurePositionRadIsMutable();
          positionRad_.addAll(other.positionRad_);
        }
        onChanged();
      }
      if (other.getTimeFromStartNanos() != 0L) {
        setTimeFromStartNanos(other.getTimeFromStartNanos());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              double v = input.readDouble();
              ensurePositionRadIsMutable();
              positionRad_.addDouble(v);
              break;
            } // case 9
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensurePositionRadIsMutable(alloc / 8);
              while (input.getBytesUntilLimit() > 0) {
                positionRad_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            } // case 10
            case 16: {
              timeFromStartNanos_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.DoubleList positionRad_ = emptyDoubleList();
    private void ensurePositionRadIsMutable() {
      if (!positionRad_.isModifiable()) {
        positionRad_ = makeMutableCopy(positionRad_);
      }
      bitField0_ |= 0x00000001;
    }
    private void ensurePositionRadIsMutable(int capacity) {
      if (!positionRad_.isModifiable()) {
        positionRad_ = makeMutableCopy(positionRad_, capacity);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * 各关节目标角，rad（索引对齐 ArmState）
     * </pre>
     *
     * <code>repeated double position_rad = 1 [json_name = "positionRad"];</code>
     * @return A list containing the positionRad.
     */
    public java.util.List<java.lang.Double>
        getPositionRadList() {
      positionRad_.makeImmutable();
      return positionRad_;
    }
    /**
     * <pre>
     * 各关节目标角，rad（索引对齐 ArmState）
     * </pre>
     *
     * <code>repeated double position_rad = 1 [json_name = "positionRad"];</code>
     * @return The count of positionRad.
     */
    public int getPositionRadCount() {
      return positionRad_.size();
    }
    /**
     * <pre>
     * 各关节目标角，rad（索引对齐 ArmState）
     * </pre>
     *
     * <code>repeated double position_rad = 1 [json_name = "positionRad"];</code>
     * @param index The index of the element to return.
     * @return The positionRad at the given index.
     */
    public double getPositionRad(int index) {
      return positionRad_.getDouble(index);
    }
    /**
     * <pre>
     * 各关节目标角，rad（索引对齐 ArmState）
     * </pre>
     *
     * <code>repeated double position_rad = 1 [json_name = "positionRad"];</code>
     * @param index The index to set the value at.
     * @param value The positionRad to set.
     * @return This builder for chaining.
     */
    public Builder setPositionRad(
        int index, double value) {

      ensurePositionRadIsMutable();
      positionRad_.setDouble(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 各关节目标角，rad（索引对齐 ArmState）
     * </pre>
     *
     * <code>repeated double position_rad = 1 [json_name = "positionRad"];</code>
     * @param value The positionRad to add.
     * @return This builder for chaining.
     */
    public Builder addPositionRad(double value) {

      ensurePositionRadIsMutable();
      positionRad_.addDouble(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 各关节目标角，rad（索引对齐 ArmState）
     * </pre>
     *
     * <code>repeated double position_rad = 1 [json_name = "positionRad"];</code>
     * @param values The positionRad to add.
     * @return This builder for chaining.
     */
    public Builder addAllPositionRad(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensurePositionRadIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, positionRad_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 各关节目标角，rad（索引对齐 ArmState）
     * </pre>
     *
     * <code>repeated double position_rad = 1 [json_name = "positionRad"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPositionRad() {
      positionRad_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private long timeFromStartNanos_ ;
    /**
     * <pre>
     * 相对轨迹起点的时间，ns，单调递增
     * </pre>
     *
     * <code>int64 time_from_start_nanos = 2 [json_name = "timeFromStartNanos"];</code>
     * @return The timeFromStartNanos.
     */
    @java.lang.Override
    public long getTimeFromStartNanos() {
      return timeFromStartNanos_;
    }
    /**
     * <pre>
     * 相对轨迹起点的时间，ns，单调递增
     * </pre>
     *
     * <code>int64 time_from_start_nanos = 2 [json_name = "timeFromStartNanos"];</code>
     * @param value The timeFromStartNanos to set.
     * @return This builder for chaining.
     */
    public Builder setTimeFromStartNanos(long value) {

      timeFromStartNanos_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 相对轨迹起点的时间，ns，单调递增
     * </pre>
     *
     * <code>int64 time_from_start_nanos = 2 [json_name = "timeFromStartNanos"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeFromStartNanos() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timeFromStartNanos_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:nervus.interface.manipulator.v1.MoveJointTrajectoryPoint)
  }

  // @@protoc_insertion_point(class_scope:nervus.interface.manipulator.v1.MoveJointTrajectoryPoint)
  private static final io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint();
  }

  public static io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MoveJointTrajectoryPoint>
      PARSER = new com.google.protobuf.AbstractParser<MoveJointTrajectoryPoint>() {
    @java.lang.Override
    public MoveJointTrajectoryPoint parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MoveJointTrajectoryPoint> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MoveJointTrajectoryPoint> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.nervusos.iface.manipulator.v1.MoveJointTrajectoryPoint getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

