// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/manipulator/v1/manipulator.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.iface.manipulator.v1;

public interface MoveToPoseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nervus.interface.manipulator.v1.MoveToPoseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.nervus.interface.manipulator.v1.Pose target = 1 [json_name = "target"];</code>
   * @return Whether the target field is set.
   */
  boolean hasTarget();
  /**
   * <code>.nervus.interface.manipulator.v1.Pose target = 1 [json_name = "target"];</code>
   * @return The target.
   */
  io.github.nervusos.iface.manipulator.v1.Pose getTarget();
  /**
   * <code>.nervus.interface.manipulator.v1.Pose target = 1 [json_name = "target"];</code>
   */
  io.github.nervusos.iface.manipulator.v1.PoseOrBuilder getTargetOrBuilder();

  /**
   * <pre>
   * 速度缩放，取值 0..1；越界 → INVALID_ARGUMENT
   * </pre>
   *
   * <code>double max_vel_scale = 2 [json_name = "maxVelScale"];</code>
   * @return The maxVelScale.
   */
  double getMaxVelScale();
}
