// Nervus 标准接口 · Manipulator@1  [REWRITE-v1 / experimental]
//
// interface_id = nervus.interface.manipulator.arm ，major = 1，experimental。
//   Feature     = nervus.feature.manipulator.arm
//   Permission  = perm.manipulator.control
//   Resource    = nervus.resource.manipulator.arm （role 如 main/left/right）
//
// 语义边界（NRCP §17 / §13.2）：
//   机械臂不是移动底座，语义是【关节 / 末端位姿 / 轨迹 / 夹爪 / 回零】。
//   逆运动学、轨迹规划、碰撞检测本身是 OEM Provider 的活，本 schema【不】实现
//   算法，只定义边界消息、method_id 与错误语义。
//
// 长任务是 operation（NRCP §11）：MoveToPose / MoveJointTrajectory / GoHome 三个
//   移动类方法是长任务，method_meta.returns_operation = true，dispatch 走
//   operation.Create（B5），成功以 STATUS_CODE_ACCEPTED + operation_id 应答；
//   SetGripper / Stop 是短命令，非 operation。
//
// 单位与坐标系（NRCP §17.1，务必读进注释）：
//   关节角 = rad；关节角速度 = rad/s；笛卡尔位置 = m；四元数无量纲；
//   坐标系一律用显式 frame 字符串（如 "base_link"），【禁止】含糊或隐式默认。
//
// [REWRITE-v1] experimental：v2 前允许破坏性调整，第三方不得假设已稳定。
//   正式冻结后遵循 §10.12：method_id / 字段号 / 枚举值永不改含义或复用，
//   删除写 reserved，新增字段须有安全默认，枚举以 *_UNSPECIFIED = 0 起始。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nervus/interface/manipulator/v1/manipulator.proto

package manipulatorv1

import (
	_ "github.com/nervus-os/nervus-ipc/go/protocol/ipcv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ManipulatorMethod 的每个枚举值【就是】该方法的 wire method_id（进
// Request.method_id）。逐值挂 (nervus.ipc.v1.method_meta)，让 nervud 与 SDK
// 从 descriptor 抽取 Registry，不在 Go/Kotlin 里另写清单。
//
// method_meta.method_id 冗余等于枚举数字值（抽取工具会校验一致）。
type ManipulatorMethod int32

const (
	ManipulatorMethod_MANIPULATOR_METHOD_UNSPECIFIED ManipulatorMethod = 0
	// 只读：关节位 / 末端位姿 / readiness / limits / epoch。
	ManipulatorMethod_MANIPULATOR_METHOD_GET_ARM_STATE ManipulatorMethod = 1
	// 状态事件流（订阅，非 request/response）。响应类型即事件 payload 类型。
	ManipulatorMethod_MANIPULATOR_METHOD_SUBSCRIBE_ARM_STATE ManipulatorMethod = 2
	// 末端移到笛卡尔位姿（含 frame）。长任务 → operation。
	ManipulatorMethod_MANIPULATOR_METHOD_MOVE_TO_POSE ManipulatorMethod = 3
	// 关节空间轨迹。长任务 → operation。
	ManipulatorMethod_MANIPULATOR_METHOD_MOVE_JOINT_TRAJECTORY ManipulatorMethod = 4
	// 回零 / 收拢位。长任务 → operation。
	ManipulatorMethod_MANIPULATOR_METHOD_GO_HOME ManipulatorMethod = 5
	// 夹爪开合（短命令，非 operation），但仍驱动执行器 → 需 lease。
	ManipulatorMethod_MANIPULATOR_METHOD_SET_GRIPPER ManipulatorMethod = 6
	// 普通受控停止（非 SafetyHalt）。需 lease，短命令。
	ManipulatorMethod_MANIPULATOR_METHOD_STOP ManipulatorMethod = 7
)

// Enum value maps for ManipulatorMethod.
var (
	ManipulatorMethod_name = map[int32]string{
		0: "MANIPULATOR_METHOD_UNSPECIFIED",
		1: "MANIPULATOR_METHOD_GET_ARM_STATE",
		2: "MANIPULATOR_METHOD_SUBSCRIBE_ARM_STATE",
		3: "MANIPULATOR_METHOD_MOVE_TO_POSE",
		4: "MANIPULATOR_METHOD_MOVE_JOINT_TRAJECTORY",
		5: "MANIPULATOR_METHOD_GO_HOME",
		6: "MANIPULATOR_METHOD_SET_GRIPPER",
		7: "MANIPULATOR_METHOD_STOP",
	}
	ManipulatorMethod_value = map[string]int32{
		"MANIPULATOR_METHOD_UNSPECIFIED":           0,
		"MANIPULATOR_METHOD_GET_ARM_STATE":         1,
		"MANIPULATOR_METHOD_SUBSCRIBE_ARM_STATE":   2,
		"MANIPULATOR_METHOD_MOVE_TO_POSE":          3,
		"MANIPULATOR_METHOD_MOVE_JOINT_TRAJECTORY": 4,
		"MANIPULATOR_METHOD_GO_HOME":               5,
		"MANIPULATOR_METHOD_SET_GRIPPER":           6,
		"MANIPULATOR_METHOD_STOP":                  7,
	}
)

func (x ManipulatorMethod) Enum() *ManipulatorMethod {
	p := new(ManipulatorMethod)
	*p = x
	return p
}

func (x ManipulatorMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManipulatorMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_nervus_interface_manipulator_v1_manipulator_proto_enumTypes[0].Descriptor()
}

func (ManipulatorMethod) Type() protoreflect.EnumType {
	return &file_nervus_interface_manipulator_v1_manipulator_proto_enumTypes[0]
}

func (x ManipulatorMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManipulatorMethod.Descriptor instead.
func (ManipulatorMethod) EnumDescriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{0}
}

// ArmReadiness —— 机械臂就绪态。*_UNSPECIFIED=0 fail closed。
type ArmReadiness int32

const (
	ArmReadiness_ARM_READINESS_UNSPECIFIED   ArmReadiness = 0
	ArmReadiness_ARM_READINESS_READY         ArmReadiness = 1
	ArmReadiness_ARM_READINESS_NOT_READY     ArmReadiness = 2
	ArmReadiness_ARM_READINESS_TRANSITIONING ArmReadiness = 3
	ArmReadiness_ARM_READINESS_FAULT         ArmReadiness = 4
)

// Enum value maps for ArmReadiness.
var (
	ArmReadiness_name = map[int32]string{
		0: "ARM_READINESS_UNSPECIFIED",
		1: "ARM_READINESS_READY",
		2: "ARM_READINESS_NOT_READY",
		3: "ARM_READINESS_TRANSITIONING",
		4: "ARM_READINESS_FAULT",
	}
	ArmReadiness_value = map[string]int32{
		"ARM_READINESS_UNSPECIFIED":   0,
		"ARM_READINESS_READY":         1,
		"ARM_READINESS_NOT_READY":     2,
		"ARM_READINESS_TRANSITIONING": 3,
		"ARM_READINESS_FAULT":         4,
	}
)

func (x ArmReadiness) Enum() *ArmReadiness {
	p := new(ArmReadiness)
	*p = x
	return p
}

func (x ArmReadiness) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArmReadiness) Descriptor() protoreflect.EnumDescriptor {
	return file_nervus_interface_manipulator_v1_manipulator_proto_enumTypes[1].Descriptor()
}

func (ArmReadiness) Type() protoreflect.EnumType {
	return &file_nervus_interface_manipulator_v1_manipulator_proto_enumTypes[1]
}

func (x ArmReadiness) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArmReadiness.Descriptor instead.
func (ArmReadiness) EnumDescriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{1}
}

// ManipulatorReason —— Manipulator 失败的 typed error_detail reason。
//
// 业务失败一律走 Failure outcome（通用 StatusCode 位置 A + 本 reason 位置 B），
// 【不得】藏进 Success payload（NRCP §19）。PERMISSION_DENIED / DEADLINE_EXCEEDED
// / CANCELLED / UNAVAILABLE 只作位置 A 通用码，不在此重复。
//
// 所有值以 *_UNSPECIFIED=0 起始，fail closed。
type ManipulatorReason int32

const (
	ManipulatorReason_MANIPULATOR_REASON_UNSPECIFIED          ManipulatorReason = 0
	ManipulatorReason_MANIPULATOR_REASON_NOT_READY            ManipulatorReason = 1 // 未进入 READY
	ManipulatorReason_MANIPULATOR_REASON_SAFETY_LATCHED       ManipulatorReason = 2 // Safety 已锁存
	ManipulatorReason_MANIPULATOR_REASON_STALE_EPOCH          ManipulatorReason = 3 // 命令属已撤销的 motion epoch
	ManipulatorReason_MANIPULATOR_REASON_CONTROL_NOT_HELD     ManipulatorReason = 4 // 未持有 ControlLease
	ManipulatorReason_MANIPULATOR_REASON_JOINT_LIMIT          ManipulatorReason = 5 // 超关节限位
	ManipulatorReason_MANIPULATOR_REASON_UNREACHABLE_POSE     ManipulatorReason = 6 // IK 无解 / 超工作空间
	ManipulatorReason_MANIPULATOR_REASON_COLLISION            ManipulatorReason = 7 // 碰撞检测拦截
	ManipulatorReason_MANIPULATOR_REASON_RESOURCE_UNAVAILABLE ManipulatorReason = 8 // Resource/链路不可用
	ManipulatorReason_MANIPULATOR_REASON_RESOURCE_FAULT       ManipulatorReason = 9 // Resource 故障
)

// Enum value maps for ManipulatorReason.
var (
	ManipulatorReason_name = map[int32]string{
		0: "MANIPULATOR_REASON_UNSPECIFIED",
		1: "MANIPULATOR_REASON_NOT_READY",
		2: "MANIPULATOR_REASON_SAFETY_LATCHED",
		3: "MANIPULATOR_REASON_STALE_EPOCH",
		4: "MANIPULATOR_REASON_CONTROL_NOT_HELD",
		5: "MANIPULATOR_REASON_JOINT_LIMIT",
		6: "MANIPULATOR_REASON_UNREACHABLE_POSE",
		7: "MANIPULATOR_REASON_COLLISION",
		8: "MANIPULATOR_REASON_RESOURCE_UNAVAILABLE",
		9: "MANIPULATOR_REASON_RESOURCE_FAULT",
	}
	ManipulatorReason_value = map[string]int32{
		"MANIPULATOR_REASON_UNSPECIFIED":          0,
		"MANIPULATOR_REASON_NOT_READY":            1,
		"MANIPULATOR_REASON_SAFETY_LATCHED":       2,
		"MANIPULATOR_REASON_STALE_EPOCH":          3,
		"MANIPULATOR_REASON_CONTROL_NOT_HELD":     4,
		"MANIPULATOR_REASON_JOINT_LIMIT":          5,
		"MANIPULATOR_REASON_UNREACHABLE_POSE":     6,
		"MANIPULATOR_REASON_COLLISION":            7,
		"MANIPULATOR_REASON_RESOURCE_UNAVAILABLE": 8,
		"MANIPULATOR_REASON_RESOURCE_FAULT":       9,
	}
)

func (x ManipulatorReason) Enum() *ManipulatorReason {
	p := new(ManipulatorReason)
	*p = x
	return p
}

func (x ManipulatorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManipulatorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_nervus_interface_manipulator_v1_manipulator_proto_enumTypes[2].Descriptor()
}

func (ManipulatorReason) Type() protoreflect.EnumType {
	return &file_nervus_interface_manipulator_v1_manipulator_proto_enumTypes[2]
}

func (x ManipulatorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManipulatorReason.Descriptor instead.
func (ManipulatorReason) EnumDescriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{2}
}

// JointState —— 关节空间状态。position/velocity 的索引与 Provider 的关节顺序
// 一一对应（顺序由 Provider Descriptor / ArmState.limits 长度约束）。
type JointState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionRad   []float64              `protobuf:"fixed64,1,rep,packed,name=position_rad,json=positionRad,proto3" json:"position_rad,omitempty"`      // 各关节角，rad
	VelocityRadS  []float64              `protobuf:"fixed64,2,rep,packed,name=velocity_rad_s,json=velocityRadS,proto3" json:"velocity_rad_s,omitempty"` // 各关节角速度，rad/s
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JointState) Reset() {
	*x = JointState{}
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JointState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JointState) ProtoMessage() {}

func (x *JointState) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JointState.ProtoReflect.Descriptor instead.
func (*JointState) Descriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{0}
}

func (x *JointState) GetPositionRad() []float64 {
	if x != nil {
		return x.PositionRad
	}
	return nil
}

func (x *JointState) GetVelocityRadS() []float64 {
	if x != nil {
		return x.VelocityRadS
	}
	return nil
}

// Pose —— 笛卡尔位姿，位置 m + 单位四元数（无量纲）。frame 必须显式给出。
type Pose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         string                 `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"` // 坐标系，如 "base_link"。【禁止含糊】：空 = INVALID_ARGUMENT。
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`       // m
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`       // m
	Z             float64                `protobuf:"fixed64,4,opt,name=z,proto3" json:"z,omitempty"`       // m
	Qx            float64                `protobuf:"fixed64,5,opt,name=qx,proto3" json:"qx,omitempty"`     // 四元数分量（无量纲）
	Qy            float64                `protobuf:"fixed64,6,opt,name=qy,proto3" json:"qy,omitempty"`
	Qz            float64                `protobuf:"fixed64,7,opt,name=qz,proto3" json:"qz,omitempty"`
	Qw            float64                `protobuf:"fixed64,8,opt,name=qw,proto3" json:"qw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pose) Reset() {
	*x = Pose{}
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pose) ProtoMessage() {}

func (x *Pose) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pose.ProtoReflect.Descriptor instead.
func (*Pose) Descriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{1}
}

func (x *Pose) GetFrame() string {
	if x != nil {
		return x.Frame
	}
	return ""
}

func (x *Pose) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pose) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Pose) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Pose) GetQx() float64 {
	if x != nil {
		return x.Qx
	}
	return 0
}

func (x *Pose) GetQy() float64 {
	if x != nil {
		return x.Qy
	}
	return 0
}

func (x *Pose) GetQz() float64 {
	if x != nil {
		return x.Qz
	}
	return 0
}

func (x *Pose) GetQw() float64 {
	if x != nil {
		return x.Qw
	}
	return 0
}

// ArmState —— GetArmState / SubscribeArmState 的状态载荷。
type ArmState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Readiness         ArmReadiness           `protobuf:"varint,1,opt,name=readiness,proto3,enum=nervus.interface.manipulator.v1.ArmReadiness" json:"readiness,omitempty"`
	Joints            *JointState            `protobuf:"bytes,2,opt,name=joints,proto3" json:"joints,omitempty"`
	TcpPose           *Pose                  `protobuf:"bytes,3,opt,name=tcp_pose,json=tcpPose,proto3" json:"tcp_pose,omitempty"`                                  // 末端（tool center point）位姿
	JointLowerRad     []float64              `protobuf:"fixed64,4,rep,packed,name=joint_lower_rad,json=jointLowerRad,proto3" json:"joint_lower_rad,omitempty"`     // 各关节下限，rad（索引对齐 joints）
	JointUpperRad     []float64              `protobuf:"fixed64,5,rep,packed,name=joint_upper_rad,json=jointUpperRad,proto3" json:"joint_upper_rad,omitempty"`     // 各关节上限，rad
	ActiveMotionEpoch uint64                 `protobuf:"varint,6,opt,name=active_motion_epoch,json=activeMotionEpoch,proto3" json:"active_motion_epoch,omitempty"` // 当前 motion epoch（陈旧命令据此判废）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ArmState) Reset() {
	*x = ArmState{}
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmState) ProtoMessage() {}

func (x *ArmState) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmState.ProtoReflect.Descriptor instead.
func (*ArmState) Descriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{2}
}

func (x *ArmState) GetReadiness() ArmReadiness {
	if x != nil {
		return x.Readiness
	}
	return ArmReadiness_ARM_READINESS_UNSPECIFIED
}

func (x *ArmState) GetJoints() *JointState {
	if x != nil {
		return x.Joints
	}
	return nil
}

func (x *ArmState) GetTcpPose() *Pose {
	if x != nil {
		return x.TcpPose
	}
	return nil
}

func (x *ArmState) GetJointLowerRad() []float64 {
	if x != nil {
		return x.JointLowerRad
	}
	return nil
}

func (x *ArmState) GetJointUpperRad() []float64 {
	if x != nil {
		return x.JointUpperRad
	}
	return nil
}

func (x *ArmState) GetActiveMotionEpoch() uint64 {
	if x != nil {
		return x.ActiveMotionEpoch
	}
	return 0
}

type GetArmStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArmStateRequest) Reset() {
	*x = GetArmStateRequest{}
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArmStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArmStateRequest) ProtoMessage() {}

func (x *GetArmStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArmStateRequest.ProtoReflect.Descriptor instead.
func (*GetArmStateRequest) Descriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{3}
}

type SubscribeArmStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeArmStateRequest) Reset() {
	*x = SubscribeArmStateRequest{}
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeArmStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeArmStateRequest) ProtoMessage() {}

func (x *SubscribeArmStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeArmStateRequest.ProtoReflect.Descriptor instead.
func (*SubscribeArmStateRequest) Descriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{4}
}

// MoveToPoseRequest —— 末端移到目标位姿。
type MoveToPoseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *Pose                  `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	MaxVelScale   float64                `protobuf:"fixed64,2,opt,name=max_vel_scale,json=maxVelScale,proto3" json:"max_vel_scale,omitempty"` // 速度缩放，取值 0..1；越界 → INVALID_ARGUMENT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToPoseRequest) Reset() {
	*x = MoveToPoseRequest{}
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToPoseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToPoseRequest) ProtoMessage() {}

func (x *MoveToPoseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToPoseRequest.ProtoReflect.Descriptor instead.
func (*MoveToPoseRequest) Descriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{5}
}

func (x *MoveToPoseRequest) GetTarget() *Pose {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *MoveToPoseRequest) GetMaxVelScale() float64 {
	if x != nil {
		return x.MaxVelScale
	}
	return 0
}

// MoveJointTrajectoryPoint —— 关节轨迹上的一个途经点。
type MoveJointTrajectoryPoint struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PositionRad        []float64              `protobuf:"fixed64,1,rep,packed,name=position_rad,json=positionRad,proto3" json:"position_rad,omitempty"`                  // 各关节目标角，rad（索引对齐 ArmState）
	TimeFromStartNanos int64                  `protobuf:"varint,2,opt,name=time_from_start_nanos,json=timeFromStartNanos,proto3" json:"time_from_start_nanos,omitempty"` // 相对轨迹起点的时间，ns，单调递增
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MoveJointTrajectoryPoint) Reset() {
	*x = MoveJointTrajectoryPoint{}
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveJointTrajectoryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveJointTrajectoryPoint) ProtoMessage() {}

func (x *MoveJointTrajectoryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveJointTrajectoryPoint.ProtoReflect.Descriptor instead.
func (*MoveJointTrajectoryPoint) Descriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{6}
}

func (x *MoveJointTrajectoryPoint) GetPositionRad() []float64 {
	if x != nil {
		return x.PositionRad
	}
	return nil
}

func (x *MoveJointTrajectoryPoint) GetTimeFromStartNanos() int64 {
	if x != nil {
		return x.TimeFromStartNanos
	}
	return 0
}

// MoveJointTrajectoryRequest —— 关节空间轨迹。
type MoveJointTrajectoryRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Points        []*MoveJointTrajectoryPoint `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveJointTrajectoryRequest) Reset() {
	*x = MoveJointTrajectoryRequest{}
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveJointTrajectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveJointTrajectoryRequest) ProtoMessage() {}

func (x *MoveJointTrajectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveJointTrajectoryRequest.ProtoReflect.Descriptor instead.
func (*MoveJointTrajectoryRequest) Descriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{7}
}

func (x *MoveJointTrajectoryRequest) GetPoints() []*MoveJointTrajectoryPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type GoHomeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoHomeRequest) Reset() {
	*x = GoHomeRequest{}
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoHomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoHomeRequest) ProtoMessage() {}

func (x *GoHomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoHomeRequest.ProtoReflect.Descriptor instead.
func (*GoHomeRequest) Descriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{8}
}

// SetGripperRequest —— 夹爪开合。
type SetGripperRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opening       float64                `protobuf:"fixed64,1,opt,name=opening,proto3" json:"opening,omitempty"`                      // 0 = 闭合，1 = 全开；越界 → INVALID_ARGUMENT
	MaxEffort     float64                `protobuf:"fixed64,2,opt,name=max_effort,json=maxEffort,proto3" json:"max_effort,omitempty"` // 最大力矩/力限（0 = Provider 默认）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGripperRequest) Reset() {
	*x = SetGripperRequest{}
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGripperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGripperRequest) ProtoMessage() {}

func (x *SetGripperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGripperRequest.ProtoReflect.Descriptor instead.
func (*SetGripperRequest) Descriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{9}
}

func (x *SetGripperRequest) GetOpening() float64 {
	if x != nil {
		return x.Opening
	}
	return 0
}

func (x *SetGripperRequest) GetMaxEffort() float64 {
	if x != nil {
		return x.MaxEffort
	}
	return 0
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{10}
}

// ManipulatorMoveResult —— 移动类 operation 的成功终态载荷（NRCP §11）。
// operation 终态载荷类型由 origin 方法绑定决定（method_meta.response_type）。
type ManipulatorMoveResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinalPose     *Pose                  `protobuf:"bytes,1,opt,name=final_pose,json=finalPose,proto3" json:"final_pose,omitempty"` // 到位后的实际末端位姿
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManipulatorMoveResult) Reset() {
	*x = ManipulatorMoveResult{}
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManipulatorMoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManipulatorMoveResult) ProtoMessage() {}

func (x *ManipulatorMoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManipulatorMoveResult.ProtoReflect.Descriptor instead.
func (*ManipulatorMoveResult) Descriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{11}
}

func (x *ManipulatorMoveResult) GetFinalPose() *Pose {
	if x != nil {
		return x.FinalPose
	}
	return nil
}

type ManipulatorErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        ManipulatorReason      `protobuf:"varint,1,opt,name=reason,proto3,enum=nervus.interface.manipulator.v1.ManipulatorReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManipulatorErrorDetail) Reset() {
	*x = ManipulatorErrorDetail{}
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManipulatorErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManipulatorErrorDetail) ProtoMessage() {}

func (x *ManipulatorErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManipulatorErrorDetail.ProtoReflect.Descriptor instead.
func (*ManipulatorErrorDetail) Descriptor() ([]byte, []int) {
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP(), []int{12}
}

func (x *ManipulatorErrorDetail) GetReason() ManipulatorReason {
	if x != nil {
		return x.Reason
	}
	return ManipulatorReason_MANIPULATOR_REASON_UNSPECIFIED
}

var File_nervus_interface_manipulator_v1_manipulator_proto protoreflect.FileDescriptor

const file_nervus_interface_manipulator_v1_manipulator_proto_rawDesc = "" +
	"\n" +
	"1nervus/interface/manipulator/v1/manipulator.proto\x12\x1fnervus.interface.manipulator.v1\x1a#nervus/ipc/v1/method_registry.proto\"U\n" +
	"\n" +
	"JointState\x12!\n" +
	"\fposition_rad\x18\x01 \x03(\x01R\vpositionRad\x12$\n" +
	"\x0evelocity_rad_s\x18\x02 \x03(\x01R\fvelocityRadS\"\x86\x01\n" +
	"\x04Pose\x12\x14\n" +
	"\x05frame\x18\x01 \x01(\tR\x05frame\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x01R\x01z\x12\x0e\n" +
	"\x02qx\x18\x05 \x01(\x01R\x02qx\x12\x0e\n" +
	"\x02qy\x18\x06 \x01(\x01R\x02qy\x12\x0e\n" +
	"\x02qz\x18\a \x01(\x01R\x02qz\x12\x0e\n" +
	"\x02qw\x18\b \x01(\x01R\x02qw\"\xde\x02\n" +
	"\bArmState\x12K\n" +
	"\treadiness\x18\x01 \x01(\x0e2-.nervus.interface.manipulator.v1.ArmReadinessR\treadiness\x12C\n" +
	"\x06joints\x18\x02 \x01(\v2+.nervus.interface.manipulator.v1.JointStateR\x06joints\x12@\n" +
	"\btcp_pose\x18\x03 \x01(\v2%.nervus.interface.manipulator.v1.PoseR\atcpPose\x12&\n" +
	"\x0fjoint_lower_rad\x18\x04 \x03(\x01R\rjointLowerRad\x12&\n" +
	"\x0fjoint_upper_rad\x18\x05 \x03(\x01R\rjointUpperRad\x12.\n" +
	"\x13active_motion_epoch\x18\x06 \x01(\x04R\x11activeMotionEpoch\"\x14\n" +
	"\x12GetArmStateRequest\"\x1a\n" +
	"\x18SubscribeArmStateRequest\"v\n" +
	"\x11MoveToPoseRequest\x12=\n" +
	"\x06target\x18\x01 \x01(\v2%.nervus.interface.manipulator.v1.PoseR\x06target\x12\"\n" +
	"\rmax_vel_scale\x18\x02 \x01(\x01R\vmaxVelScale\"p\n" +
	"\x18MoveJointTrajectoryPoint\x12!\n" +
	"\fposition_rad\x18\x01 \x03(\x01R\vpositionRad\x121\n" +
	"\x15time_from_start_nanos\x18\x02 \x01(\x03R\x12timeFromStartNanos\"o\n" +
	"\x1aMoveJointTrajectoryRequest\x12Q\n" +
	"\x06points\x18\x01 \x03(\v29.nervus.interface.manipulator.v1.MoveJointTrajectoryPointR\x06points\"\x0f\n" +
	"\rGoHomeRequest\"L\n" +
	"\x11SetGripperRequest\x12\x18\n" +
	"\aopening\x18\x01 \x01(\x01R\aopening\x12\x1d\n" +
	"\n" +
	"max_effort\x18\x02 \x01(\x01R\tmaxEffort\"\r\n" +
	"\vStopRequest\"]\n" +
	"\x15ManipulatorMoveResult\x12D\n" +
	"\n" +
	"final_pose\x18\x01 \x01(\v2%.nervus.interface.manipulator.v1.PoseR\tfinalPose\"d\n" +
	"\x16ManipulatorErrorDetail\x12J\n" +
	"\x06reason\x18\x01 \x01(\x0e22.nervus.interface.manipulator.v1.ManipulatorReasonR\x06reason*\x8b\t\n" +
	"\x11ManipulatorMethod\x12\"\n" +
	"\x1eMANIPULATOR_METHOD_UNSPECIFIED\x10\x00\x12\x8c\x01\n" +
	" MANIPULATOR_METHOD_GET_ARM_STATE\x10\x01\x1af\x8a\xa6\x1db\b\x01\x18\x01:2nervus.interface.manipulator.v1.GetArmStateRequestB(nervus.interface.manipulator.v1.ArmState\x12\x98\x01\n" +
	"&MANIPULATOR_METHOD_SUBSCRIBE_ARM_STATE\x10\x02\x1al\x8a\xa6\x1dh\b\x02\x18\x01:8nervus.interface.manipulator.v1.SubscribeArmStateRequestB(nervus.interface.manipulator.v1.ArmState\x12\xb9\x01\n" +
	"\x1fMANIPULATOR_METHOD_MOVE_TO_POSE\x10\x03\x1a\x93\x01\x8a\xa6\x1d\x8e\x01\b\x03\x12\x18perm.manipulator.control\x18\x03 \x01(\x010\x01:1nervus.interface.manipulator.v1.MoveToPoseRequestB5nervus.interface.manipulator.v1.ManipulatorMoveResult\x12\xcb\x01\n" +
	"(MANIPULATOR_METHOD_MOVE_JOINT_TRAJECTORY\x10\x04\x1a\x9c\x01\x8a\xa6\x1d\x97\x01\b\x04\x12\x18perm.manipulator.control\x18\x03 \x01(\x010\x01::nervus.interface.manipulator.v1.MoveJointTrajectoryRequestB5nervus.interface.manipulator.v1.ManipulatorMoveResult\x12\xb0\x01\n" +
	"\x1aMANIPULATOR_METHOD_GO_HOME\x10\x05\x1a\x8f\x01\x8a\xa6\x1d\x8a\x01\b\x05\x12\x18perm.manipulator.control\x18\x03 \x01(\x010\x01:-nervus.interface.manipulator.v1.GoHomeRequestB5nervus.interface.manipulator.v1.ManipulatorMoveResult\x12{\n" +
	"\x1eMANIPULATOR_METHOD_SET_GRIPPER\x10\x06\x1aW\x8a\xa6\x1dS\b\x06\x12\x18perm.manipulator.control\x18\x03 \x01:1nervus.interface.manipulator.v1.SetGripperRequest\x12n\n" +
	"\x17MANIPULATOR_METHOD_STOP\x10\a\x1aQ\x8a\xa6\x1dM\b\a\x12\x18perm.manipulator.control\x18\x03 \x01:+nervus.interface.manipulator.v1.StopRequest*\x9d\x01\n" +
	"\fArmReadiness\x12\x1d\n" +
	"\x19ARM_READINESS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ARM_READINESS_READY\x10\x01\x12\x1b\n" +
	"\x17ARM_READINESS_NOT_READY\x10\x02\x12\x1f\n" +
	"\x1bARM_READINESS_TRANSITIONING\x10\x03\x12\x17\n" +
	"\x13ARM_READINESS_FAULT\x10\x04*\x90\x03\n" +
	"\x11ManipulatorReason\x12\"\n" +
	"\x1eMANIPULATOR_REASON_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cMANIPULATOR_REASON_NOT_READY\x10\x01\x12%\n" +
	"!MANIPULATOR_REASON_SAFETY_LATCHED\x10\x02\x12\"\n" +
	"\x1eMANIPULATOR_REASON_STALE_EPOCH\x10\x03\x12'\n" +
	"#MANIPULATOR_REASON_CONTROL_NOT_HELD\x10\x04\x12\"\n" +
	"\x1eMANIPULATOR_REASON_JOINT_LIMIT\x10\x05\x12'\n" +
	"#MANIPULATOR_REASON_UNREACHABLE_POSE\x10\x06\x12 \n" +
	"\x1cMANIPULATOR_REASON_COLLISION\x10\a\x12+\n" +
	"'MANIPULATOR_REASON_RESOURCE_UNAVAILABLE\x10\b\x12%\n" +
	"!MANIPULATOR_REASON_RESOURCE_FAULT\x10\tB\x90\x01\n" +
	"'io.github.nervusos.iface.manipulator.v1B\x10ManipulatorProtoP\x01ZQgithub.com/nervus-os/nervus-ipc/go/protocol/interface/manipulatorv1;manipulatorv1b\x06proto3"

var (
	file_nervus_interface_manipulator_v1_manipulator_proto_rawDescOnce sync.Once
	file_nervus_interface_manipulator_v1_manipulator_proto_rawDescData []byte
)

func file_nervus_interface_manipulator_v1_manipulator_proto_rawDescGZIP() []byte {
	file_nervus_interface_manipulator_v1_manipulator_proto_rawDescOnce.Do(func() {
		file_nervus_interface_manipulator_v1_manipulator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nervus_interface_manipulator_v1_manipulator_proto_rawDesc), len(file_nervus_interface_manipulator_v1_manipulator_proto_rawDesc)))
	})
	return file_nervus_interface_manipulator_v1_manipulator_proto_rawDescData
}

var file_nervus_interface_manipulator_v1_manipulator_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_nervus_interface_manipulator_v1_manipulator_proto_goTypes = []any{
	(ManipulatorMethod)(0),             // 0: nervus.interface.manipulator.v1.ManipulatorMethod
	(ArmReadiness)(0),                  // 1: nervus.interface.manipulator.v1.ArmReadiness
	(ManipulatorReason)(0),             // 2: nervus.interface.manipulator.v1.ManipulatorReason
	(*JointState)(nil),                 // 3: nervus.interface.manipulator.v1.JointState
	(*Pose)(nil),                       // 4: nervus.interface.manipulator.v1.Pose
	(*ArmState)(nil),                   // 5: nervus.interface.manipulator.v1.ArmState
	(*GetArmStateRequest)(nil),         // 6: nervus.interface.manipulator.v1.GetArmStateRequest
	(*SubscribeArmStateRequest)(nil),   // 7: nervus.interface.manipulator.v1.SubscribeArmStateRequest
	(*MoveToPoseRequest)(nil),          // 8: nervus.interface.manipulator.v1.MoveToPoseRequest
	(*MoveJointTrajectoryPoint)(nil),   // 9: nervus.interface.manipulator.v1.MoveJointTrajectoryPoint
	(*MoveJointTrajectoryRequest)(nil), // 10: nervus.interface.manipulator.v1.MoveJointTrajectoryRequest
	(*GoHomeRequest)(nil),              // 11: nervus.interface.manipulator.v1.GoHomeRequest
	(*SetGripperRequest)(nil),          // 12: nervus.interface.manipulator.v1.SetGripperRequest
	(*StopRequest)(nil),                // 13: nervus.interface.manipulator.v1.StopRequest
	(*ManipulatorMoveResult)(nil),      // 14: nervus.interface.manipulator.v1.ManipulatorMoveResult
	(*ManipulatorErrorDetail)(nil),     // 15: nervus.interface.manipulator.v1.ManipulatorErrorDetail
}
var file_nervus_interface_manipulator_v1_manipulator_proto_depIdxs = []int32{
	1, // 0: nervus.interface.manipulator.v1.ArmState.readiness:type_name -> nervus.interface.manipulator.v1.ArmReadiness
	3, // 1: nervus.interface.manipulator.v1.ArmState.joints:type_name -> nervus.interface.manipulator.v1.JointState
	4, // 2: nervus.interface.manipulator.v1.ArmState.tcp_pose:type_name -> nervus.interface.manipulator.v1.Pose
	4, // 3: nervus.interface.manipulator.v1.MoveToPoseRequest.target:type_name -> nervus.interface.manipulator.v1.Pose
	9, // 4: nervus.interface.manipulator.v1.MoveJointTrajectoryRequest.points:type_name -> nervus.interface.manipulator.v1.MoveJointTrajectoryPoint
	4, // 5: nervus.interface.manipulator.v1.ManipulatorMoveResult.final_pose:type_name -> nervus.interface.manipulator.v1.Pose
	2, // 6: nervus.interface.manipulator.v1.ManipulatorErrorDetail.reason:type_name -> nervus.interface.manipulator.v1.ManipulatorReason
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_nervus_interface_manipulator_v1_manipulator_proto_init() }
func file_nervus_interface_manipulator_v1_manipulator_proto_init() {
	if File_nervus_interface_manipulator_v1_manipulator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nervus_interface_manipulator_v1_manipulator_proto_rawDesc), len(file_nervus_interface_manipulator_v1_manipulator_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nervus_interface_manipulator_v1_manipulator_proto_goTypes,
		DependencyIndexes: file_nervus_interface_manipulator_v1_manipulator_proto_depIdxs,
		EnumInfos:         file_nervus_interface_manipulator_v1_manipulator_proto_enumTypes,
		MessageInfos:      file_nervus_interface_manipulator_v1_manipulator_proto_msgTypes,
	}.Build()
	File_nervus_interface_manipulator_v1_manipulator_proto = out.File
	file_nervus_interface_manipulator_v1_manipulator_proto_goTypes = nil
	file_nervus_interface_manipulator_v1_manipulator_proto_depIdxs = nil
}
