// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: acme/dog/rawgait/v1/rawgait.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.acme.dog.rawgait.v1;

@kotlin.jvm.JvmName("-initializeexecuteRawGaitResult")
public inline fun executeRawGaitResult(block: com.acme.dog.rawgait.v1.ExecuteRawGaitResultKt.Dsl.() -> kotlin.Unit): com.acme.dog.rawgait.v1.ExecuteRawGaitResult =
  com.acme.dog.rawgait.v1.ExecuteRawGaitResultKt.Dsl._create(com.acme.dog.rawgait.v1.ExecuteRawGaitResult.newBuilder()).apply { block() }._build()
/**
 * ```
 * ExecuteRawGaitResult —— operation 成功终态载荷。
 * ```
 *
 * Protobuf type `acme.dog.rawgait.v1.ExecuteRawGaitResult`
 */
public object ExecuteRawGaitResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.acme.dog.rawgait.v1.ExecuteRawGaitResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.acme.dog.rawgait.v1.ExecuteRawGaitResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.acme.dog.rawgait.v1.ExecuteRawGaitResult = _builder.build()

    /**
     * `int64 frames_executed = 1 [json_name = "framesExecuted"];`
     */
    public var framesExecuted: kotlin.Long
      @JvmName("getFramesExecuted")
      get() = _builder.framesExecuted
      @JvmName("setFramesExecuted")
      set(value) {
        _builder.framesExecuted = value
      }
    /**
     * `int64 frames_executed = 1 [json_name = "framesExecuted"];`
     */
    public fun clearFramesExecuted() {
      _builder.clearFramesExecuted()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.acme.dog.rawgait.v1.ExecuteRawGaitResult.copy(block: `com.acme.dog.rawgait.v1`.ExecuteRawGaitResultKt.Dsl.() -> kotlin.Unit): com.acme.dog.rawgait.v1.ExecuteRawGaitResult =
  `com.acme.dog.rawgait.v1`.ExecuteRawGaitResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

