// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/permission/v1/permission.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.iface.permission.v1;

/**
 * <pre>
 * PackageGrants —— 一个包及其全部可授予权限。
 * </pre>
 *
 * Protobuf type {@code nervus.interface.permission.v1.PackageGrants}
 */
public final class PackageGrants extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:nervus.interface.permission.v1.PackageGrants)
    PackageGrantsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PackageGrants.class.getName());
  }
  // Use PackageGrants.newBuilder() to construct.
  private PackageGrants(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PackageGrants() {
    packageId_ = "";
    label_ = "";
    permissions_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.nervusos.iface.permission.v1.PermissionAdminProto.internal_static_nervus_interface_permission_v1_PackageGrants_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.nervusos.iface.permission.v1.PermissionAdminProto.internal_static_nervus_interface_permission_v1_PackageGrants_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.nervusos.iface.permission.v1.PackageGrants.class, io.github.nervusos.iface.permission.v1.PackageGrants.Builder.class);
  }

  public static final int PACKAGE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object packageId_ = "";
  /**
   * <code>string package_id = 1;</code>
   * @return The packageId.
   */
  @java.lang.Override
  public java.lang.String getPackageId() {
    java.lang.Object ref = packageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packageId_ = s;
      return s;
    }
  }
  /**
   * <code>string package_id = 1;</code>
   * @return The bytes for packageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackageIdBytes() {
    java.lang.Object ref = packageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LABEL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object label_ = "";
  /**
   * <pre>
   * 包的显示名，来自 manifest 的 label。空则由界面回落到 package_id。
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      label_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 包的显示名，来自 manifest 的 label。空则由界面回落到 package_id。
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      label_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERMISSIONS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<io.github.nervusos.iface.permission.v1.PermissionGrant> permissions_;
  /**
   * <pre>
   * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
   * </pre>
   *
   * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<io.github.nervusos.iface.permission.v1.PermissionGrant> getPermissionsList() {
    return permissions_;
  }
  /**
   * <pre>
   * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
   * </pre>
   *
   * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.github.nervusos.iface.permission.v1.PermissionGrantOrBuilder> 
      getPermissionsOrBuilderList() {
    return permissions_;
  }
  /**
   * <pre>
   * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
   * </pre>
   *
   * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
   */
  @java.lang.Override
  public int getPermissionsCount() {
    return permissions_.size();
  }
  /**
   * <pre>
   * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
   * </pre>
   *
   * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
   */
  @java.lang.Override
  public io.github.nervusos.iface.permission.v1.PermissionGrant getPermissions(int index) {
    return permissions_.get(index);
  }
  /**
   * <pre>
   * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
   * </pre>
   *
   * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
   */
  @java.lang.Override
  public io.github.nervusos.iface.permission.v1.PermissionGrantOrBuilder getPermissionsOrBuilder(
      int index) {
    return permissions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(packageId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, packageId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(label_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, label_);
    }
    for (int i = 0; i < permissions_.size(); i++) {
      output.writeMessage(3, permissions_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(packageId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, packageId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(label_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, label_);
    }
    for (int i = 0; i < permissions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, permissions_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.nervusos.iface.permission.v1.PackageGrants)) {
      return super.equals(obj);
    }
    io.github.nervusos.iface.permission.v1.PackageGrants other = (io.github.nervusos.iface.permission.v1.PackageGrants) obj;

    if (!getPackageId()
        .equals(other.getPackageId())) return false;
    if (!getLabel()
        .equals(other.getLabel())) return false;
    if (!getPermissionsList()
        .equals(other.getPermissionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PACKAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPackageId().hashCode();
    hash = (37 * hash) + LABEL_FIELD_NUMBER;
    hash = (53 * hash) + getLabel().hashCode();
    if (getPermissionsCount() > 0) {
      hash = (37 * hash) + PERMISSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getPermissionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.nervusos.iface.permission.v1.PackageGrants parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.iface.permission.v1.PackageGrants parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.iface.permission.v1.PackageGrants parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.iface.permission.v1.PackageGrants parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.iface.permission.v1.PackageGrants parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.iface.permission.v1.PackageGrants parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.iface.permission.v1.PackageGrants parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.nervusos.iface.permission.v1.PackageGrants parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.nervusos.iface.permission.v1.PackageGrants parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.nervusos.iface.permission.v1.PackageGrants parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.nervusos.iface.permission.v1.PackageGrants parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.nervusos.iface.permission.v1.PackageGrants parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.nervusos.iface.permission.v1.PackageGrants prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * PackageGrants —— 一个包及其全部可授予权限。
   * </pre>
   *
   * Protobuf type {@code nervus.interface.permission.v1.PackageGrants}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nervus.interface.permission.v1.PackageGrants)
      io.github.nervusos.iface.permission.v1.PackageGrantsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.nervusos.iface.permission.v1.PermissionAdminProto.internal_static_nervus_interface_permission_v1_PackageGrants_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.nervusos.iface.permission.v1.PermissionAdminProto.internal_static_nervus_interface_permission_v1_PackageGrants_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.nervusos.iface.permission.v1.PackageGrants.class, io.github.nervusos.iface.permission.v1.PackageGrants.Builder.class);
    }

    // Construct using io.github.nervusos.iface.permission.v1.PackageGrants.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      packageId_ = "";
      label_ = "";
      if (permissionsBuilder_ == null) {
        permissions_ = java.util.Collections.emptyList();
      } else {
        permissions_ = null;
        permissionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.nervusos.iface.permission.v1.PermissionAdminProto.internal_static_nervus_interface_permission_v1_PackageGrants_descriptor;
    }

    @java.lang.Override
    public io.github.nervusos.iface.permission.v1.PackageGrants getDefaultInstanceForType() {
      return io.github.nervusos.iface.permission.v1.PackageGrants.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.nervusos.iface.permission.v1.PackageGrants build() {
      io.github.nervusos.iface.permission.v1.PackageGrants result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.nervusos.iface.permission.v1.PackageGrants buildPartial() {
      io.github.nervusos.iface.permission.v1.PackageGrants result = new io.github.nervusos.iface.permission.v1.PackageGrants(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.github.nervusos.iface.permission.v1.PackageGrants result) {
      if (permissionsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          permissions_ = java.util.Collections.unmodifiableList(permissions_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.permissions_ = permissions_;
      } else {
        result.permissions_ = permissionsBuilder_.build();
      }
    }

    private void buildPartial0(io.github.nervusos.iface.permission.v1.PackageGrants result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.packageId_ = packageId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.label_ = label_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.nervusos.iface.permission.v1.PackageGrants) {
        return mergeFrom((io.github.nervusos.iface.permission.v1.PackageGrants)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.nervusos.iface.permission.v1.PackageGrants other) {
      if (other == io.github.nervusos.iface.permission.v1.PackageGrants.getDefaultInstance()) return this;
      if (!other.getPackageId().isEmpty()) {
        packageId_ = other.packageId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getLabel().isEmpty()) {
        label_ = other.label_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (permissionsBuilder_ == null) {
        if (!other.permissions_.isEmpty()) {
          if (permissions_.isEmpty()) {
            permissions_ = other.permissions_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePermissionsIsMutable();
            permissions_.addAll(other.permissions_);
          }
          onChanged();
        }
      } else {
        if (!other.permissions_.isEmpty()) {
          if (permissionsBuilder_.isEmpty()) {
            permissionsBuilder_.dispose();
            permissionsBuilder_ = null;
            permissions_ = other.permissions_;
            bitField0_ = (bitField0_ & ~0x00000004);
            permissionsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPermissionsFieldBuilder() : null;
          } else {
            permissionsBuilder_.addAllMessages(other.permissions_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              packageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              label_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              io.github.nervusos.iface.permission.v1.PermissionGrant m =
                  input.readMessage(
                      io.github.nervusos.iface.permission.v1.PermissionGrant.parser(),
                      extensionRegistry);
              if (permissionsBuilder_ == null) {
                ensurePermissionsIsMutable();
                permissions_.add(m);
              } else {
                permissionsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object packageId_ = "";
    /**
     * <code>string package_id = 1;</code>
     * @return The packageId.
     */
    public java.lang.String getPackageId() {
      java.lang.Object ref = packageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string package_id = 1;</code>
     * @return The bytes for packageId.
     */
    public com.google.protobuf.ByteString
        getPackageIdBytes() {
      java.lang.Object ref = packageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string package_id = 1;</code>
     * @param value The packageId to set.
     * @return This builder for chaining.
     */
    public Builder setPackageId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      packageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string package_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageId() {
      packageId_ = getDefaultInstance().getPackageId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string package_id = 1;</code>
     * @param value The bytes for packageId to set.
     * @return This builder for chaining.
     */
    public Builder setPackageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      packageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object label_ = "";
    /**
     * <pre>
     * 包的显示名，来自 manifest 的 label。空则由界面回落到 package_id。
     * </pre>
     *
     * <code>string label = 2;</code>
     * @return The label.
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 包的显示名，来自 manifest 的 label。空则由界面回落到 package_id。
     * </pre>
     *
     * <code>string label = 2;</code>
     * @return The bytes for label.
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 包的显示名，来自 manifest 的 label。空则由界面回落到 package_id。
     * </pre>
     *
     * <code>string label = 2;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      label_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 包的显示名，来自 manifest 的 label。空则由界面回落到 package_id。
     * </pre>
     *
     * <code>string label = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      label_ = getDefaultInstance().getLabel();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 包的显示名，来自 manifest 的 label。空则由界面回落到 package_id。
     * </pre>
     *
     * <code>string label = 2;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      label_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<io.github.nervusos.iface.permission.v1.PermissionGrant> permissions_ =
      java.util.Collections.emptyList();
    private void ensurePermissionsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        permissions_ = new java.util.ArrayList<io.github.nervusos.iface.permission.v1.PermissionGrant>(permissions_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.github.nervusos.iface.permission.v1.PermissionGrant, io.github.nervusos.iface.permission.v1.PermissionGrant.Builder, io.github.nervusos.iface.permission.v1.PermissionGrantOrBuilder> permissionsBuilder_;

    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public java.util.List<io.github.nervusos.iface.permission.v1.PermissionGrant> getPermissionsList() {
      if (permissionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(permissions_);
      } else {
        return permissionsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public int getPermissionsCount() {
      if (permissionsBuilder_ == null) {
        return permissions_.size();
      } else {
        return permissionsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public io.github.nervusos.iface.permission.v1.PermissionGrant getPermissions(int index) {
      if (permissionsBuilder_ == null) {
        return permissions_.get(index);
      } else {
        return permissionsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public Builder setPermissions(
        int index, io.github.nervusos.iface.permission.v1.PermissionGrant value) {
      if (permissionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePermissionsIsMutable();
        permissions_.set(index, value);
        onChanged();
      } else {
        permissionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public Builder setPermissions(
        int index, io.github.nervusos.iface.permission.v1.PermissionGrant.Builder builderForValue) {
      if (permissionsBuilder_ == null) {
        ensurePermissionsIsMutable();
        permissions_.set(index, builderForValue.build());
        onChanged();
      } else {
        permissionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public Builder addPermissions(io.github.nervusos.iface.permission.v1.PermissionGrant value) {
      if (permissionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePermissionsIsMutable();
        permissions_.add(value);
        onChanged();
      } else {
        permissionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public Builder addPermissions(
        int index, io.github.nervusos.iface.permission.v1.PermissionGrant value) {
      if (permissionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePermissionsIsMutable();
        permissions_.add(index, value);
        onChanged();
      } else {
        permissionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public Builder addPermissions(
        io.github.nervusos.iface.permission.v1.PermissionGrant.Builder builderForValue) {
      if (permissionsBuilder_ == null) {
        ensurePermissionsIsMutable();
        permissions_.add(builderForValue.build());
        onChanged();
      } else {
        permissionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public Builder addPermissions(
        int index, io.github.nervusos.iface.permission.v1.PermissionGrant.Builder builderForValue) {
      if (permissionsBuilder_ == null) {
        ensurePermissionsIsMutable();
        permissions_.add(index, builderForValue.build());
        onChanged();
      } else {
        permissionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public Builder addAllPermissions(
        java.lang.Iterable<? extends io.github.nervusos.iface.permission.v1.PermissionGrant> values) {
      if (permissionsBuilder_ == null) {
        ensurePermissionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, permissions_);
        onChanged();
      } else {
        permissionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public Builder clearPermissions() {
      if (permissionsBuilder_ == null) {
        permissions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        permissionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public Builder removePermissions(int index) {
      if (permissionsBuilder_ == null) {
        ensurePermissionsIsMutable();
        permissions_.remove(index);
        onChanged();
      } else {
        permissionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public io.github.nervusos.iface.permission.v1.PermissionGrant.Builder getPermissionsBuilder(
        int index) {
      return getPermissionsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public io.github.nervusos.iface.permission.v1.PermissionGrantOrBuilder getPermissionsOrBuilder(
        int index) {
      if (permissionsBuilder_ == null) {
        return permissions_.get(index);  } else {
        return permissionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public java.util.List<? extends io.github.nervusos.iface.permission.v1.PermissionGrantOrBuilder> 
         getPermissionsOrBuilderList() {
      if (permissionsBuilder_ != null) {
        return permissionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(permissions_);
      }
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public io.github.nervusos.iface.permission.v1.PermissionGrant.Builder addPermissionsBuilder() {
      return getPermissionsFieldBuilder().addBuilder(
          io.github.nervusos.iface.permission.v1.PermissionGrant.getDefaultInstance());
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public io.github.nervusos.iface.permission.v1.PermissionGrant.Builder addPermissionsBuilder(
        int index) {
      return getPermissionsFieldBuilder().addBuilder(
          index, io.github.nervusos.iface.permission.v1.PermissionGrant.getDefaultInstance());
    }
    /**
     * <pre>
     * 按 permission_id 字典序排列。顺序确定，否则设置页里的开关每次刷新都在跳。
     * </pre>
     *
     * <code>repeated .nervus.interface.permission.v1.PermissionGrant permissions = 3;</code>
     */
    public java.util.List<io.github.nervusos.iface.permission.v1.PermissionGrant.Builder> 
         getPermissionsBuilderList() {
      return getPermissionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.github.nervusos.iface.permission.v1.PermissionGrant, io.github.nervusos.iface.permission.v1.PermissionGrant.Builder, io.github.nervusos.iface.permission.v1.PermissionGrantOrBuilder> 
        getPermissionsFieldBuilder() {
      if (permissionsBuilder_ == null) {
        permissionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.github.nervusos.iface.permission.v1.PermissionGrant, io.github.nervusos.iface.permission.v1.PermissionGrant.Builder, io.github.nervusos.iface.permission.v1.PermissionGrantOrBuilder>(
                permissions_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        permissions_ = null;
      }
      return permissionsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:nervus.interface.permission.v1.PackageGrants)
  }

  // @@protoc_insertion_point(class_scope:nervus.interface.permission.v1.PackageGrants)
  private static final io.github.nervusos.iface.permission.v1.PackageGrants DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.nervusos.iface.permission.v1.PackageGrants();
  }

  public static io.github.nervusos.iface.permission.v1.PackageGrants getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PackageGrants>
      PARSER = new com.google.protobuf.AbstractParser<PackageGrants>() {
    @java.lang.Override
    public PackageGrants parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PackageGrants> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PackageGrants> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.nervusos.iface.permission.v1.PackageGrants getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

