// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/permission/v1/permission_ui.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.iface.permission.v1;

/**
 * Protobuf enum {@code nervus.interface.permission.v1.PermissionUiMethod}
 */
public enum PermissionUiMethod
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PERMISSION_UI_METHOD_UNSPECIFIED = 0;</code>
   */
  PERMISSION_UI_METHOD_UNSPECIFIED(0),
  /**
   * <pre>
   * 展示安装确认，用户接受则安装。
   *
   * 【长任务】：它内含一次 pkgmanager 的 INSTALL（本身就是 operation），前面
   * 还要等用户读完权限清单再点。人的反应时间不属于任何 deadline 预算，因此
   * returns_operation = true，以 ACCEPTED + operation_id 应答。
   *
   * needs_user_confirmation = false 而不是 true：【本方法就是那个确认框】。
   * 置 true 会要求 nervud 在放行之前再要一次确认，而那次确认还得由同一个组件
   * 显示——一个自己确认自己的环。真正的门在 INSTALL 那一侧，本方法穿过它。
   *
   * risk_class 取 CRITICAL_SAFETY，与 pkgmanager 的 INSTALL 一致：往系统里
   * 引入新的可执行代码，后果的持久性远超一次运动指令。
   * </pre>
   *
   * <code>PERMISSION_UI_METHOD_CONFIRM_INSTALL = 1 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  PERMISSION_UI_METHOD_CONFIRM_INSTALL(1),
  /**
   * <pre>
   * 打开权限管理界面（某个包的，或全部包的）。
   *
   * 纯 UI 导航，不改任何状态：真正的授予变更由 permissionui 自己经
   * permission.admin 完成，调用方无从干预，也拿不到结果。因此 is_read_only。
   *
   * 存在的理由是设置应用需要一个「管理此应用权限」的入口，而权限界面不能塞进
   * 设置——它要 platform-release 签名才够得着 perm.permission.admin，
   * 而系统软件仓库统一签 platform-systemapp（permissionui 是唯一例外）。
   * </pre>
   *
   * <code>PERMISSION_UI_METHOD_OPEN_MANAGER = 2 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  PERMISSION_UI_METHOD_OPEN_MANAGER(2),
  /**
   * <pre>
   * 向用户申请一批 USER_CONSENT 权限（调用方自己的）。
   *
   * 对应 Android 的 `requestPermissions`。配合 `permission.self` 的 Check 使用：
   * 应用在调用需要敏感权限的方法【之前】先自查，没有再申请，有了直接调。
   *
   * # 为什么 required_permission 是空的
   *
   * 【申请自己的权限不是一种特权】。任何应用都必须能开口问——这条路是它唯一
   * 的自救手段：USER_CONSENT 权限的运行期状态默认 NOT_REQUESTED，装完之后
   * 若用户在权限管理里关掉了某条，应用就再也拿不回来，除非它能申请。
   *
   * 门是别处的，不在这里：
   *
   * 谁的权限     恒为调用方自己（由 nervud 的 caller 决定，请求里没有
   * package_id 字段），因此无从替别人申请
   * 哪些能申请   只有本包在 manifest 里申请过、且安装期裁决批了、且是
   * USER_CONSENT 那一档的才可能成功；其余由 permissionui 与
   * nervud 一律拒（SetGrantState 自带那两道前置校验）
   * 给不给       用户决定。应用发起申请只能让弹窗出现，不能让它自己点确定
   *
   * 也就是说无门槛放行的仅仅是「弹一次窗问用户」这个动作本身。给它加一条权限
   * 反而会造出一个环：那条权限如果也要用户同意，应用就得先有权限才能申请权限。
   *
   * # 为什么是长任务
   *
   * 它要等用户读完说明再点，而人的反应时间不属于任何 deadline 预算。与
   * ConfirmInstall 同一理由。
   *
   * needs_user_confirmation = false：【本方法就是那个确认框】。置 true 会要求
   * nervud 在放行之前再要一次确认，而那次确认还得由同一个组件显示——一个自己
   * 确认自己的环。
   * </pre>
   *
   * <code>PERMISSION_UI_METHOD_REQUEST_PERMISSION = 3 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  PERMISSION_UI_METHOD_REQUEST_PERMISSION(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PermissionUiMethod.class.getName());
  }
  /**
   * <code>PERMISSION_UI_METHOD_UNSPECIFIED = 0;</code>
   */
  public static final int PERMISSION_UI_METHOD_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * 展示安装确认，用户接受则安装。
   *
   * 【长任务】：它内含一次 pkgmanager 的 INSTALL（本身就是 operation），前面
   * 还要等用户读完权限清单再点。人的反应时间不属于任何 deadline 预算，因此
   * returns_operation = true，以 ACCEPTED + operation_id 应答。
   *
   * needs_user_confirmation = false 而不是 true：【本方法就是那个确认框】。
   * 置 true 会要求 nervud 在放行之前再要一次确认，而那次确认还得由同一个组件
   * 显示——一个自己确认自己的环。真正的门在 INSTALL 那一侧，本方法穿过它。
   *
   * risk_class 取 CRITICAL_SAFETY，与 pkgmanager 的 INSTALL 一致：往系统里
   * 引入新的可执行代码，后果的持久性远超一次运动指令。
   * </pre>
   *
   * <code>PERMISSION_UI_METHOD_CONFIRM_INSTALL = 1 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  public static final int PERMISSION_UI_METHOD_CONFIRM_INSTALL_VALUE = 1;
  /**
   * <pre>
   * 打开权限管理界面（某个包的，或全部包的）。
   *
   * 纯 UI 导航，不改任何状态：真正的授予变更由 permissionui 自己经
   * permission.admin 完成，调用方无从干预，也拿不到结果。因此 is_read_only。
   *
   * 存在的理由是设置应用需要一个「管理此应用权限」的入口，而权限界面不能塞进
   * 设置——它要 platform-release 签名才够得着 perm.permission.admin，
   * 而系统软件仓库统一签 platform-systemapp（permissionui 是唯一例外）。
   * </pre>
   *
   * <code>PERMISSION_UI_METHOD_OPEN_MANAGER = 2 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  public static final int PERMISSION_UI_METHOD_OPEN_MANAGER_VALUE = 2;
  /**
   * <pre>
   * 向用户申请一批 USER_CONSENT 权限（调用方自己的）。
   *
   * 对应 Android 的 `requestPermissions`。配合 `permission.self` 的 Check 使用：
   * 应用在调用需要敏感权限的方法【之前】先自查，没有再申请，有了直接调。
   *
   * # 为什么 required_permission 是空的
   *
   * 【申请自己的权限不是一种特权】。任何应用都必须能开口问——这条路是它唯一
   * 的自救手段：USER_CONSENT 权限的运行期状态默认 NOT_REQUESTED，装完之后
   * 若用户在权限管理里关掉了某条，应用就再也拿不回来，除非它能申请。
   *
   * 门是别处的，不在这里：
   *
   * 谁的权限     恒为调用方自己（由 nervud 的 caller 决定，请求里没有
   * package_id 字段），因此无从替别人申请
   * 哪些能申请   只有本包在 manifest 里申请过、且安装期裁决批了、且是
   * USER_CONSENT 那一档的才可能成功；其余由 permissionui 与
   * nervud 一律拒（SetGrantState 自带那两道前置校验）
   * 给不给       用户决定。应用发起申请只能让弹窗出现，不能让它自己点确定
   *
   * 也就是说无门槛放行的仅仅是「弹一次窗问用户」这个动作本身。给它加一条权限
   * 反而会造出一个环：那条权限如果也要用户同意，应用就得先有权限才能申请权限。
   *
   * # 为什么是长任务
   *
   * 它要等用户读完说明再点，而人的反应时间不属于任何 deadline 预算。与
   * ConfirmInstall 同一理由。
   *
   * needs_user_confirmation = false：【本方法就是那个确认框】。置 true 会要求
   * nervud 在放行之前再要一次确认，而那次确认还得由同一个组件显示——一个自己
   * 确认自己的环。
   * </pre>
   *
   * <code>PERMISSION_UI_METHOD_REQUEST_PERMISSION = 3 [(.nervus.ipc.v1.method_meta) = { ... }</code>
   */
  public static final int PERMISSION_UI_METHOD_REQUEST_PERMISSION_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PermissionUiMethod valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PermissionUiMethod forNumber(int value) {
    switch (value) {
      case 0: return PERMISSION_UI_METHOD_UNSPECIFIED;
      case 1: return PERMISSION_UI_METHOD_CONFIRM_INSTALL;
      case 2: return PERMISSION_UI_METHOD_OPEN_MANAGER;
      case 3: return PERMISSION_UI_METHOD_REQUEST_PERMISSION;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PermissionUiMethod>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PermissionUiMethod> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PermissionUiMethod>() {
          public PermissionUiMethod findValueByNumber(int number) {
            return PermissionUiMethod.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.github.nervusos.iface.permission.v1.PermissionUiProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final PermissionUiMethod[] VALUES = values();

  public static PermissionUiMethod valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PermissionUiMethod(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:nervus.interface.permission.v1.PermissionUiMethod)
}

