// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/permission/v1/permission_self.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.iface.permission.v1;

public final class PermissionSelfProto {
  private PermissionSelfProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PermissionSelfProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_interface_permission_v1_CheckSelfPermissionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_interface_permission_v1_CheckSelfPermissionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_interface_permission_v1_CheckSelfPermissionResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_interface_permission_v1_CheckSelfPermissionResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_interface_permission_v1_SelfPermissionState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_interface_permission_v1_SelfPermissionState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4nervus/interface/permission/v1/permiss" +
      "ion_self.proto\022\036nervus.interface.permiss" +
      "ion.v1\032#nervus/ipc/v1/method_registry.pr" +
      "oto\032/nervus/interface/permission/v1/perm" +
      "ission.proto\"C\n\032CheckSelfPermissionReque" +
      "st\022%\n\016permission_ids\030\001 \003(\tR\rpermissionId" +
      "s\"h\n\031CheckSelfPermissionResult\022K\n\006states" +
      "\030\001 \003(\01323.nervus.interface.permission.v1." +
      "SelfPermissionStateR\006states\"\270\001\n\023SelfPerm" +
      "issionState\022#\n\rpermission_id\030\001 \001(\tR\014perm" +
      "issionId\022\030\n\007granted\030\002 \001(\010R\007granted\022@\n\005st" +
      "ate\030\003 \001(\0162*.nervus.interface.permission." +
      "v1.GrantStateR\005state\022 \n\013requestable\030\004 \001(" +
      "\010R\013requestable*\342\001\n\024PermissionSelfMethod\022" +
      "&\n\"PERMISSION_SELF_METHOD_UNSPECIFIED\020\000\022" +
      "\241\001\n\034PERMISSION_SELF_METHOD_CHECK\020\001\032\177\212\246\035{" +
      "\010\001\030\001:9nervus.interface.permission.v1.Che" +
      "ckSelfPermissionRequestB8nervus.interfac" +
      "e.permission.v1.CheckSelfPermissionResul" +
      "tH\001B\215\001\n&io.github.nervusos.iface.permiss" +
      "ion.v1B\023PermissionSelfProtoP\001ZLgithub.co" +
      "m/nervus-os/nervus-ipc/protocol/interfac" +
      "e/permissionv1;permissionv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.github.nervusos.ipc.v1.MethodRegistryProto.getDescriptor(),
          io.github.nervusos.iface.permission.v1.PermissionAdminProto.getDescriptor(),
        });
    internal_static_nervus_interface_permission_v1_CheckSelfPermissionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nervus_interface_permission_v1_CheckSelfPermissionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_interface_permission_v1_CheckSelfPermissionRequest_descriptor,
        new java.lang.String[] { "PermissionIds", });
    internal_static_nervus_interface_permission_v1_CheckSelfPermissionResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_nervus_interface_permission_v1_CheckSelfPermissionResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_interface_permission_v1_CheckSelfPermissionResult_descriptor,
        new java.lang.String[] { "States", });
    internal_static_nervus_interface_permission_v1_SelfPermissionState_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_nervus_interface_permission_v1_SelfPermissionState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_interface_permission_v1_SelfPermissionState_descriptor,
        new java.lang.String[] { "PermissionId", "Granted", "State", "Requestable", });
    descriptor.resolveAllFeaturesImmutable();
    io.github.nervusos.ipc.v1.MethodRegistryProto.getDescriptor();
    io.github.nervusos.iface.permission.v1.PermissionAdminProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.github.nervusos.ipc.v1.MethodRegistryProto.methodMeta);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
