// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/permission/v1/permission_ui.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.iface.permission.v1;

/**
 * Protobuf enum {@code nervus.interface.permission.v1.PermissionUiReason}
 */
public enum PermissionUiReason
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * fail closed：未知原因按最保守处理（不重试）。
   * </pre>
   *
   * <code>PERMISSION_UI_REASON_UNSPECIFIED = 0;</code>
   */
  PERMISSION_UI_REASON_UNSPECIFIED(0),
  /**
   * <pre>
   * 交接路径不合法：含 ".."、是绝对路径，或 handoff_package_id 与调用方身份
   * 不一致。
   * </pre>
   *
   * <code>PERMISSION_UI_REASON_HANDOFF_INVALID = 1;</code>
   */
  PERMISSION_UI_REASON_HANDOFF_INVALID(1),
  /**
   * <pre>
   * 交接位置上没有那个文件，或 permissionui 读不到它（调用方没把包放进共享区，
   * 或没有 perm.storage.shared）。
   * </pre>
   *
   * <code>PERMISSION_UI_REASON_HANDOFF_NOT_FOUND = 2;</code>
   */
  PERMISSION_UI_REASON_HANDOFF_NOT_FOUND(2),
  /**
   * <pre>
   * manifest 读不出来或结构不合法——【确认框在展示之前就需要它】：要列出权限
   * 清单，必须先知道这个包申请了什么。这一条与 pkgmanager 的
   * MANIFEST_INVALID 不同层：那是安装裁决拒绝，这是连问都问不出来。
   * </pre>
   *
   * <code>PERMISSION_UI_REASON_MANIFEST_UNREADABLE = 3;</code>
   */
  PERMISSION_UI_REASON_MANIFEST_UNREADABLE(3),
  /**
   * <pre>
   * 已经有一次确认正在进行。串行化是有意的：两个确认框同时开着，用户分不清
   * 自己在给谁授权。
   * </pre>
   *
   * <code>PERMISSION_UI_REASON_BUSY = 4;</code>
   */
  PERMISSION_UI_REASON_BUSY(4),
  /**
   * <pre>
   * 没有可用的显示输出（无 DISPLAY，或窗口创建失败）。
   *
   * 【必须是一个明确的失败而不是静默放行】：显示不出确认框时，绝不能当成
   * 「用户同意了」把包装上。
   * </pre>
   *
   * <code>PERMISSION_UI_REASON_NO_DISPLAY = 5;</code>
   */
  PERMISSION_UI_REASON_NO_DISPLAY(5),
  /**
   * <pre>
   * 安装本身被 nervud 拒绝。细因在 pkgmanager 那一侧
   * （PackageManagerErrorDetail），本枚举不复制一份——复制等于制造第二个
   * 会漂移的真相源。
   * </pre>
   *
   * <code>PERMISSION_UI_REASON_INSTALL_REJECTED = 6;</code>
   */
  PERMISSION_UI_REASON_INSTALL_REJECTED(6),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PermissionUiReason.class.getName());
  }
  /**
   * <pre>
   * fail closed：未知原因按最保守处理（不重试）。
   * </pre>
   *
   * <code>PERMISSION_UI_REASON_UNSPECIFIED = 0;</code>
   */
  public static final int PERMISSION_UI_REASON_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * 交接路径不合法：含 ".."、是绝对路径，或 handoff_package_id 与调用方身份
   * 不一致。
   * </pre>
   *
   * <code>PERMISSION_UI_REASON_HANDOFF_INVALID = 1;</code>
   */
  public static final int PERMISSION_UI_REASON_HANDOFF_INVALID_VALUE = 1;
  /**
   * <pre>
   * 交接位置上没有那个文件，或 permissionui 读不到它（调用方没把包放进共享区，
   * 或没有 perm.storage.shared）。
   * </pre>
   *
   * <code>PERMISSION_UI_REASON_HANDOFF_NOT_FOUND = 2;</code>
   */
  public static final int PERMISSION_UI_REASON_HANDOFF_NOT_FOUND_VALUE = 2;
  /**
   * <pre>
   * manifest 读不出来或结构不合法——【确认框在展示之前就需要它】：要列出权限
   * 清单，必须先知道这个包申请了什么。这一条与 pkgmanager 的
   * MANIFEST_INVALID 不同层：那是安装裁决拒绝，这是连问都问不出来。
   * </pre>
   *
   * <code>PERMISSION_UI_REASON_MANIFEST_UNREADABLE = 3;</code>
   */
  public static final int PERMISSION_UI_REASON_MANIFEST_UNREADABLE_VALUE = 3;
  /**
   * <pre>
   * 已经有一次确认正在进行。串行化是有意的：两个确认框同时开着，用户分不清
   * 自己在给谁授权。
   * </pre>
   *
   * <code>PERMISSION_UI_REASON_BUSY = 4;</code>
   */
  public static final int PERMISSION_UI_REASON_BUSY_VALUE = 4;
  /**
   * <pre>
   * 没有可用的显示输出（无 DISPLAY，或窗口创建失败）。
   *
   * 【必须是一个明确的失败而不是静默放行】：显示不出确认框时，绝不能当成
   * 「用户同意了」把包装上。
   * </pre>
   *
   * <code>PERMISSION_UI_REASON_NO_DISPLAY = 5;</code>
   */
  public static final int PERMISSION_UI_REASON_NO_DISPLAY_VALUE = 5;
  /**
   * <pre>
   * 安装本身被 nervud 拒绝。细因在 pkgmanager 那一侧
   * （PackageManagerErrorDetail），本枚举不复制一份——复制等于制造第二个
   * 会漂移的真相源。
   * </pre>
   *
   * <code>PERMISSION_UI_REASON_INSTALL_REJECTED = 6;</code>
   */
  public static final int PERMISSION_UI_REASON_INSTALL_REJECTED_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PermissionUiReason valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PermissionUiReason forNumber(int value) {
    switch (value) {
      case 0: return PERMISSION_UI_REASON_UNSPECIFIED;
      case 1: return PERMISSION_UI_REASON_HANDOFF_INVALID;
      case 2: return PERMISSION_UI_REASON_HANDOFF_NOT_FOUND;
      case 3: return PERMISSION_UI_REASON_MANIFEST_UNREADABLE;
      case 4: return PERMISSION_UI_REASON_BUSY;
      case 5: return PERMISSION_UI_REASON_NO_DISPLAY;
      case 6: return PERMISSION_UI_REASON_INSTALL_REJECTED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PermissionUiReason>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PermissionUiReason> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PermissionUiReason>() {
          public PermissionUiReason findValueByNumber(int number) {
            return PermissionUiReason.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.github.nervusos.iface.permission.v1.PermissionUiProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final PermissionUiReason[] VALUES = values();

  public static PermissionUiReason valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PermissionUiReason(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:nervus.interface.permission.v1.PermissionUiReason)
}

