// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/permission/v1/permission.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.iface.permission.v1;

/**
 * <pre>
 * PermissionGrant —— 一个包的一条可授予权限。
 *
 * 只包含 GrantMode 为 USER_CONSENT 的权限：其它模式没有运行期状态可言，
 * 列出来只会给用户一排拨不动的开关。
 * </pre>
 *
 * Protobuf type {@code nervus.interface.permission.v1.PermissionGrant}
 */
public final class PermissionGrant extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:nervus.interface.permission.v1.PermissionGrant)
    PermissionGrantOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PermissionGrant.class.getName());
  }
  // Use PermissionGrant.newBuilder() to construct.
  private PermissionGrant(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PermissionGrant() {
    permissionId_ = "";
    riskClass_ = 0;
    state_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.nervusos.iface.permission.v1.PermissionAdminProto.internal_static_nervus_interface_permission_v1_PermissionGrant_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.nervusos.iface.permission.v1.PermissionAdminProto.internal_static_nervus_interface_permission_v1_PermissionGrant_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.nervusos.iface.permission.v1.PermissionGrant.class, io.github.nervusos.iface.permission.v1.PermissionGrant.Builder.class);
  }

  private int bitField0_;
  public static final int PERMISSION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object permissionId_ = "";
  /**
   * <pre>
   * 权限 ID，如 "perm.storage.user"。
   * </pre>
   *
   * <code>string permission_id = 1 [json_name = "permissionId"];</code>
   * @return The permissionId.
   */
  @java.lang.Override
  public java.lang.String getPermissionId() {
    java.lang.Object ref = permissionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      permissionId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 权限 ID，如 "perm.storage.user"。
   * </pre>
   *
   * <code>string permission_id = 1 [json_name = "permissionId"];</code>
   * @return The bytes for permissionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPermissionIdBytes() {
    java.lang.Object ref = permissionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      permissionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAY_NAME_FIELD_NUMBER = 2;
  private io.github.nervusos.ipc.v1.LocalizedText displayName_;
  /**
   * <pre>
   * 面向用户的名称与说明，来自 Catalog 的权限定义。
   *
   * 【由内核给出而不是界面自己写死】：第三方包可以定义自己的权限，
   * 界面不可能预先知道它们的文案。
   * </pre>
   *
   * <code>.nervus.ipc.v1.LocalizedText display_name = 2 [json_name = "displayName"];</code>
   * @return Whether the displayName field is set.
   */
  @java.lang.Override
  public boolean hasDisplayName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 面向用户的名称与说明，来自 Catalog 的权限定义。
   *
   * 【由内核给出而不是界面自己写死】：第三方包可以定义自己的权限，
   * 界面不可能预先知道它们的文案。
   * </pre>
   *
   * <code>.nervus.ipc.v1.LocalizedText display_name = 2 [json_name = "displayName"];</code>
   * @return The displayName.
   */
  @java.lang.Override
  public io.github.nervusos.ipc.v1.LocalizedText getDisplayName() {
    return displayName_ == null ? io.github.nervusos.ipc.v1.LocalizedText.getDefaultInstance() : displayName_;
  }
  /**
   * <pre>
   * 面向用户的名称与说明，来自 Catalog 的权限定义。
   *
   * 【由内核给出而不是界面自己写死】：第三方包可以定义自己的权限，
   * 界面不可能预先知道它们的文案。
   * </pre>
   *
   * <code>.nervus.ipc.v1.LocalizedText display_name = 2 [json_name = "displayName"];</code>
   */
  @java.lang.Override
  public io.github.nervusos.ipc.v1.LocalizedTextOrBuilder getDisplayNameOrBuilder() {
    return displayName_ == null ? io.github.nervusos.ipc.v1.LocalizedText.getDefaultInstance() : displayName_;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private io.github.nervusos.ipc.v1.LocalizedText description_;
  /**
   * <code>.nervus.ipc.v1.LocalizedText description = 3 [json_name = "description"];</code>
   * @return Whether the description field is set.
   */
  @java.lang.Override
  public boolean hasDescription() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.nervus.ipc.v1.LocalizedText description = 3 [json_name = "description"];</code>
   * @return The description.
   */
  @java.lang.Override
  public io.github.nervusos.ipc.v1.LocalizedText getDescription() {
    return description_ == null ? io.github.nervusos.ipc.v1.LocalizedText.getDefaultInstance() : description_;
  }
  /**
   * <code>.nervus.ipc.v1.LocalizedText description = 3 [json_name = "description"];</code>
   */
  @java.lang.Override
  public io.github.nervusos.ipc.v1.LocalizedTextOrBuilder getDescriptionOrBuilder() {
    return description_ == null ? io.github.nervusos.ipc.v1.LocalizedText.getDefaultInstance() : description_;
  }

  public static final int RISK_CLASS_FIELD_NUMBER = 4;
  private int riskClass_ = 0;
  /**
   * <code>.nervus.ipc.v1.RiskClass risk_class = 4 [json_name = "riskClass"];</code>
   * @return The enum numeric value on the wire for riskClass.
   */
  @java.lang.Override public int getRiskClassValue() {
    return riskClass_;
  }
  /**
   * <code>.nervus.ipc.v1.RiskClass risk_class = 4 [json_name = "riskClass"];</code>
   * @return The riskClass.
   */
  @java.lang.Override public io.github.nervusos.ipc.v1.RiskClass getRiskClass() {
    io.github.nervusos.ipc.v1.RiskClass result = io.github.nervusos.ipc.v1.RiskClass.forNumber(riskClass_);
    return result == null ? io.github.nervusos.ipc.v1.RiskClass.UNRECOGNIZED : result;
  }

  public static final int STATE_FIELD_NUMBER = 5;
  private int state_ = 0;
  /**
   * <code>.nervus.interface.permission.v1.GrantState state = 5 [json_name = "state"];</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override public int getStateValue() {
    return state_;
  }
  /**
   * <code>.nervus.interface.permission.v1.GrantState state = 5 [json_name = "state"];</code>
   * @return The state.
   */
  @java.lang.Override public io.github.nervusos.iface.permission.v1.GrantState getState() {
    io.github.nervusos.iface.permission.v1.GrantState result = io.github.nervusos.iface.permission.v1.GrantState.forNumber(state_);
    return result == null ? io.github.nervusos.iface.permission.v1.GrantState.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(permissionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, permissionId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getDisplayName());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getDescription());
    }
    if (riskClass_ != io.github.nervusos.ipc.v1.RiskClass.RISK_CLASS_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, riskClass_);
    }
    if (state_ != io.github.nervusos.iface.permission.v1.GrantState.GRANT_STATE_UNSPECIFIED.getNumber()) {
      output.writeEnum(5, state_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(permissionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, permissionId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDisplayName());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDescription());
    }
    if (riskClass_ != io.github.nervusos.ipc.v1.RiskClass.RISK_CLASS_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, riskClass_);
    }
    if (state_ != io.github.nervusos.iface.permission.v1.GrantState.GRANT_STATE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, state_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.nervusos.iface.permission.v1.PermissionGrant)) {
      return super.equals(obj);
    }
    io.github.nervusos.iface.permission.v1.PermissionGrant other = (io.github.nervusos.iface.permission.v1.PermissionGrant) obj;

    if (!getPermissionId()
        .equals(other.getPermissionId())) return false;
    if (hasDisplayName() != other.hasDisplayName()) return false;
    if (hasDisplayName()) {
      if (!getDisplayName()
          .equals(other.getDisplayName())) return false;
    }
    if (hasDescription() != other.hasDescription()) return false;
    if (hasDescription()) {
      if (!getDescription()
          .equals(other.getDescription())) return false;
    }
    if (riskClass_ != other.riskClass_) return false;
    if (state_ != other.state_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PERMISSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPermissionId().hashCode();
    if (hasDisplayName()) {
      hash = (37 * hash) + DISPLAY_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getDisplayName().hashCode();
    }
    if (hasDescription()) {
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
    }
    hash = (37 * hash) + RISK_CLASS_FIELD_NUMBER;
    hash = (53 * hash) + riskClass_;
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.nervusos.iface.permission.v1.PermissionGrant parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.iface.permission.v1.PermissionGrant parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.iface.permission.v1.PermissionGrant parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.iface.permission.v1.PermissionGrant parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.iface.permission.v1.PermissionGrant parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.iface.permission.v1.PermissionGrant parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.iface.permission.v1.PermissionGrant parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.nervusos.iface.permission.v1.PermissionGrant parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.nervusos.iface.permission.v1.PermissionGrant parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.nervusos.iface.permission.v1.PermissionGrant parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.nervusos.iface.permission.v1.PermissionGrant parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.nervusos.iface.permission.v1.PermissionGrant parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.nervusos.iface.permission.v1.PermissionGrant prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * PermissionGrant —— 一个包的一条可授予权限。
   *
   * 只包含 GrantMode 为 USER_CONSENT 的权限：其它模式没有运行期状态可言，
   * 列出来只会给用户一排拨不动的开关。
   * </pre>
   *
   * Protobuf type {@code nervus.interface.permission.v1.PermissionGrant}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nervus.interface.permission.v1.PermissionGrant)
      io.github.nervusos.iface.permission.v1.PermissionGrantOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.nervusos.iface.permission.v1.PermissionAdminProto.internal_static_nervus_interface_permission_v1_PermissionGrant_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.nervusos.iface.permission.v1.PermissionAdminProto.internal_static_nervus_interface_permission_v1_PermissionGrant_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.nervusos.iface.permission.v1.PermissionGrant.class, io.github.nervusos.iface.permission.v1.PermissionGrant.Builder.class);
    }

    // Construct using io.github.nervusos.iface.permission.v1.PermissionGrant.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getDisplayNameFieldBuilder();
        getDescriptionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      permissionId_ = "";
      displayName_ = null;
      if (displayNameBuilder_ != null) {
        displayNameBuilder_.dispose();
        displayNameBuilder_ = null;
      }
      description_ = null;
      if (descriptionBuilder_ != null) {
        descriptionBuilder_.dispose();
        descriptionBuilder_ = null;
      }
      riskClass_ = 0;
      state_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.nervusos.iface.permission.v1.PermissionAdminProto.internal_static_nervus_interface_permission_v1_PermissionGrant_descriptor;
    }

    @java.lang.Override
    public io.github.nervusos.iface.permission.v1.PermissionGrant getDefaultInstanceForType() {
      return io.github.nervusos.iface.permission.v1.PermissionGrant.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.nervusos.iface.permission.v1.PermissionGrant build() {
      io.github.nervusos.iface.permission.v1.PermissionGrant result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.nervusos.iface.permission.v1.PermissionGrant buildPartial() {
      io.github.nervusos.iface.permission.v1.PermissionGrant result = new io.github.nervusos.iface.permission.v1.PermissionGrant(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.nervusos.iface.permission.v1.PermissionGrant result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.permissionId_ = permissionId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.displayName_ = displayNameBuilder_ == null
            ? displayName_
            : displayNameBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.description_ = descriptionBuilder_ == null
            ? description_
            : descriptionBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.riskClass_ = riskClass_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.state_ = state_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.nervusos.iface.permission.v1.PermissionGrant) {
        return mergeFrom((io.github.nervusos.iface.permission.v1.PermissionGrant)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.nervusos.iface.permission.v1.PermissionGrant other) {
      if (other == io.github.nervusos.iface.permission.v1.PermissionGrant.getDefaultInstance()) return this;
      if (!other.getPermissionId().isEmpty()) {
        permissionId_ = other.permissionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasDisplayName()) {
        mergeDisplayName(other.getDisplayName());
      }
      if (other.hasDescription()) {
        mergeDescription(other.getDescription());
      }
      if (other.riskClass_ != 0) {
        setRiskClassValue(other.getRiskClassValue());
      }
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              permissionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getDisplayNameFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getDescriptionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              riskClass_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              state_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object permissionId_ = "";
    /**
     * <pre>
     * 权限 ID，如 "perm.storage.user"。
     * </pre>
     *
     * <code>string permission_id = 1 [json_name = "permissionId"];</code>
     * @return The permissionId.
     */
    public java.lang.String getPermissionId() {
      java.lang.Object ref = permissionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        permissionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 权限 ID，如 "perm.storage.user"。
     * </pre>
     *
     * <code>string permission_id = 1 [json_name = "permissionId"];</code>
     * @return The bytes for permissionId.
     */
    public com.google.protobuf.ByteString
        getPermissionIdBytes() {
      java.lang.Object ref = permissionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        permissionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 权限 ID，如 "perm.storage.user"。
     * </pre>
     *
     * <code>string permission_id = 1 [json_name = "permissionId"];</code>
     * @param value The permissionId to set.
     * @return This builder for chaining.
     */
    public Builder setPermissionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      permissionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 权限 ID，如 "perm.storage.user"。
     * </pre>
     *
     * <code>string permission_id = 1 [json_name = "permissionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPermissionId() {
      permissionId_ = getDefaultInstance().getPermissionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 权限 ID，如 "perm.storage.user"。
     * </pre>
     *
     * <code>string permission_id = 1 [json_name = "permissionId"];</code>
     * @param value The bytes for permissionId to set.
     * @return This builder for chaining.
     */
    public Builder setPermissionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      permissionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private io.github.nervusos.ipc.v1.LocalizedText displayName_;
    private com.google.protobuf.SingleFieldBuilder<
        io.github.nervusos.ipc.v1.LocalizedText, io.github.nervusos.ipc.v1.LocalizedText.Builder, io.github.nervusos.ipc.v1.LocalizedTextOrBuilder> displayNameBuilder_;
    /**
     * <pre>
     * 面向用户的名称与说明，来自 Catalog 的权限定义。
     *
     * 【由内核给出而不是界面自己写死】：第三方包可以定义自己的权限，
     * 界面不可能预先知道它们的文案。
     * </pre>
     *
     * <code>.nervus.ipc.v1.LocalizedText display_name = 2 [json_name = "displayName"];</code>
     * @return Whether the displayName field is set.
     */
    public boolean hasDisplayName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 面向用户的名称与说明，来自 Catalog 的权限定义。
     *
     * 【由内核给出而不是界面自己写死】：第三方包可以定义自己的权限，
     * 界面不可能预先知道它们的文案。
     * </pre>
     *
     * <code>.nervus.ipc.v1.LocalizedText display_name = 2 [json_name = "displayName"];</code>
     * @return The displayName.
     */
    public io.github.nervusos.ipc.v1.LocalizedText getDisplayName() {
      if (displayNameBuilder_ == null) {
        return displayName_ == null ? io.github.nervusos.ipc.v1.LocalizedText.getDefaultInstance() : displayName_;
      } else {
        return displayNameBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 面向用户的名称与说明，来自 Catalog 的权限定义。
     *
     * 【由内核给出而不是界面自己写死】：第三方包可以定义自己的权限，
     * 界面不可能预先知道它们的文案。
     * </pre>
     *
     * <code>.nervus.ipc.v1.LocalizedText display_name = 2 [json_name = "displayName"];</code>
     */
    public Builder setDisplayName(io.github.nervusos.ipc.v1.LocalizedText value) {
      if (displayNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        displayName_ = value;
      } else {
        displayNameBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 面向用户的名称与说明，来自 Catalog 的权限定义。
     *
     * 【由内核给出而不是界面自己写死】：第三方包可以定义自己的权限，
     * 界面不可能预先知道它们的文案。
     * </pre>
     *
     * <code>.nervus.ipc.v1.LocalizedText display_name = 2 [json_name = "displayName"];</code>
     */
    public Builder setDisplayName(
        io.github.nervusos.ipc.v1.LocalizedText.Builder builderForValue) {
      if (displayNameBuilder_ == null) {
        displayName_ = builderForValue.build();
      } else {
        displayNameBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 面向用户的名称与说明，来自 Catalog 的权限定义。
     *
     * 【由内核给出而不是界面自己写死】：第三方包可以定义自己的权限，
     * 界面不可能预先知道它们的文案。
     * </pre>
     *
     * <code>.nervus.ipc.v1.LocalizedText display_name = 2 [json_name = "displayName"];</code>
     */
    public Builder mergeDisplayName(io.github.nervusos.ipc.v1.LocalizedText value) {
      if (displayNameBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          displayName_ != null &&
          displayName_ != io.github.nervusos.ipc.v1.LocalizedText.getDefaultInstance()) {
          getDisplayNameBuilder().mergeFrom(value);
        } else {
          displayName_ = value;
        }
      } else {
        displayNameBuilder_.mergeFrom(value);
      }
      if (displayName_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 面向用户的名称与说明，来自 Catalog 的权限定义。
     *
     * 【由内核给出而不是界面自己写死】：第三方包可以定义自己的权限，
     * 界面不可能预先知道它们的文案。
     * </pre>
     *
     * <code>.nervus.ipc.v1.LocalizedText display_name = 2 [json_name = "displayName"];</code>
     */
    public Builder clearDisplayName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      displayName_ = null;
      if (displayNameBuilder_ != null) {
        displayNameBuilder_.dispose();
        displayNameBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 面向用户的名称与说明，来自 Catalog 的权限定义。
     *
     * 【由内核给出而不是界面自己写死】：第三方包可以定义自己的权限，
     * 界面不可能预先知道它们的文案。
     * </pre>
     *
     * <code>.nervus.ipc.v1.LocalizedText display_name = 2 [json_name = "displayName"];</code>
     */
    public io.github.nervusos.ipc.v1.LocalizedText.Builder getDisplayNameBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getDisplayNameFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 面向用户的名称与说明，来自 Catalog 的权限定义。
     *
     * 【由内核给出而不是界面自己写死】：第三方包可以定义自己的权限，
     * 界面不可能预先知道它们的文案。
     * </pre>
     *
     * <code>.nervus.ipc.v1.LocalizedText display_name = 2 [json_name = "displayName"];</code>
     */
    public io.github.nervusos.ipc.v1.LocalizedTextOrBuilder getDisplayNameOrBuilder() {
      if (displayNameBuilder_ != null) {
        return displayNameBuilder_.getMessageOrBuilder();
      } else {
        return displayName_ == null ?
            io.github.nervusos.ipc.v1.LocalizedText.getDefaultInstance() : displayName_;
      }
    }
    /**
     * <pre>
     * 面向用户的名称与说明，来自 Catalog 的权限定义。
     *
     * 【由内核给出而不是界面自己写死】：第三方包可以定义自己的权限，
     * 界面不可能预先知道它们的文案。
     * </pre>
     *
     * <code>.nervus.ipc.v1.LocalizedText display_name = 2 [json_name = "displayName"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.github.nervusos.ipc.v1.LocalizedText, io.github.nervusos.ipc.v1.LocalizedText.Builder, io.github.nervusos.ipc.v1.LocalizedTextOrBuilder> 
        getDisplayNameFieldBuilder() {
      if (displayNameBuilder_ == null) {
        displayNameBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.github.nervusos.ipc.v1.LocalizedText, io.github.nervusos.ipc.v1.LocalizedText.Builder, io.github.nervusos.ipc.v1.LocalizedTextOrBuilder>(
                getDisplayName(),
                getParentForChildren(),
                isClean());
        displayName_ = null;
      }
      return displayNameBuilder_;
    }

    private io.github.nervusos.ipc.v1.LocalizedText description_;
    private com.google.protobuf.SingleFieldBuilder<
        io.github.nervusos.ipc.v1.LocalizedText, io.github.nervusos.ipc.v1.LocalizedText.Builder, io.github.nervusos.ipc.v1.LocalizedTextOrBuilder> descriptionBuilder_;
    /**
     * <code>.nervus.ipc.v1.LocalizedText description = 3 [json_name = "description"];</code>
     * @return Whether the description field is set.
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.nervus.ipc.v1.LocalizedText description = 3 [json_name = "description"];</code>
     * @return The description.
     */
    public io.github.nervusos.ipc.v1.LocalizedText getDescription() {
      if (descriptionBuilder_ == null) {
        return description_ == null ? io.github.nervusos.ipc.v1.LocalizedText.getDefaultInstance() : description_;
      } else {
        return descriptionBuilder_.getMessage();
      }
    }
    /**
     * <code>.nervus.ipc.v1.LocalizedText description = 3 [json_name = "description"];</code>
     */
    public Builder setDescription(io.github.nervusos.ipc.v1.LocalizedText value) {
      if (descriptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        description_ = value;
      } else {
        descriptionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.nervus.ipc.v1.LocalizedText description = 3 [json_name = "description"];</code>
     */
    public Builder setDescription(
        io.github.nervusos.ipc.v1.LocalizedText.Builder builderForValue) {
      if (descriptionBuilder_ == null) {
        description_ = builderForValue.build();
      } else {
        descriptionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.nervus.ipc.v1.LocalizedText description = 3 [json_name = "description"];</code>
     */
    public Builder mergeDescription(io.github.nervusos.ipc.v1.LocalizedText value) {
      if (descriptionBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          description_ != null &&
          description_ != io.github.nervusos.ipc.v1.LocalizedText.getDefaultInstance()) {
          getDescriptionBuilder().mergeFrom(value);
        } else {
          description_ = value;
        }
      } else {
        descriptionBuilder_.mergeFrom(value);
      }
      if (description_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.nervus.ipc.v1.LocalizedText description = 3 [json_name = "description"];</code>
     */
    public Builder clearDescription() {
      bitField0_ = (bitField0_ & ~0x00000004);
      description_ = null;
      if (descriptionBuilder_ != null) {
        descriptionBuilder_.dispose();
        descriptionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.nervus.ipc.v1.LocalizedText description = 3 [json_name = "description"];</code>
     */
    public io.github.nervusos.ipc.v1.LocalizedText.Builder getDescriptionBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getDescriptionFieldBuilder().getBuilder();
    }
    /**
     * <code>.nervus.ipc.v1.LocalizedText description = 3 [json_name = "description"];</code>
     */
    public io.github.nervusos.ipc.v1.LocalizedTextOrBuilder getDescriptionOrBuilder() {
      if (descriptionBuilder_ != null) {
        return descriptionBuilder_.getMessageOrBuilder();
      } else {
        return description_ == null ?
            io.github.nervusos.ipc.v1.LocalizedText.getDefaultInstance() : description_;
      }
    }
    /**
     * <code>.nervus.ipc.v1.LocalizedText description = 3 [json_name = "description"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.github.nervusos.ipc.v1.LocalizedText, io.github.nervusos.ipc.v1.LocalizedText.Builder, io.github.nervusos.ipc.v1.LocalizedTextOrBuilder> 
        getDescriptionFieldBuilder() {
      if (descriptionBuilder_ == null) {
        descriptionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.github.nervusos.ipc.v1.LocalizedText, io.github.nervusos.ipc.v1.LocalizedText.Builder, io.github.nervusos.ipc.v1.LocalizedTextOrBuilder>(
                getDescription(),
                getParentForChildren(),
                isClean());
        description_ = null;
      }
      return descriptionBuilder_;
    }

    private int riskClass_ = 0;
    /**
     * <code>.nervus.ipc.v1.RiskClass risk_class = 4 [json_name = "riskClass"];</code>
     * @return The enum numeric value on the wire for riskClass.
     */
    @java.lang.Override public int getRiskClassValue() {
      return riskClass_;
    }
    /**
     * <code>.nervus.ipc.v1.RiskClass risk_class = 4 [json_name = "riskClass"];</code>
     * @param value The enum numeric value on the wire for riskClass to set.
     * @return This builder for chaining.
     */
    public Builder setRiskClassValue(int value) {
      riskClass_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.nervus.ipc.v1.RiskClass risk_class = 4 [json_name = "riskClass"];</code>
     * @return The riskClass.
     */
    @java.lang.Override
    public io.github.nervusos.ipc.v1.RiskClass getRiskClass() {
      io.github.nervusos.ipc.v1.RiskClass result = io.github.nervusos.ipc.v1.RiskClass.forNumber(riskClass_);
      return result == null ? io.github.nervusos.ipc.v1.RiskClass.UNRECOGNIZED : result;
    }
    /**
     * <code>.nervus.ipc.v1.RiskClass risk_class = 4 [json_name = "riskClass"];</code>
     * @param value The riskClass to set.
     * @return This builder for chaining.
     */
    public Builder setRiskClass(io.github.nervusos.ipc.v1.RiskClass value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      riskClass_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.nervus.ipc.v1.RiskClass risk_class = 4 [json_name = "riskClass"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRiskClass() {
      bitField0_ = (bitField0_ & ~0x00000008);
      riskClass_ = 0;
      onChanged();
      return this;
    }

    private int state_ = 0;
    /**
     * <code>.nervus.interface.permission.v1.GrantState state = 5 [json_name = "state"];</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.nervus.interface.permission.v1.GrantState state = 5 [json_name = "state"];</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      state_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.nervus.interface.permission.v1.GrantState state = 5 [json_name = "state"];</code>
     * @return The state.
     */
    @java.lang.Override
    public io.github.nervusos.iface.permission.v1.GrantState getState() {
      io.github.nervusos.iface.permission.v1.GrantState result = io.github.nervusos.iface.permission.v1.GrantState.forNumber(state_);
      return result == null ? io.github.nervusos.iface.permission.v1.GrantState.UNRECOGNIZED : result;
    }
    /**
     * <code>.nervus.interface.permission.v1.GrantState state = 5 [json_name = "state"];</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(io.github.nervusos.iface.permission.v1.GrantState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.nervus.interface.permission.v1.GrantState state = 5 [json_name = "state"];</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      bitField0_ = (bitField0_ & ~0x00000010);
      state_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:nervus.interface.permission.v1.PermissionGrant)
  }

  // @@protoc_insertion_point(class_scope:nervus.interface.permission.v1.PermissionGrant)
  private static final io.github.nervusos.iface.permission.v1.PermissionGrant DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.nervusos.iface.permission.v1.PermissionGrant();
  }

  public static io.github.nervusos.iface.permission.v1.PermissionGrant getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PermissionGrant>
      PARSER = new com.google.protobuf.AbstractParser<PermissionGrant>() {
    @java.lang.Override
    public PermissionGrant parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PermissionGrant> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PermissionGrant> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.nervusos.iface.permission.v1.PermissionGrant getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

