// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/permission/v1/permission.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.iface.permission.v1;

public final class PermissionAdminProto {
  private PermissionAdminProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PermissionAdminProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_interface_permission_v1_ListGrantsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_interface_permission_v1_ListGrantsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_interface_permission_v1_PermissionGrant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_interface_permission_v1_PermissionGrant_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_interface_permission_v1_PackageGrants_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_interface_permission_v1_PackageGrants_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_interface_permission_v1_GrantList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_interface_permission_v1_GrantList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_interface_permission_v1_SetGrantStateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_interface_permission_v1_SetGrantStateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_interface_permission_v1_SetGrantStateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_interface_permission_v1_SetGrantStateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/nervus/interface/permission/v1/permiss" +
      "ion.proto\022\036nervus.interface.permission.v" +
      "1\032#nervus/ipc/v1/method_registry.proto\032\'" +
      "nervus/ipc/v1/provider_descriptor.proto\"" +
      "\'\n\021ListGrantsRequest\022\022\n\npackage_id\030\001 \001(\t" +
      "\"\223\002\n\017PermissionGrant\022\025\n\rpermission_id\030\001 " +
      "\001(\t\0222\n\014display_name\030\002 \001(\0132\034.nervus.ipc.v" +
      "1.LocalizedText\0221\n\013description\030\003 \001(\0132\034.n" +
      "ervus.ipc.v1.LocalizedText\022,\n\nrisk_class" +
      "\030\004 \001(\0162\030.nervus.ipc.v1.RiskClass\0229\n\005stat" +
      "e\030\005 \001(\0162*.nervus.interface.permission.v1" +
      ".GrantState\022\031\n\021effective_granted\030\006 \001(\010\"x" +
      "\n\rPackageGrants\022\022\n\npackage_id\030\001 \001(\t\022\r\n\005l" +
      "abel\030\002 \001(\t\022D\n\013permissions\030\003 \003(\0132/.nervus" +
      ".interface.permission.v1.PermissionGrant" +
      "\"L\n\tGrantList\022?\n\010packages\030\001 \003(\0132-.nervus" +
      ".interface.permission.v1.PackageGrants\"|" +
      "\n\024SetGrantStateRequest\022\022\n\npackage_id\030\001 \001" +
      "(\t\022\025\n\rpermission_id\030\002 \001(\t\0229\n\005state\030\003 \001(\016" +
      "2*.nervus.interface.permission.v1.GrantS" +
      "tate\"R\n\025SetGrantStateResponse\0229\n\005state\030\001" +
      " \001(\0162*.nervus.interface.permission.v1.Gr" +
      "antState*\243\003\n\025PermissionAdminMethod\022\'\n#PE" +
      "RMISSION_ADMIN_METHOD_UNSPECIFIED\020\000\022\244\001\n#" +
      "PERMISSION_ADMIN_METHOD_LIST_GRANTS\020\001\032{\212" +
      "\246\035w\010\001\022\025perm.permission.admin\030\001:0nervus.i" +
      "nterface.permission.v1.ListGrantsRequest" +
      "B(nervus.interface.permission.v1.GrantLi" +
      "st\022\271\001\n\'PERMISSION_ADMIN_METHOD_SET_GRANT" +
      "_STATE\020\002\032\213\001\212\246\035\206\001\010\002\022\025perm.permission.admi" +
      "n\030\002:3nervus.interface.permission.v1.SetG" +
      "rantStateRequestB4nervus.interface.permi" +
      "ssion.v1.SetGrantStateResponse*\233\001\n\nGrant" +
      "State\022\033\n\027GRANT_STATE_UNSPECIFIED\020\000\022\035\n\031GR" +
      "ANT_STATE_NOT_REQUESTED\020\001\022\027\n\023GRANT_STATE" +
      "_GRANTED\020\002\022\026\n\022GRANT_STATE_DENIED\020\003\022 \n\034GR" +
      "ANT_STATE_DENIED_PERMANENT\020\004B\216\001\n&io.gith" +
      "ub.nervusos.iface.permission.v1B\024Permiss" +
      "ionAdminProtoP\001ZLgithub.com/nervus-os/ne" +
      "rvus-ipc/protocol/interface/permissionv1" +
      ";permissionv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.github.nervusos.ipc.v1.MethodRegistryProto.getDescriptor(),
          io.github.nervusos.ipc.v1.ProviderDescriptorProto.getDescriptor(),
        });
    internal_static_nervus_interface_permission_v1_ListGrantsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nervus_interface_permission_v1_ListGrantsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_interface_permission_v1_ListGrantsRequest_descriptor,
        new java.lang.String[] { "PackageId", });
    internal_static_nervus_interface_permission_v1_PermissionGrant_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_nervus_interface_permission_v1_PermissionGrant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_interface_permission_v1_PermissionGrant_descriptor,
        new java.lang.String[] { "PermissionId", "DisplayName", "Description", "RiskClass", "State", "EffectiveGranted", });
    internal_static_nervus_interface_permission_v1_PackageGrants_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_nervus_interface_permission_v1_PackageGrants_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_interface_permission_v1_PackageGrants_descriptor,
        new java.lang.String[] { "PackageId", "Label", "Permissions", });
    internal_static_nervus_interface_permission_v1_GrantList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_nervus_interface_permission_v1_GrantList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_interface_permission_v1_GrantList_descriptor,
        new java.lang.String[] { "Packages", });
    internal_static_nervus_interface_permission_v1_SetGrantStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_nervus_interface_permission_v1_SetGrantStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_interface_permission_v1_SetGrantStateRequest_descriptor,
        new java.lang.String[] { "PackageId", "PermissionId", "State", });
    internal_static_nervus_interface_permission_v1_SetGrantStateResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_nervus_interface_permission_v1_SetGrantStateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_interface_permission_v1_SetGrantStateResponse_descriptor,
        new java.lang.String[] { "State", });
    descriptor.resolveAllFeaturesImmutable();
    io.github.nervusos.ipc.v1.MethodRegistryProto.getDescriptor();
    io.github.nervusos.ipc.v1.ProviderDescriptorProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.github.nervusos.ipc.v1.MethodRegistryProto.methodMeta);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
