// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/manipulator/v1/manipulator.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.github.nervusos.iface.manipulator.v1;

@kotlin.jvm.JvmName("-initializearmState")
public inline fun armState(block: io.github.nervusos.iface.manipulator.v1.ArmStateKt.Dsl.() -> kotlin.Unit): io.github.nervusos.iface.manipulator.v1.ArmState =
  io.github.nervusos.iface.manipulator.v1.ArmStateKt.Dsl._create(io.github.nervusos.iface.manipulator.v1.ArmState.newBuilder()).apply { block() }._build()
/**
 * ```
 * ArmState —— GetArmState / SubscribeArmState 的状态载荷。
 * ```
 *
 * Protobuf type `nervus.interface.manipulator.v1.ArmState`
 */
public object ArmStateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.github.nervusos.iface.manipulator.v1.ArmState.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: io.github.nervusos.iface.manipulator.v1.ArmState.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): io.github.nervusos.iface.manipulator.v1.ArmState = _builder.build()

    /**
     * `.nervus.interface.manipulator.v1.ArmReadiness readiness = 1 [json_name = "readiness"];`
     */
    public var readiness: io.github.nervusos.iface.manipulator.v1.ArmReadiness
      @JvmName("getReadiness")
      get() = _builder.readiness
      @JvmName("setReadiness")
      set(value) {
        _builder.readiness = value
      }
    public var readinessValue: kotlin.Int
      @JvmName("getReadinessValue")
      get() = _builder.readinessValue
      @JvmName("setReadinessValue")
      set(value) {
        _builder.readinessValue = value
      }
    /**
     * `.nervus.interface.manipulator.v1.ArmReadiness readiness = 1 [json_name = "readiness"];`
     */
    public fun clearReadiness() {
      _builder.clearReadiness()
    }

    /**
     * `.nervus.interface.manipulator.v1.JointState joints = 2 [json_name = "joints"];`
     */
    public var joints: io.github.nervusos.iface.manipulator.v1.JointState
      @JvmName("getJoints")
      get() = _builder.joints
      @JvmName("setJoints")
      set(value) {
        _builder.joints = value
      }
    /**
     * `.nervus.interface.manipulator.v1.JointState joints = 2 [json_name = "joints"];`
     */
    public fun clearJoints() {
      _builder.clearJoints()
    }
    /**
     * `.nervus.interface.manipulator.v1.JointState joints = 2 [json_name = "joints"];`
     * @return Whether the joints field is set.
     */
    public fun hasJoints(): kotlin.Boolean {
      return _builder.hasJoints()
    }

    public val ArmStateKt.Dsl.jointsOrNull: io.github.nervusos.iface.manipulator.v1.JointState?
      get() = _builder.jointsOrNull

    /**
     * ```
     * 末端（tool center point）位姿
     * ```
     *
     * `.nervus.interface.manipulator.v1.Pose tcp_pose = 3 [json_name = "tcpPose"];`
     */
    public var tcpPose: io.github.nervusos.iface.manipulator.v1.Pose
      @JvmName("getTcpPose")
      get() = _builder.tcpPose
      @JvmName("setTcpPose")
      set(value) {
        _builder.tcpPose = value
      }
    /**
     * ```
     * 末端（tool center point）位姿
     * ```
     *
     * `.nervus.interface.manipulator.v1.Pose tcp_pose = 3 [json_name = "tcpPose"];`
     */
    public fun clearTcpPose() {
      _builder.clearTcpPose()
    }
    /**
     * ```
     * 末端（tool center point）位姿
     * ```
     *
     * `.nervus.interface.manipulator.v1.Pose tcp_pose = 3 [json_name = "tcpPose"];`
     * @return Whether the tcpPose field is set.
     */
    public fun hasTcpPose(): kotlin.Boolean {
      return _builder.hasTcpPose()
    }

    public val ArmStateKt.Dsl.tcpPoseOrNull: io.github.nervusos.iface.manipulator.v1.Pose?
      get() = _builder.tcpPoseOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class JointLowerRadProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 各关节下限，rad（索引对齐 joints）
     * ```
     *
     * `repeated double joint_lower_rad = 4 [json_name = "jointLowerRad"];`
     */
     public val jointLowerRad: com.google.protobuf.kotlin.DslList<kotlin.Double, JointLowerRadProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.jointLowerRadList
      )
    /**
     * ```
     * 各关节下限，rad（索引对齐 joints）
     * ```
     *
     * `repeated double joint_lower_rad = 4 [json_name = "jointLowerRad"];`
     * @param value The jointLowerRad to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addJointLowerRad")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, JointLowerRadProxy>.add(value: kotlin.Double) {
      _builder.addJointLowerRad(value)
    }/**
     * ```
     * 各关节下限，rad（索引对齐 joints）
     * ```
     *
     * `repeated double joint_lower_rad = 4 [json_name = "jointLowerRad"];`
     * @param value The jointLowerRad to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignJointLowerRad")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, JointLowerRadProxy>.plusAssign(value: kotlin.Double) {
      add(value)
    }/**
     * ```
     * 各关节下限，rad（索引对齐 joints）
     * ```
     *
     * `repeated double joint_lower_rad = 4 [json_name = "jointLowerRad"];`
     * @param values The jointLowerRad to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllJointLowerRad")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, JointLowerRadProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Double>) {
      _builder.addAllJointLowerRad(values)
    }/**
     * ```
     * 各关节下限，rad（索引对齐 joints）
     * ```
     *
     * `repeated double joint_lower_rad = 4 [json_name = "jointLowerRad"];`
     * @param values The jointLowerRad to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllJointLowerRad")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, JointLowerRadProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Double>) {
      addAll(values)
    }/**
     * ```
     * 各关节下限，rad（索引对齐 joints）
     * ```
     *
     * `repeated double joint_lower_rad = 4 [json_name = "jointLowerRad"];`
     * @param index The index to set the value at.
     * @param value The jointLowerRad to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setJointLowerRad")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, JointLowerRadProxy>.set(index: kotlin.Int, value: kotlin.Double) {
      _builder.setJointLowerRad(index, value)
    }/**
     * ```
     * 各关节下限，rad（索引对齐 joints）
     * ```
     *
     * `repeated double joint_lower_rad = 4 [json_name = "jointLowerRad"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearJointLowerRad")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, JointLowerRadProxy>.clear() {
      _builder.clearJointLowerRad()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class JointUpperRadProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 各关节上限，rad
     * ```
     *
     * `repeated double joint_upper_rad = 5 [json_name = "jointUpperRad"];`
     */
     public val jointUpperRad: com.google.protobuf.kotlin.DslList<kotlin.Double, JointUpperRadProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.jointUpperRadList
      )
    /**
     * ```
     * 各关节上限，rad
     * ```
     *
     * `repeated double joint_upper_rad = 5 [json_name = "jointUpperRad"];`
     * @param value The jointUpperRad to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addJointUpperRad")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, JointUpperRadProxy>.add(value: kotlin.Double) {
      _builder.addJointUpperRad(value)
    }/**
     * ```
     * 各关节上限，rad
     * ```
     *
     * `repeated double joint_upper_rad = 5 [json_name = "jointUpperRad"];`
     * @param value The jointUpperRad to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignJointUpperRad")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, JointUpperRadProxy>.plusAssign(value: kotlin.Double) {
      add(value)
    }/**
     * ```
     * 各关节上限，rad
     * ```
     *
     * `repeated double joint_upper_rad = 5 [json_name = "jointUpperRad"];`
     * @param values The jointUpperRad to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllJointUpperRad")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, JointUpperRadProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Double>) {
      _builder.addAllJointUpperRad(values)
    }/**
     * ```
     * 各关节上限，rad
     * ```
     *
     * `repeated double joint_upper_rad = 5 [json_name = "jointUpperRad"];`
     * @param values The jointUpperRad to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllJointUpperRad")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, JointUpperRadProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Double>) {
      addAll(values)
    }/**
     * ```
     * 各关节上限，rad
     * ```
     *
     * `repeated double joint_upper_rad = 5 [json_name = "jointUpperRad"];`
     * @param index The index to set the value at.
     * @param value The jointUpperRad to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setJointUpperRad")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, JointUpperRadProxy>.set(index: kotlin.Int, value: kotlin.Double) {
      _builder.setJointUpperRad(index, value)
    }/**
     * ```
     * 各关节上限，rad
     * ```
     *
     * `repeated double joint_upper_rad = 5 [json_name = "jointUpperRad"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearJointUpperRad")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, JointUpperRadProxy>.clear() {
      _builder.clearJointUpperRad()
    }
    /**
     * ```
     * 当前 motion epoch（陈旧命令据此判废）
     * ```
     *
     * `uint64 active_motion_epoch = 6 [json_name = "activeMotionEpoch"];`
     */
    public var activeMotionEpoch: kotlin.Long
      @JvmName("getActiveMotionEpoch")
      get() = _builder.activeMotionEpoch
      @JvmName("setActiveMotionEpoch")
      set(value) {
        _builder.activeMotionEpoch = value
      }
    /**
     * ```
     * 当前 motion epoch（陈旧命令据此判废）
     * ```
     *
     * `uint64 active_motion_epoch = 6 [json_name = "activeMotionEpoch"];`
     */
    public fun clearActiveMotionEpoch() {
      _builder.clearActiveMotionEpoch()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.github.nervusos.iface.manipulator.v1.ArmState.copy(block: `io.github.nervusos.iface.manipulator.v1`.ArmStateKt.Dsl.() -> kotlin.Unit): io.github.nervusos.iface.manipulator.v1.ArmState =
  `io.github.nervusos.iface.manipulator.v1`.ArmStateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val io.github.nervusos.iface.manipulator.v1.ArmStateOrBuilder.jointsOrNull: io.github.nervusos.iface.manipulator.v1.JointState?
  get() = if (hasJoints()) getJoints() else null

public val io.github.nervusos.iface.manipulator.v1.ArmStateOrBuilder.tcpPoseOrNull: io.github.nervusos.iface.manipulator.v1.Pose?
  get() = if (hasTcpPose()) getTcpPose() else null

