// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/manipulator/v1/manipulator.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.github.nervusos.iface.manipulator.v1;

@kotlin.jvm.JvmName("-initializejointState")
public inline fun jointState(block: io.github.nervusos.iface.manipulator.v1.JointStateKt.Dsl.() -> kotlin.Unit): io.github.nervusos.iface.manipulator.v1.JointState =
  io.github.nervusos.iface.manipulator.v1.JointStateKt.Dsl._create(io.github.nervusos.iface.manipulator.v1.JointState.newBuilder()).apply { block() }._build()
/**
 * ```
 * JointState —— 关节空间状态。position/velocity 的索引与 Provider 的关节顺序
 * 一一对应（顺序由 Provider Descriptor / ArmState.limits 长度约束）。
 * ```
 *
 * Protobuf type `nervus.interface.manipulator.v1.JointState`
 */
public object JointStateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.github.nervusos.iface.manipulator.v1.JointState.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: io.github.nervusos.iface.manipulator.v1.JointState.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): io.github.nervusos.iface.manipulator.v1.JointState = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PositionRadProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 各关节角，rad
     * ```
     *
     * `repeated double position_rad = 1 [json_name = "positionRad"];`
     */
     public val positionRad: com.google.protobuf.kotlin.DslList<kotlin.Double, PositionRadProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.positionRadList
      )
    /**
     * ```
     * 各关节角，rad
     * ```
     *
     * `repeated double position_rad = 1 [json_name = "positionRad"];`
     * @param value The positionRad to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addPositionRad")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, PositionRadProxy>.add(value: kotlin.Double) {
      _builder.addPositionRad(value)
    }/**
     * ```
     * 各关节角，rad
     * ```
     *
     * `repeated double position_rad = 1 [json_name = "positionRad"];`
     * @param value The positionRad to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignPositionRad")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, PositionRadProxy>.plusAssign(value: kotlin.Double) {
      add(value)
    }/**
     * ```
     * 各关节角，rad
     * ```
     *
     * `repeated double position_rad = 1 [json_name = "positionRad"];`
     * @param values The positionRad to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllPositionRad")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, PositionRadProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Double>) {
      _builder.addAllPositionRad(values)
    }/**
     * ```
     * 各关节角，rad
     * ```
     *
     * `repeated double position_rad = 1 [json_name = "positionRad"];`
     * @param values The positionRad to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllPositionRad")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, PositionRadProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Double>) {
      addAll(values)
    }/**
     * ```
     * 各关节角，rad
     * ```
     *
     * `repeated double position_rad = 1 [json_name = "positionRad"];`
     * @param index The index to set the value at.
     * @param value The positionRad to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setPositionRad")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, PositionRadProxy>.set(index: kotlin.Int, value: kotlin.Double) {
      _builder.setPositionRad(index, value)
    }/**
     * ```
     * 各关节角，rad
     * ```
     *
     * `repeated double position_rad = 1 [json_name = "positionRad"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearPositionRad")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, PositionRadProxy>.clear() {
      _builder.clearPositionRad()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class VelocityRadSProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 各关节角速度，rad/s
     * ```
     *
     * `repeated double velocity_rad_s = 2 [json_name = "velocityRadS"];`
     */
     public val velocityRadS: com.google.protobuf.kotlin.DslList<kotlin.Double, VelocityRadSProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.velocityRadSList
      )
    /**
     * ```
     * 各关节角速度，rad/s
     * ```
     *
     * `repeated double velocity_rad_s = 2 [json_name = "velocityRadS"];`
     * @param value The velocityRadS to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addVelocityRadS")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, VelocityRadSProxy>.add(value: kotlin.Double) {
      _builder.addVelocityRadS(value)
    }/**
     * ```
     * 各关节角速度，rad/s
     * ```
     *
     * `repeated double velocity_rad_s = 2 [json_name = "velocityRadS"];`
     * @param value The velocityRadS to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignVelocityRadS")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, VelocityRadSProxy>.plusAssign(value: kotlin.Double) {
      add(value)
    }/**
     * ```
     * 各关节角速度，rad/s
     * ```
     *
     * `repeated double velocity_rad_s = 2 [json_name = "velocityRadS"];`
     * @param values The velocityRadS to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllVelocityRadS")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, VelocityRadSProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Double>) {
      _builder.addAllVelocityRadS(values)
    }/**
     * ```
     * 各关节角速度，rad/s
     * ```
     *
     * `repeated double velocity_rad_s = 2 [json_name = "velocityRadS"];`
     * @param values The velocityRadS to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllVelocityRadS")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, VelocityRadSProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Double>) {
      addAll(values)
    }/**
     * ```
     * 各关节角速度，rad/s
     * ```
     *
     * `repeated double velocity_rad_s = 2 [json_name = "velocityRadS"];`
     * @param index The index to set the value at.
     * @param value The velocityRadS to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setVelocityRadS")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Double, VelocityRadSProxy>.set(index: kotlin.Int, value: kotlin.Double) {
      _builder.setVelocityRadS(index, value)
    }/**
     * ```
     * 各关节角速度，rad/s
     * ```
     *
     * `repeated double velocity_rad_s = 2 [json_name = "velocityRadS"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearVelocityRadS")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Double, VelocityRadSProxy>.clear() {
      _builder.clearVelocityRadS()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun io.github.nervusos.iface.manipulator.v1.JointState.copy(block: `io.github.nervusos.iface.manipulator.v1`.JointStateKt.Dsl.() -> kotlin.Unit): io.github.nervusos.iface.manipulator.v1.JointState =
  `io.github.nervusos.iface.manipulator.v1`.JointStateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

