// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/manipulator/v1/manipulator.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.github.nervusos.iface.manipulator.v1;

@kotlin.jvm.JvmName("-initializemanipulatorErrorDetail")
public inline fun manipulatorErrorDetail(block: io.github.nervusos.iface.manipulator.v1.ManipulatorErrorDetailKt.Dsl.() -> kotlin.Unit): io.github.nervusos.iface.manipulator.v1.ManipulatorErrorDetail =
  io.github.nervusos.iface.manipulator.v1.ManipulatorErrorDetailKt.Dsl._create(io.github.nervusos.iface.manipulator.v1.ManipulatorErrorDetail.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `nervus.interface.manipulator.v1.ManipulatorErrorDetail`
 */
public object ManipulatorErrorDetailKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.github.nervusos.iface.manipulator.v1.ManipulatorErrorDetail.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: io.github.nervusos.iface.manipulator.v1.ManipulatorErrorDetail.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): io.github.nervusos.iface.manipulator.v1.ManipulatorErrorDetail = _builder.build()

    /**
     * `.nervus.interface.manipulator.v1.ManipulatorReason reason = 1 [json_name = "reason"];`
     */
    public var reason: io.github.nervusos.iface.manipulator.v1.ManipulatorReason
      @JvmName("getReason")
      get() = _builder.reason
      @JvmName("setReason")
      set(value) {
        _builder.reason = value
      }
    public var reasonValue: kotlin.Int
      @JvmName("getReasonValue")
      get() = _builder.reasonValue
      @JvmName("setReasonValue")
      set(value) {
        _builder.reasonValue = value
      }
    /**
     * `.nervus.interface.manipulator.v1.ManipulatorReason reason = 1 [json_name = "reason"];`
     */
    public fun clearReason() {
      _builder.clearReason()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.github.nervusos.iface.manipulator.v1.ManipulatorErrorDetail.copy(block: `io.github.nervusos.iface.manipulator.v1`.ManipulatorErrorDetailKt.Dsl.() -> kotlin.Unit): io.github.nervusos.iface.manipulator.v1.ManipulatorErrorDetail =
  `io.github.nervusos.iface.manipulator.v1`.ManipulatorErrorDetailKt.Dsl._create(this.toBuilder()).apply { block() }._build()

