// Nervus IPC v1 -- 通用 Transfer 数据面契约。
//
// Transfer 不增加 Envelope body。创建、提交和中止都通过
// nervus.interface.transfer.control 的普通 Request/Response 完成；真正的数据
// 走独立 UDS。Camera、Microphone、文件导入和未来传感器流共用本协议。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nervus/ipc/v1/transfer.proto

package ipcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferDirection int32

const (
	TransferDirection_TRANSFER_DIRECTION_UNSPECIFIED        TransferDirection = 0
	TransferDirection_TRANSFER_DIRECTION_PROVIDER_TO_CALLER TransferDirection = 1
	TransferDirection_TRANSFER_DIRECTION_CALLER_TO_PROVIDER TransferDirection = 2
	TransferDirection_TRANSFER_DIRECTION_BIDIRECTIONAL      TransferDirection = 3
)

// Enum value maps for TransferDirection.
var (
	TransferDirection_name = map[int32]string{
		0: "TRANSFER_DIRECTION_UNSPECIFIED",
		1: "TRANSFER_DIRECTION_PROVIDER_TO_CALLER",
		2: "TRANSFER_DIRECTION_CALLER_TO_PROVIDER",
		3: "TRANSFER_DIRECTION_BIDIRECTIONAL",
	}
	TransferDirection_value = map[string]int32{
		"TRANSFER_DIRECTION_UNSPECIFIED":        0,
		"TRANSFER_DIRECTION_PROVIDER_TO_CALLER": 1,
		"TRANSFER_DIRECTION_CALLER_TO_PROVIDER": 2,
		"TRANSFER_DIRECTION_BIDIRECTIONAL":      3,
	}
)

func (x TransferDirection) Enum() *TransferDirection {
	p := new(TransferDirection)
	*p = x
	return p
}

func (x TransferDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_nervus_ipc_v1_transfer_proto_enumTypes[0].Descriptor()
}

func (TransferDirection) Type() protoreflect.EnumType {
	return &file_nervus_ipc_v1_transfer_proto_enumTypes[0]
}

func (x TransferDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferDirection.Descriptor instead.
func (TransferDirection) EnumDescriptor() ([]byte, []int) {
	return file_nervus_ipc_v1_transfer_proto_rawDescGZIP(), []int{0}
}

type TransferMode int32

const (
	TransferMode_TRANSFER_MODE_UNSPECIFIED TransferMode = 0
	// 基线模式。两端连接固定 Transfer UDS，由 nervud 做有界帧转发。
	TransferMode_TRANSFER_MODE_FRAMED_RELAY TransferMode = 1
	// Linux 高吞吐模式。nervud 经 SCM_RIGHTS 分发 memfd/eventfd；
	// 具体 ring ABI 必须在实现前单独冻结。
	TransferMode_TRANSFER_MODE_SHARED_MEMORY_RING TransferMode = 2
)

// Enum value maps for TransferMode.
var (
	TransferMode_name = map[int32]string{
		0: "TRANSFER_MODE_UNSPECIFIED",
		1: "TRANSFER_MODE_FRAMED_RELAY",
		2: "TRANSFER_MODE_SHARED_MEMORY_RING",
	}
	TransferMode_value = map[string]int32{
		"TRANSFER_MODE_UNSPECIFIED":        0,
		"TRANSFER_MODE_FRAMED_RELAY":       1,
		"TRANSFER_MODE_SHARED_MEMORY_RING": 2,
	}
)

func (x TransferMode) Enum() *TransferMode {
	p := new(TransferMode)
	*p = x
	return p
}

func (x TransferMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferMode) Descriptor() protoreflect.EnumDescriptor {
	return file_nervus_ipc_v1_transfer_proto_enumTypes[1].Descriptor()
}

func (TransferMode) Type() protoreflect.EnumType {
	return &file_nervus_ipc_v1_transfer_proto_enumTypes[1]
}

func (x TransferMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferMode.Descriptor instead.
func (TransferMode) EnumDescriptor() ([]byte, []int) {
	return file_nervus_ipc_v1_transfer_proto_rawDescGZIP(), []int{1}
}

type TransferRole int32

const (
	TransferRole_TRANSFER_ROLE_UNSPECIFIED TransferRole = 0
	TransferRole_TRANSFER_ROLE_PRODUCER    TransferRole = 1
	TransferRole_TRANSFER_ROLE_CONSUMER    TransferRole = 2
	// BIDIRECTIONAL Transfer 的两端都使用 PEER。
	TransferRole_TRANSFER_ROLE_PEER TransferRole = 3
)

// Enum value maps for TransferRole.
var (
	TransferRole_name = map[int32]string{
		0: "TRANSFER_ROLE_UNSPECIFIED",
		1: "TRANSFER_ROLE_PRODUCER",
		2: "TRANSFER_ROLE_CONSUMER",
		3: "TRANSFER_ROLE_PEER",
	}
	TransferRole_value = map[string]int32{
		"TRANSFER_ROLE_UNSPECIFIED": 0,
		"TRANSFER_ROLE_PRODUCER":    1,
		"TRANSFER_ROLE_CONSUMER":    2,
		"TRANSFER_ROLE_PEER":        3,
	}
)

func (x TransferRole) Enum() *TransferRole {
	p := new(TransferRole)
	*p = x
	return p
}

func (x TransferRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferRole) Descriptor() protoreflect.EnumDescriptor {
	return file_nervus_ipc_v1_transfer_proto_enumTypes[2].Descriptor()
}

func (TransferRole) Type() protoreflect.EnumType {
	return &file_nervus_ipc_v1_transfer_proto_enumTypes[2]
}

func (x TransferRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferRole.Descriptor instead.
func (TransferRole) EnumDescriptor() ([]byte, []int) {
	return file_nervus_ipc_v1_transfer_proto_rawDescGZIP(), []int{2}
}

// TransferPolicy 是 MethodMeta 的可选字段。字段不存在表示该方法绝不允许创建
// Transfer；Provider 不能在运行时自行把普通方法升级为流方法。
type TransferPolicy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Direction         TransferDirection      `protobuf:"varint,1,opt,name=direction,proto3,enum=nervus.ipc.v1.TransferDirection" json:"direction,omitempty"`
	MaxStreams        uint32                 `protobuf:"varint,2,opt,name=max_streams,json=maxStreams,proto3" json:"max_streams,omitempty"`
	MaxPacketBytes    uint32                 `protobuf:"varint,3,opt,name=max_packet_bytes,json=maxPacketBytes,proto3" json:"max_packet_bytes,omitempty"`
	MaxBytesPerSecond uint64                 `protobuf:"varint,4,opt,name=max_bytes_per_second,json=maxBytesPerSecond,proto3" json:"max_bytes_per_second,omitempty"`
	// 空集合表示只允许 FRAMED_RELAY，而不是允许任意未来模式。
	AllowedModes  []TransferMode `protobuf:"varint,5,rep,packed,name=allowed_modes,json=allowedModes,proto3,enum=nervus.ipc.v1.TransferMode" json:"allowed_modes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferPolicy) Reset() {
	*x = TransferPolicy{}
	mi := &file_nervus_ipc_v1_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferPolicy) ProtoMessage() {}

func (x *TransferPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_ipc_v1_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferPolicy.ProtoReflect.Descriptor instead.
func (*TransferPolicy) Descriptor() ([]byte, []int) {
	return file_nervus_ipc_v1_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *TransferPolicy) GetDirection() TransferDirection {
	if x != nil {
		return x.Direction
	}
	return TransferDirection_TRANSFER_DIRECTION_UNSPECIFIED
}

func (x *TransferPolicy) GetMaxStreams() uint32 {
	if x != nil {
		return x.MaxStreams
	}
	return 0
}

func (x *TransferPolicy) GetMaxPacketBytes() uint32 {
	if x != nil {
		return x.MaxPacketBytes
	}
	return 0
}

func (x *TransferPolicy) GetMaxBytesPerSecond() uint64 {
	if x != nil {
		return x.MaxBytesPerSecond
	}
	return 0
}

func (x *TransferPolicy) GetAllowedModes() []TransferMode {
	if x != nil {
		return x.AllowedModes
	}
	return nil
}

// TransferHandle 是某一端附着数据面的不透明凭证。它可以嵌入任意能力接口的
// OpenStream 响应，因此新 Provider 不需要新增 IPC 机制。PREPARED 状态只允许
// provider handle 附着；caller handle 必须等 Transfer Control Commit 成功。
type TransferHandle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 128 bit 随机 ID。不得使用可预测的递增数字。
	TransferId []byte `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	// 至少 256 bit、一次性、短 TTL 的附着票据。
	AttachTicket []byte       `protobuf:"bytes,2,opt,name=attach_ticket,json=attachTicket,proto3" json:"attach_ticket,omitempty"`
	Role         TransferRole `protobuf:"varint,3,opt,name=role,proto3,enum=nervus.ipc.v1.TransferRole" json:"role,omitempty"`
	Mode         TransferMode `protobuf:"varint,4,opt,name=mode,proto3,enum=nervus.ipc.v1.TransferMode" json:"mode,omitempty"`
	// CLOCK_MONOTONIC 时间域；0 非法。
	ExpiresAtMonotonicNanos uint64 `protobuf:"varint,5,opt,name=expires_at_monotonic_nanos,json=expiresAtMonotonicNanos,proto3" json:"expires_at_monotonic_nanos,omitempty"`
	// 生产固定为 /run/nervus/nervud-transfer.sock；测试构建可以返回其它路径。
	DataPlaneEndpoint string `protobuf:"bytes,6,opt,name=data_plane_endpoint,json=dataPlaneEndpoint,proto3" json:"data_plane_endpoint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransferHandle) Reset() {
	*x = TransferHandle{}
	mi := &file_nervus_ipc_v1_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferHandle) ProtoMessage() {}

func (x *TransferHandle) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_ipc_v1_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferHandle.ProtoReflect.Descriptor instead.
func (*TransferHandle) Descriptor() ([]byte, []int) {
	return file_nervus_ipc_v1_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *TransferHandle) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *TransferHandle) GetAttachTicket() []byte {
	if x != nil {
		return x.AttachTicket
	}
	return nil
}

func (x *TransferHandle) GetRole() TransferRole {
	if x != nil {
		return x.Role
	}
	return TransferRole_TRANSFER_ROLE_UNSPECIFIED
}

func (x *TransferHandle) GetMode() TransferMode {
	if x != nil {
		return x.Mode
	}
	return TransferMode_TRANSFER_MODE_UNSPECIFIED
}

func (x *TransferHandle) GetExpiresAtMonotonicNanos() uint64 {
	if x != nil {
		return x.ExpiresAtMonotonicNanos
	}
	return 0
}

func (x *TransferHandle) GetDataPlaneEndpoint() string {
	if x != nil {
		return x.DataPlaneEndpoint
	}
	return ""
}

// AttachTransfer 是独立数据 UDS 上的第一帧，不是 Envelope body。握手的
// AttachTransfer 与 AttachTransferResult 都沿用控制面的 u32 big-endian 长度前缀
// + protobuf payload；成功后才切换到下方 NVT1 数据帧。nervud 还必须用
// SO_PEERCRED 复核进程身份；仅持有 ticket 不构成授权。
type AttachTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    []byte                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	AttachTicket  []byte                 `protobuf:"bytes,2,opt,name=attach_ticket,json=attachTicket,proto3" json:"attach_ticket,omitempty"`
	Role          TransferRole           `protobuf:"varint,3,opt,name=role,proto3,enum=nervus.ipc.v1.TransferRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachTransfer) Reset() {
	*x = AttachTransfer{}
	mi := &file_nervus_ipc_v1_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachTransfer) ProtoMessage() {}

func (x *AttachTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_ipc_v1_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachTransfer.ProtoReflect.Descriptor instead.
func (*AttachTransfer) Descriptor() ([]byte, []int) {
	return file_nervus_ipc_v1_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *AttachTransfer) GetTransferId() []byte {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *AttachTransfer) GetAttachTicket() []byte {
	if x != nil {
		return x.AttachTicket
	}
	return nil
}

func (x *AttachTransfer) GetRole() TransferRole {
	if x != nil {
		return x.Role
	}
	return TransferRole_TRANSFER_ROLE_UNSPECIFIED
}

type AttachTransferSuccess struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Mode              TransferMode           `protobuf:"varint,1,opt,name=mode,proto3,enum=nervus.ipc.v1.TransferMode" json:"mode,omitempty"`
	MaxPacketBytes    uint32                 `protobuf:"varint,2,opt,name=max_packet_bytes,json=maxPacketBytes,proto3" json:"max_packet_bytes,omitempty"`
	MaxBytesPerSecond uint64                 `protobuf:"varint,3,opt,name=max_bytes_per_second,json=maxBytesPerSecond,proto3" json:"max_bytes_per_second,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AttachTransferSuccess) Reset() {
	*x = AttachTransferSuccess{}
	mi := &file_nervus_ipc_v1_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachTransferSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachTransferSuccess) ProtoMessage() {}

func (x *AttachTransferSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_ipc_v1_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachTransferSuccess.ProtoReflect.Descriptor instead.
func (*AttachTransferSuccess) Descriptor() ([]byte, []int) {
	return file_nervus_ipc_v1_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *AttachTransferSuccess) GetMode() TransferMode {
	if x != nil {
		return x.Mode
	}
	return TransferMode_TRANSFER_MODE_UNSPECIFIED
}

func (x *AttachTransferSuccess) GetMaxPacketBytes() uint32 {
	if x != nil {
		return x.MaxPacketBytes
	}
	return 0
}

func (x *AttachTransferSuccess) GetMaxBytesPerSecond() uint64 {
	if x != nil {
		return x.MaxBytesPerSecond
	}
	return 0
}

type AttachTransferResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*AttachTransferResult_Success
	//	*AttachTransferResult_Failure
	Outcome       isAttachTransferResult_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachTransferResult) Reset() {
	*x = AttachTransferResult{}
	mi := &file_nervus_ipc_v1_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachTransferResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachTransferResult) ProtoMessage() {}

func (x *AttachTransferResult) ProtoReflect() protoreflect.Message {
	mi := &file_nervus_ipc_v1_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachTransferResult.ProtoReflect.Descriptor instead.
func (*AttachTransferResult) Descriptor() ([]byte, []int) {
	return file_nervus_ipc_v1_transfer_proto_rawDescGZIP(), []int{4}
}

func (x *AttachTransferResult) GetOutcome() isAttachTransferResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *AttachTransferResult) GetSuccess() *AttachTransferSuccess {
	if x != nil {
		if x, ok := x.Outcome.(*AttachTransferResult_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *AttachTransferResult) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Outcome.(*AttachTransferResult_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isAttachTransferResult_Outcome interface {
	isAttachTransferResult_Outcome()
}

type AttachTransferResult_Success struct {
	Success *AttachTransferSuccess `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type AttachTransferResult_Failure struct {
	Failure *Failure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*AttachTransferResult_Success) isAttachTransferResult_Outcome() {}

func (*AttachTransferResult_Failure) isAttachTransferResult_Outcome() {}

var File_nervus_ipc_v1_transfer_proto protoreflect.FileDescriptor

const file_nervus_ipc_v1_transfer_proto_rawDesc = "" +
	"\n" +
	"\x1cnervus/ipc/v1/transfer.proto\x12\rnervus.ipc.v1\x1a\x1anervus/ipc/v1/status.proto\"\x8e\x02\n" +
	"\x0eTransferPolicy\x12>\n" +
	"\tdirection\x18\x01 \x01(\x0e2 .nervus.ipc.v1.TransferDirectionR\tdirection\x12\x1f\n" +
	"\vmax_streams\x18\x02 \x01(\rR\n" +
	"maxStreams\x12(\n" +
	"\x10max_packet_bytes\x18\x03 \x01(\rR\x0emaxPacketBytes\x12/\n" +
	"\x14max_bytes_per_second\x18\x04 \x01(\x04R\x11maxBytesPerSecond\x12@\n" +
	"\rallowed_modes\x18\x05 \x03(\x0e2\x1b.nervus.ipc.v1.TransferModeR\fallowedModes\"\xa5\x02\n" +
	"\x0eTransferHandle\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\x12#\n" +
	"\rattach_ticket\x18\x02 \x01(\fR\fattachTicket\x12/\n" +
	"\x04role\x18\x03 \x01(\x0e2\x1b.nervus.ipc.v1.TransferRoleR\x04role\x12/\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x1b.nervus.ipc.v1.TransferModeR\x04mode\x12;\n" +
	"\x1aexpires_at_monotonic_nanos\x18\x05 \x01(\x04R\x17expiresAtMonotonicNanos\x12.\n" +
	"\x13data_plane_endpoint\x18\x06 \x01(\tR\x11dataPlaneEndpoint\"\x87\x01\n" +
	"\x0eAttachTransfer\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\fR\n" +
	"transferId\x12#\n" +
	"\rattach_ticket\x18\x02 \x01(\fR\fattachTicket\x12/\n" +
	"\x04role\x18\x03 \x01(\x0e2\x1b.nervus.ipc.v1.TransferRoleR\x04role\"\xa3\x01\n" +
	"\x15AttachTransferSuccess\x12/\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1b.nervus.ipc.v1.TransferModeR\x04mode\x12(\n" +
	"\x10max_packet_bytes\x18\x02 \x01(\rR\x0emaxPacketBytes\x12/\n" +
	"\x14max_bytes_per_second\x18\x03 \x01(\x04R\x11maxBytesPerSecond\"\x97\x01\n" +
	"\x14AttachTransferResult\x12@\n" +
	"\asuccess\x18\x01 \x01(\v2$.nervus.ipc.v1.AttachTransferSuccessH\x00R\asuccess\x122\n" +
	"\afailure\x18\x02 \x01(\v2\x16.nervus.ipc.v1.FailureH\x00R\afailureB\t\n" +
	"\aoutcome*\xb3\x01\n" +
	"\x11TransferDirection\x12\"\n" +
	"\x1eTRANSFER_DIRECTION_UNSPECIFIED\x10\x00\x12)\n" +
	"%TRANSFER_DIRECTION_PROVIDER_TO_CALLER\x10\x01\x12)\n" +
	"%TRANSFER_DIRECTION_CALLER_TO_PROVIDER\x10\x02\x12$\n" +
	" TRANSFER_DIRECTION_BIDIRECTIONAL\x10\x03*s\n" +
	"\fTransferMode\x12\x1d\n" +
	"\x19TRANSFER_MODE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTRANSFER_MODE_FRAMED_RELAY\x10\x01\x12$\n" +
	" TRANSFER_MODE_SHARED_MEMORY_RING\x10\x02*}\n" +
	"\fTransferRole\x12\x1d\n" +
	"\x19TRANSFER_ROLE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TRANSFER_ROLE_PRODUCER\x10\x01\x12\x1a\n" +
	"\x16TRANSFER_ROLE_CONSUMER\x10\x02\x12\x16\n" +
	"\x12TRANSFER_ROLE_PEER\x10\x03Bb\n" +
	"\x19io.github.nervusos.ipc.v1B\rTransferProtoP\x01Z4github.com/nervus-os/nervus-ipc/protocol/ipcv1;ipcv1b\x06proto3"

var (
	file_nervus_ipc_v1_transfer_proto_rawDescOnce sync.Once
	file_nervus_ipc_v1_transfer_proto_rawDescData []byte
)

func file_nervus_ipc_v1_transfer_proto_rawDescGZIP() []byte {
	file_nervus_ipc_v1_transfer_proto_rawDescOnce.Do(func() {
		file_nervus_ipc_v1_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nervus_ipc_v1_transfer_proto_rawDesc), len(file_nervus_ipc_v1_transfer_proto_rawDesc)))
	})
	return file_nervus_ipc_v1_transfer_proto_rawDescData
}

var file_nervus_ipc_v1_transfer_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_nervus_ipc_v1_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_nervus_ipc_v1_transfer_proto_goTypes = []any{
	(TransferDirection)(0),        // 0: nervus.ipc.v1.TransferDirection
	(TransferMode)(0),             // 1: nervus.ipc.v1.TransferMode
	(TransferRole)(0),             // 2: nervus.ipc.v1.TransferRole
	(*TransferPolicy)(nil),        // 3: nervus.ipc.v1.TransferPolicy
	(*TransferHandle)(nil),        // 4: nervus.ipc.v1.TransferHandle
	(*AttachTransfer)(nil),        // 5: nervus.ipc.v1.AttachTransfer
	(*AttachTransferSuccess)(nil), // 6: nervus.ipc.v1.AttachTransferSuccess
	(*AttachTransferResult)(nil),  // 7: nervus.ipc.v1.AttachTransferResult
	(*Failure)(nil),               // 8: nervus.ipc.v1.Failure
}
var file_nervus_ipc_v1_transfer_proto_depIdxs = []int32{
	0, // 0: nervus.ipc.v1.TransferPolicy.direction:type_name -> nervus.ipc.v1.TransferDirection
	1, // 1: nervus.ipc.v1.TransferPolicy.allowed_modes:type_name -> nervus.ipc.v1.TransferMode
	2, // 2: nervus.ipc.v1.TransferHandle.role:type_name -> nervus.ipc.v1.TransferRole
	1, // 3: nervus.ipc.v1.TransferHandle.mode:type_name -> nervus.ipc.v1.TransferMode
	2, // 4: nervus.ipc.v1.AttachTransfer.role:type_name -> nervus.ipc.v1.TransferRole
	1, // 5: nervus.ipc.v1.AttachTransferSuccess.mode:type_name -> nervus.ipc.v1.TransferMode
	6, // 6: nervus.ipc.v1.AttachTransferResult.success:type_name -> nervus.ipc.v1.AttachTransferSuccess
	8, // 7: nervus.ipc.v1.AttachTransferResult.failure:type_name -> nervus.ipc.v1.Failure
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_nervus_ipc_v1_transfer_proto_init() }
func file_nervus_ipc_v1_transfer_proto_init() {
	if File_nervus_ipc_v1_transfer_proto != nil {
		return
	}
	file_nervus_ipc_v1_status_proto_init()
	file_nervus_ipc_v1_transfer_proto_msgTypes[4].OneofWrappers = []any{
		(*AttachTransferResult_Success)(nil),
		(*AttachTransferResult_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nervus_ipc_v1_transfer_proto_rawDesc), len(file_nervus_ipc_v1_transfer_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nervus_ipc_v1_transfer_proto_goTypes,
		DependencyIndexes: file_nervus_ipc_v1_transfer_proto_depIdxs,
		EnumInfos:         file_nervus_ipc_v1_transfer_proto_enumTypes,
		MessageInfos:      file_nervus_ipc_v1_transfer_proto_msgTypes,
	}.Build()
	File_nervus_ipc_v1_transfer_proto = out.File
	file_nervus_ipc_v1_transfer_proto_goTypes = nil
	file_nervus_ipc_v1_transfer_proto_depIdxs = nil
}
