// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/basemotion/v1/basemotion.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.iface.basemotion.v1;

public interface StopRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nervus.interface.basemotion.v1.StopRequest)
    com.google.protobuf.MessageOrBuilder {
}
