// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/acme/dog/v1/raw_gait.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.acme.dog.v1;

@kotlin.jvm.JvmName("-initializegetGaitStateRequest")
public inline fun getGaitStateRequest(block: com.acme.dog.v1.GetGaitStateRequestKt.Dsl.() -> kotlin.Unit): com.acme.dog.v1.GetGaitStateRequest =
  com.acme.dog.v1.GetGaitStateRequestKt.Dsl._create(com.acme.dog.v1.GetGaitStateRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.acme.dog.v1.GetGaitStateRequest`
 */
public object GetGaitStateRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.acme.dog.v1.GetGaitStateRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.acme.dog.v1.GetGaitStateRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.acme.dog.v1.GetGaitStateRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.acme.dog.v1.GetGaitStateRequest.copy(block: `com.acme.dog.v1`.GetGaitStateRequestKt.Dsl.() -> kotlin.Unit): com.acme.dog.v1.GetGaitStateRequest =
  `com.acme.dog.v1`.GetGaitStateRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

