// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/acme/dog/v1/raw_gait.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.acme.dog.v1;

@kotlin.jvm.JvmName("-initializerawGaitErrorDetail")
public inline fun rawGaitErrorDetail(block: com.acme.dog.v1.RawGaitErrorDetailKt.Dsl.() -> kotlin.Unit): com.acme.dog.v1.RawGaitErrorDetail =
  com.acme.dog.v1.RawGaitErrorDetailKt.Dsl._create(com.acme.dog.v1.RawGaitErrorDetail.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.acme.dog.v1.RawGaitErrorDetail`
 */
public object RawGaitErrorDetailKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.acme.dog.v1.RawGaitErrorDetail.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.acme.dog.v1.RawGaitErrorDetail.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.acme.dog.v1.RawGaitErrorDetail = _builder.build()

    /**
     * `.com.acme.dog.v1.RawGaitReason reason = 1 [json_name = "reason"];`
     */
    public var reason: com.acme.dog.v1.RawGaitReason
      @JvmName("getReason")
      get() = _builder.reason
      @JvmName("setReason")
      set(value) {
        _builder.reason = value
      }
    public var reasonValue: kotlin.Int
      @JvmName("getReasonValue")
      get() = _builder.reasonValue
      @JvmName("setReasonValue")
      set(value) {
        _builder.reasonValue = value
      }
    /**
     * `.com.acme.dog.v1.RawGaitReason reason = 1 [json_name = "reason"];`
     */
    public fun clearReason() {
      _builder.clearReason()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.acme.dog.v1.RawGaitErrorDetail.copy(block: `com.acme.dog.v1`.RawGaitErrorDetailKt.Dsl.() -> kotlin.Unit): com.acme.dog.v1.RawGaitErrorDetail =
  `com.acme.dog.v1`.RawGaitErrorDetailKt.Dsl._create(this.toBuilder()).apply { block() }._build()

