// OEM 私有接口样例：com.acme.dog.interface.raw_gait@1  [REWRITE-v1 / experimental]
//
// 这是 WP-A4 的**可拓展验收样例**（A4 §5）。它存在的唯一目的是证明一件事：
//
//	一家 OEM（虚构的 Acme）想给自己的机械狗加一个**标准接口里没有的**私有接口
//	——直接下发步态相位参数的 raw_gait——只需要：
//	  ① 在自己的命名空间 com.acme.* 写这一个 .proto，
//	  ② 用 nervus 冻结的 Method Registry 机制（method_registry.proto）挂 method_meta，
//	  ③ 在 Provider Descriptor 里声明这个接口 + 它的自定义权限。
//	**nervud 一行 Go 都不用改**，装上这个签名包后 App 就能 Resolve/调用它。
//	这就是 `00` 第 3 节「加接口不改内核」的活证据。
//
// 注意本文件**不在** nervus.* 命名空间：它是 OEM 私有的，proto package、接口 ID、
// 自定义权限 ID、资源类型全部落在 com.acme.dog.* 下（`00` 红线：命名空间隔离，
// Custom Permission 绑定签名）。它**只** import nervus 的通用机制文件，不反向
// 依赖任何 nervus 接口——机制是共享的，语义是私有的。
//
// [REWRITE-v1] experimental：字段/method_id 冻结前可破坏性调整。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: com/acme/dog/v1/raw_gait.proto

// OEM 私有命名空间。与标准接口 nervus.* 完全隔离。

package dogv1

import (
	_ "github.com/nervus-os/nervus-ipc/go/protocol/ipcv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RawGaitMethod 是 raw_gait 接口的方法目录。每个枚举值挂 (nervus.ipc.v1.method_meta)。
// nervud/SDK/Agent 从生成的 EnumValueOptions 抽取这些 MethodMeta，得到该 OEM 接口
// 的 method 级权限/风险/确认要求——**抽取逻辑与标准接口完全一样，内核不认得
// "acme" 这个名字**。约定：枚举值编号 == method_id。
type RawGaitMethod int32

const (
	RawGaitMethod_RAW_GAIT_METHOD_UNSPECIFIED RawGaitMethod = 0
	// 只读：读取当前步态相位与支持的步态集合。无副作用、无需 lease、无需确认。
	RawGaitMethod_RAW_GAIT_METHOD_GET_GAIT_STATE RawGaitMethod = 1
	// 物理控制：直接下发原始步态相位参数（越过标准 BaseMotion 的速度抽象）。
	// 这是危险动作：驱动执行器、需 OEM 自定义权限、需持 lease、Agent 调用需系统确认框。
	// required_permission 指向本包命名空间下的自定义权限（在 Descriptor 里定义并绑签名）。
	RawGaitMethod_RAW_GAIT_METHOD_SET_RAW_GAIT RawGaitMethod = 2
)

// Enum value maps for RawGaitMethod.
var (
	RawGaitMethod_name = map[int32]string{
		0: "RAW_GAIT_METHOD_UNSPECIFIED",
		1: "RAW_GAIT_METHOD_GET_GAIT_STATE",
		2: "RAW_GAIT_METHOD_SET_RAW_GAIT",
	}
	RawGaitMethod_value = map[string]int32{
		"RAW_GAIT_METHOD_UNSPECIFIED":    0,
		"RAW_GAIT_METHOD_GET_GAIT_STATE": 1,
		"RAW_GAIT_METHOD_SET_RAW_GAIT":   2,
	}
)

func (x RawGaitMethod) Enum() *RawGaitMethod {
	p := new(RawGaitMethod)
	*p = x
	return p
}

func (x RawGaitMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RawGaitMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_com_acme_dog_v1_raw_gait_proto_enumTypes[0].Descriptor()
}

func (RawGaitMethod) Type() protoreflect.EnumType {
	return &file_com_acme_dog_v1_raw_gait_proto_enumTypes[0]
}

func (x RawGaitMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RawGaitMethod.Descriptor instead.
func (RawGaitMethod) EnumDescriptor() ([]byte, []int) {
	return file_com_acme_dog_v1_raw_gait_proto_rawDescGZIP(), []int{0}
}

// 支持的步态类型（OEM 私有语义，标准接口里不存在）。
type GaitType int32

const (
	GaitType_GAIT_TYPE_UNSPECIFIED GaitType = 0
	GaitType_GAIT_TYPE_TROT        GaitType = 1 // 对角小跑
	GaitType_GAIT_TYPE_WALK        GaitType = 2 // 慢走
	GaitType_GAIT_TYPE_BOUND       GaitType = 3 // 前后腿同步跳跃
)

// Enum value maps for GaitType.
var (
	GaitType_name = map[int32]string{
		0: "GAIT_TYPE_UNSPECIFIED",
		1: "GAIT_TYPE_TROT",
		2: "GAIT_TYPE_WALK",
		3: "GAIT_TYPE_BOUND",
	}
	GaitType_value = map[string]int32{
		"GAIT_TYPE_UNSPECIFIED": 0,
		"GAIT_TYPE_TROT":        1,
		"GAIT_TYPE_WALK":        2,
		"GAIT_TYPE_BOUND":       3,
	}
)

func (x GaitType) Enum() *GaitType {
	p := new(GaitType)
	*p = x
	return p
}

func (x GaitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GaitType) Descriptor() protoreflect.EnumDescriptor {
	return file_com_acme_dog_v1_raw_gait_proto_enumTypes[1].Descriptor()
}

func (GaitType) Type() protoreflect.EnumType {
	return &file_com_acme_dog_v1_raw_gait_proto_enumTypes[1]
}

func (x GaitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GaitType.Descriptor instead.
func (GaitType) EnumDescriptor() ([]byte, []int) {
	return file_com_acme_dog_v1_raw_gait_proto_rawDescGZIP(), []int{1}
}

// 错误 detail（NRCP §19，位置 B）。OEM 私有细因走自己的 typed detail，
// 不污染通用 StatusCode。
type RawGaitReason int32

const (
	RawGaitReason_RAW_GAIT_REASON_UNSPECIFIED        RawGaitReason = 0
	RawGaitReason_RAW_GAIT_REASON_SAFETY_LATCHED     RawGaitReason = 1
	RawGaitReason_RAW_GAIT_REASON_CONTROL_NOT_HELD   RawGaitReason = 2
	RawGaitReason_RAW_GAIT_REASON_UNSUPPORTED_GAIT   RawGaitReason = 3
	RawGaitReason_RAW_GAIT_REASON_PHASE_OUT_OF_RANGE RawGaitReason = 4
)

// Enum value maps for RawGaitReason.
var (
	RawGaitReason_name = map[int32]string{
		0: "RAW_GAIT_REASON_UNSPECIFIED",
		1: "RAW_GAIT_REASON_SAFETY_LATCHED",
		2: "RAW_GAIT_REASON_CONTROL_NOT_HELD",
		3: "RAW_GAIT_REASON_UNSUPPORTED_GAIT",
		4: "RAW_GAIT_REASON_PHASE_OUT_OF_RANGE",
	}
	RawGaitReason_value = map[string]int32{
		"RAW_GAIT_REASON_UNSPECIFIED":        0,
		"RAW_GAIT_REASON_SAFETY_LATCHED":     1,
		"RAW_GAIT_REASON_CONTROL_NOT_HELD":   2,
		"RAW_GAIT_REASON_UNSUPPORTED_GAIT":   3,
		"RAW_GAIT_REASON_PHASE_OUT_OF_RANGE": 4,
	}
)

func (x RawGaitReason) Enum() *RawGaitReason {
	p := new(RawGaitReason)
	*p = x
	return p
}

func (x RawGaitReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RawGaitReason) Descriptor() protoreflect.EnumDescriptor {
	return file_com_acme_dog_v1_raw_gait_proto_enumTypes[2].Descriptor()
}

func (RawGaitReason) Type() protoreflect.EnumType {
	return &file_com_acme_dog_v1_raw_gait_proto_enumTypes[2]
}

func (x RawGaitReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RawGaitReason.Descriptor instead.
func (RawGaitReason) EnumDescriptor() ([]byte, []int) {
	return file_com_acme_dog_v1_raw_gait_proto_rawDescGZIP(), []int{2}
}

type GetGaitStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGaitStateRequest) Reset() {
	*x = GetGaitStateRequest{}
	mi := &file_com_acme_dog_v1_raw_gait_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGaitStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGaitStateRequest) ProtoMessage() {}

func (x *GetGaitStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_dog_v1_raw_gait_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGaitStateRequest.ProtoReflect.Descriptor instead.
func (*GetGaitStateRequest) Descriptor() ([]byte, []int) {
	return file_com_acme_dog_v1_raw_gait_proto_rawDescGZIP(), []int{0}
}

type GaitState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActiveGait     GaitType               `protobuf:"varint,1,opt,name=active_gait,json=activeGait,proto3,enum=com.acme.dog.v1.GaitType" json:"active_gait,omitempty"`
	Phase          float64                `protobuf:"fixed64,2,opt,name=phase,proto3" json:"phase,omitempty"` // 当前相位，弧度 rad，[0, 2π)
	SupportedGaits []GaitType             `protobuf:"varint,3,rep,packed,name=supported_gaits,json=supportedGaits,proto3,enum=com.acme.dog.v1.GaitType" json:"supported_gaits,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GaitState) Reset() {
	*x = GaitState{}
	mi := &file_com_acme_dog_v1_raw_gait_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GaitState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GaitState) ProtoMessage() {}

func (x *GaitState) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_dog_v1_raw_gait_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GaitState.ProtoReflect.Descriptor instead.
func (*GaitState) Descriptor() ([]byte, []int) {
	return file_com_acme_dog_v1_raw_gait_proto_rawDescGZIP(), []int{1}
}

func (x *GaitState) GetActiveGait() GaitType {
	if x != nil {
		return x.ActiveGait
	}
	return GaitType_GAIT_TYPE_UNSPECIFIED
}

func (x *GaitState) GetPhase() float64 {
	if x != nil {
		return x.Phase
	}
	return 0
}

func (x *GaitState) GetSupportedGaits() []GaitType {
	if x != nil {
		return x.SupportedGaits
	}
	return nil
}

// 原始步态下发：绕过标准速度抽象，直接给相位偏置与步频。这类"裸控制"正是
// OEM 才会暴露、标准接口刻意不提供的东西——样例的意义就在于它非标。
type SetRawGaitRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Gait              GaitType               `protobuf:"varint,1,opt,name=gait,proto3,enum=com.acme.dog.v1.GaitType" json:"gait,omitempty"`
	StrideFrequencyHz float64                `protobuf:"fixed64,2,opt,name=stride_frequency_hz,json=strideFrequencyHz,proto3" json:"stride_frequency_hz,omitempty"` // 步频，Hz
	PhaseOffsetRad    float64                `protobuf:"fixed64,3,opt,name=phase_offset_rad,json=phaseOffsetRad,proto3" json:"phase_offset_rad,omitempty"`          // 相位偏置，rad
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetRawGaitRequest) Reset() {
	*x = SetRawGaitRequest{}
	mi := &file_com_acme_dog_v1_raw_gait_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRawGaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRawGaitRequest) ProtoMessage() {}

func (x *SetRawGaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_dog_v1_raw_gait_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRawGaitRequest.ProtoReflect.Descriptor instead.
func (*SetRawGaitRequest) Descriptor() ([]byte, []int) {
	return file_com_acme_dog_v1_raw_gait_proto_rawDescGZIP(), []int{2}
}

func (x *SetRawGaitRequest) GetGait() GaitType {
	if x != nil {
		return x.Gait
	}
	return GaitType_GAIT_TYPE_UNSPECIFIED
}

func (x *SetRawGaitRequest) GetStrideFrequencyHz() float64 {
	if x != nil {
		return x.StrideFrequencyHz
	}
	return 0
}

func (x *SetRawGaitRequest) GetPhaseOffsetRad() float64 {
	if x != nil {
		return x.PhaseOffsetRad
	}
	return 0
}

type SetRawGaitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRawGaitResponse) Reset() {
	*x = SetRawGaitResponse{}
	mi := &file_com_acme_dog_v1_raw_gait_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRawGaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRawGaitResponse) ProtoMessage() {}

func (x *SetRawGaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_dog_v1_raw_gait_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRawGaitResponse.ProtoReflect.Descriptor instead.
func (*SetRawGaitResponse) Descriptor() ([]byte, []int) {
	return file_com_acme_dog_v1_raw_gait_proto_rawDescGZIP(), []int{3}
}

type RawGaitErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        RawGaitReason          `protobuf:"varint,1,opt,name=reason,proto3,enum=com.acme.dog.v1.RawGaitReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawGaitErrorDetail) Reset() {
	*x = RawGaitErrorDetail{}
	mi := &file_com_acme_dog_v1_raw_gait_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawGaitErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawGaitErrorDetail) ProtoMessage() {}

func (x *RawGaitErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_com_acme_dog_v1_raw_gait_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawGaitErrorDetail.ProtoReflect.Descriptor instead.
func (*RawGaitErrorDetail) Descriptor() ([]byte, []int) {
	return file_com_acme_dog_v1_raw_gait_proto_rawDescGZIP(), []int{4}
}

func (x *RawGaitErrorDetail) GetReason() RawGaitReason {
	if x != nil {
		return x.Reason
	}
	return RawGaitReason_RAW_GAIT_REASON_UNSPECIFIED
}

var File_com_acme_dog_v1_raw_gait_proto protoreflect.FileDescriptor

const file_com_acme_dog_v1_raw_gait_proto_rawDesc = "" +
	"\n" +
	"\x1ecom/acme/dog/v1/raw_gait.proto\x12\x0fcom.acme.dog.v1\x1a#nervus/ipc/v1/method_registry.proto\"\x15\n" +
	"\x13GetGaitStateRequest\"\xa1\x01\n" +
	"\tGaitState\x12:\n" +
	"\vactive_gait\x18\x01 \x01(\x0e2\x19.com.acme.dog.v1.GaitTypeR\n" +
	"activeGait\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\x01R\x05phase\x12B\n" +
	"\x0fsupported_gaits\x18\x03 \x03(\x0e2\x19.com.acme.dog.v1.GaitTypeR\x0esupportedGaits\"\x9c\x01\n" +
	"\x11SetRawGaitRequest\x12-\n" +
	"\x04gait\x18\x01 \x01(\x0e2\x19.com.acme.dog.v1.GaitTypeR\x04gait\x12.\n" +
	"\x13stride_frequency_hz\x18\x02 \x01(\x01R\x11strideFrequencyHz\x12(\n" +
	"\x10phase_offset_rad\x18\x03 \x01(\x01R\x0ephaseOffsetRad\"\x14\n" +
	"\x12SetRawGaitResponse\"L\n" +
	"\x12RawGaitErrorDetail\x126\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x1e.com.acme.dog.v1.RawGaitReasonR\x06reason*\xbc\x02\n" +
	"\rRawGaitMethod\x12\x1f\n" +
	"\x1bRAW_GAIT_METHOD_UNSPECIFIED\x10\x00\x12n\n" +
	"\x1eRAW_GAIT_METHOD_GET_GAIT_STATE\x10\x01\x1aJ\x8a\xa6\x1dF\b\x01\x18\x01:#com.acme.dog.v1.GetGaitStateRequestB\x19com.acme.dog.v1.GaitStateH\x01\x12\x99\x01\n" +
	"\x1cRAW_GAIT_METHOD_SET_RAW_GAIT\x10\x02\x1aw\x8a\xa6\x1ds\b\x02\x12 com.acme.dog.permission.raw_gait\x18\x03 \x010\x01:!com.acme.dog.v1.SetRawGaitRequestB\"com.acme.dog.v1.SetRawGaitResponseP\x01*b\n" +
	"\bGaitType\x12\x19\n" +
	"\x15GAIT_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eGAIT_TYPE_TROT\x10\x01\x12\x12\n" +
	"\x0eGAIT_TYPE_WALK\x10\x02\x12\x13\n" +
	"\x0fGAIT_TYPE_BOUND\x10\x03*\xc8\x01\n" +
	"\rRawGaitReason\x12\x1f\n" +
	"\x1bRAW_GAIT_REASON_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eRAW_GAIT_REASON_SAFETY_LATCHED\x10\x01\x12$\n" +
	" RAW_GAIT_REASON_CONTROL_NOT_HELD\x10\x02\x12$\n" +
	" RAW_GAIT_REASON_UNSUPPORTED_GAIT\x10\x03\x12&\n" +
	"\"RAW_GAIT_REASON_PHASE_OUT_OF_RANGE\x10\x04Bd\n" +
	"\x0fcom.acme.dog.v1B\fRawGaitProtoP\x01ZAgithub.com/nervus-os/nervus-ipc/go/protocol/oem/acme/dog/v1;dogv1b\x06proto3"

var (
	file_com_acme_dog_v1_raw_gait_proto_rawDescOnce sync.Once
	file_com_acme_dog_v1_raw_gait_proto_rawDescData []byte
)

func file_com_acme_dog_v1_raw_gait_proto_rawDescGZIP() []byte {
	file_com_acme_dog_v1_raw_gait_proto_rawDescOnce.Do(func() {
		file_com_acme_dog_v1_raw_gait_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_acme_dog_v1_raw_gait_proto_rawDesc), len(file_com_acme_dog_v1_raw_gait_proto_rawDesc)))
	})
	return file_com_acme_dog_v1_raw_gait_proto_rawDescData
}

var file_com_acme_dog_v1_raw_gait_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_com_acme_dog_v1_raw_gait_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_com_acme_dog_v1_raw_gait_proto_goTypes = []any{
	(RawGaitMethod)(0),          // 0: com.acme.dog.v1.RawGaitMethod
	(GaitType)(0),               // 1: com.acme.dog.v1.GaitType
	(RawGaitReason)(0),          // 2: com.acme.dog.v1.RawGaitReason
	(*GetGaitStateRequest)(nil), // 3: com.acme.dog.v1.GetGaitStateRequest
	(*GaitState)(nil),           // 4: com.acme.dog.v1.GaitState
	(*SetRawGaitRequest)(nil),   // 5: com.acme.dog.v1.SetRawGaitRequest
	(*SetRawGaitResponse)(nil),  // 6: com.acme.dog.v1.SetRawGaitResponse
	(*RawGaitErrorDetail)(nil),  // 7: com.acme.dog.v1.RawGaitErrorDetail
}
var file_com_acme_dog_v1_raw_gait_proto_depIdxs = []int32{
	1, // 0: com.acme.dog.v1.GaitState.active_gait:type_name -> com.acme.dog.v1.GaitType
	1, // 1: com.acme.dog.v1.GaitState.supported_gaits:type_name -> com.acme.dog.v1.GaitType
	1, // 2: com.acme.dog.v1.SetRawGaitRequest.gait:type_name -> com.acme.dog.v1.GaitType
	2, // 3: com.acme.dog.v1.RawGaitErrorDetail.reason:type_name -> com.acme.dog.v1.RawGaitReason
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_com_acme_dog_v1_raw_gait_proto_init() }
func file_com_acme_dog_v1_raw_gait_proto_init() {
	if File_com_acme_dog_v1_raw_gait_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_acme_dog_v1_raw_gait_proto_rawDesc), len(file_com_acme_dog_v1_raw_gait_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_acme_dog_v1_raw_gait_proto_goTypes,
		DependencyIndexes: file_com_acme_dog_v1_raw_gait_proto_depIdxs,
		EnumInfos:         file_com_acme_dog_v1_raw_gait_proto_enumTypes,
		MessageInfos:      file_com_acme_dog_v1_raw_gait_proto_msgTypes,
	}.Build()
	File_com_acme_dog_v1_raw_gait_proto = out.File
	file_com_acme_dog_v1_raw_gait_proto_goTypes = nil
	file_com_acme_dog_v1_raw_gait_proto_depIdxs = nil
}
