// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/ipc/v1/envelope.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.github.nervusos.ipc.v1;

@kotlin.jvm.JvmName("-initializecallerContext")
public inline fun callerContext(block: io.github.nervusos.ipc.v1.CallerContextKt.Dsl.() -> kotlin.Unit): io.github.nervusos.ipc.v1.CallerContext =
  io.github.nervusos.ipc.v1.CallerContextKt.Dsl._create(io.github.nervusos.ipc.v1.CallerContext.newBuilder()).apply { block() }._build()
/**
 * ```
 * CallerContext 是 ConnectionContext 中可以外传的那一部分（§10.2）。
 *
 * 【internal_connection_id 永不出现在这里】——它不离开 nervud。
 * 普通 Request 中也不得出现调用者自填的可信身份字段：权限永远由 nervud 按
 * 连接上下文执行，不按 payload 里的 source:"system" 或包名字符串执行。
 * ```
 *
 * Protobuf type `nervus.ipc.v1.CallerContext`
 */
public object CallerContextKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.github.nervusos.ipc.v1.CallerContext.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: io.github.nervusos.ipc.v1.CallerContext.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): io.github.nervusos.ipc.v1.CallerContext = _builder.build()

    /**
     * `string package_id = 1 [json_name = "packageId"];`
     */
    public var packageId: kotlin.String
      @JvmName("getPackageId")
      get() = _builder.packageId
      @JvmName("setPackageId")
      set(value) {
        _builder.packageId = value
      }
    /**
     * `string package_id = 1 [json_name = "packageId"];`
     */
    public fun clearPackageId() {
      _builder.clearPackageId()
    }

    /**
     * `string component_id = 2 [json_name = "componentId"];`
     */
    public var componentId: kotlin.String
      @JvmName("getComponentId")
      get() = _builder.componentId
      @JvmName("setComponentId")
      set(value) {
        _builder.componentId = value
      }
    /**
     * `string component_id = 2 [json_name = "componentId"];`
     */
    public fun clearComponentId() {
      _builder.clearComponentId()
    }

    /**
     * ```
     * 来自 Linux 内核的 SO_PEERCRED，不来自任何 Envelope 字段。
     * ```
     *
     * `uint32 uid = 3 [json_name = "uid"];`
     */
    public var uid: kotlin.Int
      @JvmName("getUid")
      get() = _builder.uid
      @JvmName("setUid")
      set(value) {
        _builder.uid = value
      }
    /**
     * ```
     * 来自 Linux 内核的 SO_PEERCRED，不来自任何 Envelope 字段。
     * ```
     *
     * `uint32 uid = 3 [json_name = "uid"];`
     */
    public fun clearUid() {
      _builder.clearUid()
    }

    /**
     * `uint32 gid = 4 [json_name = "gid"];`
     */
    public var gid: kotlin.Int
      @JvmName("getGid")
      get() = _builder.gid
      @JvmName("setGid")
      set(value) {
        _builder.gid = value
      }
    /**
     * `uint32 gid = 4 [json_name = "gid"];`
     */
    public fun clearGid() {
      _builder.clearGid()
    }

    /**
     * ```
     * PID 会随进程退出被回收，仅供诊断与日志关联，【不得】用于事后反查 /proc
     * 并信任结果。
     * ```
     *
     * `int32 pid = 5 [json_name = "pid"];`
     */
    public var pid: kotlin.Int
      @JvmName("getPid")
      get() = _builder.pid
      @JvmName("setPid")
      set(value) {
        _builder.pid = value
      }
    /**
     * ```
     * PID 会随进程退出被回收，仅供诊断与日志关联，【不得】用于事后反查 /proc
     * 并信任结果。
     * ```
     *
     * `int32 pid = 5 [json_name = "pid"];`
     */
    public fun clearPid() {
      _builder.clearPid()
    }

    /**
     * `.nervus.ipc.v1.TrustProfile trust_profile = 6 [json_name = "trustProfile"];`
     */
    public var trustProfile: io.github.nervusos.ipc.v1.TrustProfile
      @JvmName("getTrustProfile")
      get() = _builder.trustProfile
      @JvmName("setTrustProfile")
      set(value) {
        _builder.trustProfile = value
      }
    public var trustProfileValue: kotlin.Int
      @JvmName("getTrustProfileValue")
      get() = _builder.trustProfileValue
      @JvmName("setTrustProfileValue")
      set(value) {
        _builder.trustProfileValue = value
      }
    /**
     * `.nervus.ipc.v1.TrustProfile trust_profile = 6 [json_name = "trustProfile"];`
     */
    public fun clearTrustProfile() {
      _builder.clearTrustProfile()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class GrantedPermissionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 本次调用相关的、已授予的权限。是 nervud 裁决结果的【只读投影】，
     * 供 Service 做二次 fail-closed 复核，不是让 Service 重新裁决。
     * ```
     *
     * `repeated string granted_permissions = 7 [json_name = "grantedPermissions"];`
     * @return A list containing the grantedPermissions.
     */
    public val grantedPermissions: com.google.protobuf.kotlin.DslList<kotlin.String, GrantedPermissionsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.grantedPermissionsList
      )
    /**
     * ```
     * 本次调用相关的、已授予的权限。是 nervud 裁决结果的【只读投影】，
     * 供 Service 做二次 fail-closed 复核，不是让 Service 重新裁决。
     * ```
     *
     * `repeated string granted_permissions = 7 [json_name = "grantedPermissions"];`
     * @param value The grantedPermissions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addGrantedPermissions")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, GrantedPermissionsProxy>.add(value: kotlin.String) {
      _builder.addGrantedPermissions(value)
    }
    /**
     * ```
     * 本次调用相关的、已授予的权限。是 nervud 裁决结果的【只读投影】，
     * 供 Service 做二次 fail-closed 复核，不是让 Service 重新裁决。
     * ```
     *
     * `repeated string granted_permissions = 7 [json_name = "grantedPermissions"];`
     * @param value The grantedPermissions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignGrantedPermissions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, GrantedPermissionsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * 本次调用相关的、已授予的权限。是 nervud 裁决结果的【只读投影】，
     * 供 Service 做二次 fail-closed 复核，不是让 Service 重新裁决。
     * ```
     *
     * `repeated string granted_permissions = 7 [json_name = "grantedPermissions"];`
     * @param values The grantedPermissions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllGrantedPermissions")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, GrantedPermissionsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllGrantedPermissions(values)
    }
    /**
     * ```
     * 本次调用相关的、已授予的权限。是 nervud 裁决结果的【只读投影】，
     * 供 Service 做二次 fail-closed 复核，不是让 Service 重新裁决。
     * ```
     *
     * `repeated string granted_permissions = 7 [json_name = "grantedPermissions"];`
     * @param values The grantedPermissions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllGrantedPermissions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, GrantedPermissionsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * 本次调用相关的、已授予的权限。是 nervud 裁决结果的【只读投影】，
     * 供 Service 做二次 fail-closed 复核，不是让 Service 重新裁决。
     * ```
     *
     * `repeated string granted_permissions = 7 [json_name = "grantedPermissions"];`
     * @param index The index to set the value at.
     * @param value The grantedPermissions to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setGrantedPermissions")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, GrantedPermissionsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setGrantedPermissions(index, value)
    }/**
     * ```
     * 本次调用相关的、已授予的权限。是 nervud 裁决结果的【只读投影】，
     * 供 Service 做二次 fail-closed 复核，不是让 Service 重新裁决。
     * ```
     *
     * `repeated string granted_permissions = 7 [json_name = "grantedPermissions"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearGrantedPermissions")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, GrantedPermissionsProxy>.clear() {
      _builder.clearGrantedPermissions()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun io.github.nervusos.ipc.v1.CallerContext.copy(block: `io.github.nervusos.ipc.v1`.CallerContextKt.Dsl.() -> kotlin.Unit): io.github.nervusos.ipc.v1.CallerContext =
  `io.github.nervusos.ipc.v1`.CallerContextKt.Dsl._create(this.toBuilder()).apply { block() }._build()

