// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/ipc/v1/status.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.github.nervusos.ipc.v1;

