// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/ipc/v1/envelope.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.ipc.v1;

/**
 * <pre>
 * AcquireControl 申请对某个 Resource 的控制租约。
 * </pre>
 *
 * Protobuf type {@code nervus.ipc.v1.AcquireControl}
 */
public final class AcquireControl extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:nervus.ipc.v1.AcquireControl)
    AcquireControlOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AcquireControl.class.getName());
  }
  // Use AcquireControl.newBuilder() to construct.
  private AcquireControl(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AcquireControl() {
    controllerClass_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.nervusos.ipc.v1.EnvelopeProto.internal_static_nervus_ipc_v1_AcquireControl_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.nervusos.ipc.v1.EnvelopeProto.internal_static_nervus_ipc_v1_AcquireControl_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.nervusos.ipc.v1.AcquireControl.class, io.github.nervusos.ipc.v1.AcquireControl.Builder.class);
  }

  private int bitField0_;
  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  private long requestId_ = 0L;
  /**
   * <pre>
   * 本连接作用域的请求 ID，语义同 Request.request_id：0 永久保留，首个为 1，
   * 不回绕。匹配键是 (连接, request_id)。
   * </pre>
   *
   * <code>uint64 request_id = 1 [json_name = "requestId"];</code>
   * @return The requestId.
   */
  @java.lang.Override
  public long getRequestId() {
    return requestId_;
  }

  public static final int CONTROLLER_CLASS_FIELD_NUMBER = 2;
  private int controllerClass_ = 0;
  /**
   * <pre>
   * 申请的控制主体类别，必须是 HUMAN 或 AI（见 ControllerClass：无 NONE）。
   * </pre>
   *
   * <code>.nervus.ipc.v1.ControllerClass controller_class = 2 [json_name = "controllerClass"];</code>
   * @return The enum numeric value on the wire for controllerClass.
   */
  @java.lang.Override public int getControllerClassValue() {
    return controllerClass_;
  }
  /**
   * <pre>
   * 申请的控制主体类别，必须是 HUMAN 或 AI（见 ControllerClass：无 NONE）。
   * </pre>
   *
   * <code>.nervus.ipc.v1.ControllerClass controller_class = 2 [json_name = "controllerClass"];</code>
   * @return The controllerClass.
   */
  @java.lang.Override public io.github.nervusos.ipc.v1.ControllerClass getControllerClass() {
    io.github.nervusos.ipc.v1.ControllerClass result = io.github.nervusos.ipc.v1.ControllerClass.forNumber(controllerClass_);
    return result == null ? io.github.nervusos.ipc.v1.ControllerClass.UNRECOGNIZED : result;
  }

  public static final int RESOURCE_FIELD_NUMBER = 3;
  private io.github.nervusos.ipc.v1.ResourceSelector resource_;
  /**
   * <pre>
   * 申请控制的 Resource。ControlLease 天生 Resource-scoped（§10.2）。
   *
   * 【必须显式给出】：v1 曾允许留空并隐式取底盘，那条默认已随 v2 移除。
   * 只有 access_mode 为 EXCLUSIVE_CONTROL 的资源能被租约——声明为 SHARED_OBSERVE
   * 的传感器可被路由，但永远拿不到控制权。
   *
   * 提交 OEM 的 Package/Component/Provider 名一律拒绝（同 ResolveEndpoint.selector）。
   * </pre>
   *
   * <code>.nervus.ipc.v1.ResourceSelector resource = 3 [json_name = "resource"];</code>
   * @return Whether the resource field is set.
   */
  @java.lang.Override
  public boolean hasResource() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 申请控制的 Resource。ControlLease 天生 Resource-scoped（§10.2）。
   *
   * 【必须显式给出】：v1 曾允许留空并隐式取底盘，那条默认已随 v2 移除。
   * 只有 access_mode 为 EXCLUSIVE_CONTROL 的资源能被租约——声明为 SHARED_OBSERVE
   * 的传感器可被路由，但永远拿不到控制权。
   *
   * 提交 OEM 的 Package/Component/Provider 名一律拒绝（同 ResolveEndpoint.selector）。
   * </pre>
   *
   * <code>.nervus.ipc.v1.ResourceSelector resource = 3 [json_name = "resource"];</code>
   * @return The resource.
   */
  @java.lang.Override
  public io.github.nervusos.ipc.v1.ResourceSelector getResource() {
    return resource_ == null ? io.github.nervusos.ipc.v1.ResourceSelector.getDefaultInstance() : resource_;
  }
  /**
   * <pre>
   * 申请控制的 Resource。ControlLease 天生 Resource-scoped（§10.2）。
   *
   * 【必须显式给出】：v1 曾允许留空并隐式取底盘，那条默认已随 v2 移除。
   * 只有 access_mode 为 EXCLUSIVE_CONTROL 的资源能被租约——声明为 SHARED_OBSERVE
   * 的传感器可被路由，但永远拿不到控制权。
   *
   * 提交 OEM 的 Package/Component/Provider 名一律拒绝（同 ResolveEndpoint.selector）。
   * </pre>
   *
   * <code>.nervus.ipc.v1.ResourceSelector resource = 3 [json_name = "resource"];</code>
   */
  @java.lang.Override
  public io.github.nervusos.ipc.v1.ResourceSelectorOrBuilder getResourceOrBuilder() {
    return resource_ == null ? io.github.nervusos.ipc.v1.ResourceSelector.getDefaultInstance() : resource_;
  }

  public static final int REQUESTED_DEADLINE_NANOS_FIELD_NUMBER = 4;
  private long requestedDeadlineNanos_ = 0L;
  /**
   * <pre>
   * 调用者期望的租约时效（纳秒）。这是【期望值】不是承诺：nervud 可按 Policy
   * 收紧（远程 HUMAN lease 尤其短）。0 表示采用系统默认，【不表示】无限。
   * </pre>
   *
   * <code>int64 requested_deadline_nanos = 4 [json_name = "requestedDeadlineNanos"];</code>
   * @return The requestedDeadlineNanos.
   */
  @java.lang.Override
  public long getRequestedDeadlineNanos() {
    return requestedDeadlineNanos_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestId_ != 0L) {
      output.writeUInt64(1, requestId_);
    }
    if (controllerClass_ != io.github.nervusos.ipc.v1.ControllerClass.CONTROLLER_CLASS_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, controllerClass_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getResource());
    }
    if (requestedDeadlineNanos_ != 0L) {
      output.writeInt64(4, requestedDeadlineNanos_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, requestId_);
    }
    if (controllerClass_ != io.github.nervusos.ipc.v1.ControllerClass.CONTROLLER_CLASS_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, controllerClass_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getResource());
    }
    if (requestedDeadlineNanos_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, requestedDeadlineNanos_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.nervusos.ipc.v1.AcquireControl)) {
      return super.equals(obj);
    }
    io.github.nervusos.ipc.v1.AcquireControl other = (io.github.nervusos.ipc.v1.AcquireControl) obj;

    if (getRequestId()
        != other.getRequestId()) return false;
    if (controllerClass_ != other.controllerClass_) return false;
    if (hasResource() != other.hasResource()) return false;
    if (hasResource()) {
      if (!getResource()
          .equals(other.getResource())) return false;
    }
    if (getRequestedDeadlineNanos()
        != other.getRequestedDeadlineNanos()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRequestId());
    hash = (37 * hash) + CONTROLLER_CLASS_FIELD_NUMBER;
    hash = (53 * hash) + controllerClass_;
    if (hasResource()) {
      hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getResource().hashCode();
    }
    hash = (37 * hash) + REQUESTED_DEADLINE_NANOS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRequestedDeadlineNanos());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.nervusos.ipc.v1.AcquireControl parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.ipc.v1.AcquireControl parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.ipc.v1.AcquireControl parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.ipc.v1.AcquireControl parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.ipc.v1.AcquireControl parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.ipc.v1.AcquireControl parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.ipc.v1.AcquireControl parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.nervusos.ipc.v1.AcquireControl parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.nervusos.ipc.v1.AcquireControl parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.nervusos.ipc.v1.AcquireControl parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.nervusos.ipc.v1.AcquireControl parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.nervusos.ipc.v1.AcquireControl parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.nervusos.ipc.v1.AcquireControl prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * AcquireControl 申请对某个 Resource 的控制租约。
   * </pre>
   *
   * Protobuf type {@code nervus.ipc.v1.AcquireControl}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nervus.ipc.v1.AcquireControl)
      io.github.nervusos.ipc.v1.AcquireControlOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.nervusos.ipc.v1.EnvelopeProto.internal_static_nervus_ipc_v1_AcquireControl_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.nervusos.ipc.v1.EnvelopeProto.internal_static_nervus_ipc_v1_AcquireControl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.nervusos.ipc.v1.AcquireControl.class, io.github.nervusos.ipc.v1.AcquireControl.Builder.class);
    }

    // Construct using io.github.nervusos.ipc.v1.AcquireControl.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getResourceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      requestId_ = 0L;
      controllerClass_ = 0;
      resource_ = null;
      if (resourceBuilder_ != null) {
        resourceBuilder_.dispose();
        resourceBuilder_ = null;
      }
      requestedDeadlineNanos_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.nervusos.ipc.v1.EnvelopeProto.internal_static_nervus_ipc_v1_AcquireControl_descriptor;
    }

    @java.lang.Override
    public io.github.nervusos.ipc.v1.AcquireControl getDefaultInstanceForType() {
      return io.github.nervusos.ipc.v1.AcquireControl.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.nervusos.ipc.v1.AcquireControl build() {
      io.github.nervusos.ipc.v1.AcquireControl result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.nervusos.ipc.v1.AcquireControl buildPartial() {
      io.github.nervusos.ipc.v1.AcquireControl result = new io.github.nervusos.ipc.v1.AcquireControl(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.nervusos.ipc.v1.AcquireControl result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.requestId_ = requestId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.controllerClass_ = controllerClass_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.resource_ = resourceBuilder_ == null
            ? resource_
            : resourceBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.requestedDeadlineNanos_ = requestedDeadlineNanos_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.nervusos.ipc.v1.AcquireControl) {
        return mergeFrom((io.github.nervusos.ipc.v1.AcquireControl)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.nervusos.ipc.v1.AcquireControl other) {
      if (other == io.github.nervusos.ipc.v1.AcquireControl.getDefaultInstance()) return this;
      if (other.getRequestId() != 0L) {
        setRequestId(other.getRequestId());
      }
      if (other.controllerClass_ != 0) {
        setControllerClassValue(other.getControllerClassValue());
      }
      if (other.hasResource()) {
        mergeResource(other.getResource());
      }
      if (other.getRequestedDeadlineNanos() != 0L) {
        setRequestedDeadlineNanos(other.getRequestedDeadlineNanos());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              requestId_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              controllerClass_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getResourceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              requestedDeadlineNanos_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long requestId_ ;
    /**
     * <pre>
     * 本连接作用域的请求 ID，语义同 Request.request_id：0 永久保留，首个为 1，
     * 不回绕。匹配键是 (连接, request_id)。
     * </pre>
     *
     * <code>uint64 request_id = 1 [json_name = "requestId"];</code>
     * @return The requestId.
     */
    @java.lang.Override
    public long getRequestId() {
      return requestId_;
    }
    /**
     * <pre>
     * 本连接作用域的请求 ID，语义同 Request.request_id：0 永久保留，首个为 1，
     * 不回绕。匹配键是 (连接, request_id)。
     * </pre>
     *
     * <code>uint64 request_id = 1 [json_name = "requestId"];</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(long value) {

      requestId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 本连接作用域的请求 ID，语义同 Request.request_id：0 永久保留，首个为 1，
     * 不回绕。匹配键是 (连接, request_id)。
     * </pre>
     *
     * <code>uint64 request_id = 1 [json_name = "requestId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      requestId_ = 0L;
      onChanged();
      return this;
    }

    private int controllerClass_ = 0;
    /**
     * <pre>
     * 申请的控制主体类别，必须是 HUMAN 或 AI（见 ControllerClass：无 NONE）。
     * </pre>
     *
     * <code>.nervus.ipc.v1.ControllerClass controller_class = 2 [json_name = "controllerClass"];</code>
     * @return The enum numeric value on the wire for controllerClass.
     */
    @java.lang.Override public int getControllerClassValue() {
      return controllerClass_;
    }
    /**
     * <pre>
     * 申请的控制主体类别，必须是 HUMAN 或 AI（见 ControllerClass：无 NONE）。
     * </pre>
     *
     * <code>.nervus.ipc.v1.ControllerClass controller_class = 2 [json_name = "controllerClass"];</code>
     * @param value The enum numeric value on the wire for controllerClass to set.
     * @return This builder for chaining.
     */
    public Builder setControllerClassValue(int value) {
      controllerClass_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 申请的控制主体类别，必须是 HUMAN 或 AI（见 ControllerClass：无 NONE）。
     * </pre>
     *
     * <code>.nervus.ipc.v1.ControllerClass controller_class = 2 [json_name = "controllerClass"];</code>
     * @return The controllerClass.
     */
    @java.lang.Override
    public io.github.nervusos.ipc.v1.ControllerClass getControllerClass() {
      io.github.nervusos.ipc.v1.ControllerClass result = io.github.nervusos.ipc.v1.ControllerClass.forNumber(controllerClass_);
      return result == null ? io.github.nervusos.ipc.v1.ControllerClass.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 申请的控制主体类别，必须是 HUMAN 或 AI（见 ControllerClass：无 NONE）。
     * </pre>
     *
     * <code>.nervus.ipc.v1.ControllerClass controller_class = 2 [json_name = "controllerClass"];</code>
     * @param value The controllerClass to set.
     * @return This builder for chaining.
     */
    public Builder setControllerClass(io.github.nervusos.ipc.v1.ControllerClass value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      controllerClass_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 申请的控制主体类别，必须是 HUMAN 或 AI（见 ControllerClass：无 NONE）。
     * </pre>
     *
     * <code>.nervus.ipc.v1.ControllerClass controller_class = 2 [json_name = "controllerClass"];</code>
     * @return This builder for chaining.
     */
    public Builder clearControllerClass() {
      bitField0_ = (bitField0_ & ~0x00000002);
      controllerClass_ = 0;
      onChanged();
      return this;
    }

    private io.github.nervusos.ipc.v1.ResourceSelector resource_;
    private com.google.protobuf.SingleFieldBuilder<
        io.github.nervusos.ipc.v1.ResourceSelector, io.github.nervusos.ipc.v1.ResourceSelector.Builder, io.github.nervusos.ipc.v1.ResourceSelectorOrBuilder> resourceBuilder_;
    /**
     * <pre>
     * 申请控制的 Resource。ControlLease 天生 Resource-scoped（§10.2）。
     *
     * 【必须显式给出】：v1 曾允许留空并隐式取底盘，那条默认已随 v2 移除。
     * 只有 access_mode 为 EXCLUSIVE_CONTROL 的资源能被租约——声明为 SHARED_OBSERVE
     * 的传感器可被路由，但永远拿不到控制权。
     *
     * 提交 OEM 的 Package/Component/Provider 名一律拒绝（同 ResolveEndpoint.selector）。
     * </pre>
     *
     * <code>.nervus.ipc.v1.ResourceSelector resource = 3 [json_name = "resource"];</code>
     * @return Whether the resource field is set.
     */
    public boolean hasResource() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 申请控制的 Resource。ControlLease 天生 Resource-scoped（§10.2）。
     *
     * 【必须显式给出】：v1 曾允许留空并隐式取底盘，那条默认已随 v2 移除。
     * 只有 access_mode 为 EXCLUSIVE_CONTROL 的资源能被租约——声明为 SHARED_OBSERVE
     * 的传感器可被路由，但永远拿不到控制权。
     *
     * 提交 OEM 的 Package/Component/Provider 名一律拒绝（同 ResolveEndpoint.selector）。
     * </pre>
     *
     * <code>.nervus.ipc.v1.ResourceSelector resource = 3 [json_name = "resource"];</code>
     * @return The resource.
     */
    public io.github.nervusos.ipc.v1.ResourceSelector getResource() {
      if (resourceBuilder_ == null) {
        return resource_ == null ? io.github.nervusos.ipc.v1.ResourceSelector.getDefaultInstance() : resource_;
      } else {
        return resourceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 申请控制的 Resource。ControlLease 天生 Resource-scoped（§10.2）。
     *
     * 【必须显式给出】：v1 曾允许留空并隐式取底盘，那条默认已随 v2 移除。
     * 只有 access_mode 为 EXCLUSIVE_CONTROL 的资源能被租约——声明为 SHARED_OBSERVE
     * 的传感器可被路由，但永远拿不到控制权。
     *
     * 提交 OEM 的 Package/Component/Provider 名一律拒绝（同 ResolveEndpoint.selector）。
     * </pre>
     *
     * <code>.nervus.ipc.v1.ResourceSelector resource = 3 [json_name = "resource"];</code>
     */
    public Builder setResource(io.github.nervusos.ipc.v1.ResourceSelector value) {
      if (resourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
      } else {
        resourceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 申请控制的 Resource。ControlLease 天生 Resource-scoped（§10.2）。
     *
     * 【必须显式给出】：v1 曾允许留空并隐式取底盘，那条默认已随 v2 移除。
     * 只有 access_mode 为 EXCLUSIVE_CONTROL 的资源能被租约——声明为 SHARED_OBSERVE
     * 的传感器可被路由，但永远拿不到控制权。
     *
     * 提交 OEM 的 Package/Component/Provider 名一律拒绝（同 ResolveEndpoint.selector）。
     * </pre>
     *
     * <code>.nervus.ipc.v1.ResourceSelector resource = 3 [json_name = "resource"];</code>
     */
    public Builder setResource(
        io.github.nervusos.ipc.v1.ResourceSelector.Builder builderForValue) {
      if (resourceBuilder_ == null) {
        resource_ = builderForValue.build();
      } else {
        resourceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 申请控制的 Resource。ControlLease 天生 Resource-scoped（§10.2）。
     *
     * 【必须显式给出】：v1 曾允许留空并隐式取底盘，那条默认已随 v2 移除。
     * 只有 access_mode 为 EXCLUSIVE_CONTROL 的资源能被租约——声明为 SHARED_OBSERVE
     * 的传感器可被路由，但永远拿不到控制权。
     *
     * 提交 OEM 的 Package/Component/Provider 名一律拒绝（同 ResolveEndpoint.selector）。
     * </pre>
     *
     * <code>.nervus.ipc.v1.ResourceSelector resource = 3 [json_name = "resource"];</code>
     */
    public Builder mergeResource(io.github.nervusos.ipc.v1.ResourceSelector value) {
      if (resourceBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          resource_ != null &&
          resource_ != io.github.nervusos.ipc.v1.ResourceSelector.getDefaultInstance()) {
          getResourceBuilder().mergeFrom(value);
        } else {
          resource_ = value;
        }
      } else {
        resourceBuilder_.mergeFrom(value);
      }
      if (resource_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 申请控制的 Resource。ControlLease 天生 Resource-scoped（§10.2）。
     *
     * 【必须显式给出】：v1 曾允许留空并隐式取底盘，那条默认已随 v2 移除。
     * 只有 access_mode 为 EXCLUSIVE_CONTROL 的资源能被租约——声明为 SHARED_OBSERVE
     * 的传感器可被路由，但永远拿不到控制权。
     *
     * 提交 OEM 的 Package/Component/Provider 名一律拒绝（同 ResolveEndpoint.selector）。
     * </pre>
     *
     * <code>.nervus.ipc.v1.ResourceSelector resource = 3 [json_name = "resource"];</code>
     */
    public Builder clearResource() {
      bitField0_ = (bitField0_ & ~0x00000004);
      resource_ = null;
      if (resourceBuilder_ != null) {
        resourceBuilder_.dispose();
        resourceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 申请控制的 Resource。ControlLease 天生 Resource-scoped（§10.2）。
     *
     * 【必须显式给出】：v1 曾允许留空并隐式取底盘，那条默认已随 v2 移除。
     * 只有 access_mode 为 EXCLUSIVE_CONTROL 的资源能被租约——声明为 SHARED_OBSERVE
     * 的传感器可被路由，但永远拿不到控制权。
     *
     * 提交 OEM 的 Package/Component/Provider 名一律拒绝（同 ResolveEndpoint.selector）。
     * </pre>
     *
     * <code>.nervus.ipc.v1.ResourceSelector resource = 3 [json_name = "resource"];</code>
     */
    public io.github.nervusos.ipc.v1.ResourceSelector.Builder getResourceBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getResourceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 申请控制的 Resource。ControlLease 天生 Resource-scoped（§10.2）。
     *
     * 【必须显式给出】：v1 曾允许留空并隐式取底盘，那条默认已随 v2 移除。
     * 只有 access_mode 为 EXCLUSIVE_CONTROL 的资源能被租约——声明为 SHARED_OBSERVE
     * 的传感器可被路由，但永远拿不到控制权。
     *
     * 提交 OEM 的 Package/Component/Provider 名一律拒绝（同 ResolveEndpoint.selector）。
     * </pre>
     *
     * <code>.nervus.ipc.v1.ResourceSelector resource = 3 [json_name = "resource"];</code>
     */
    public io.github.nervusos.ipc.v1.ResourceSelectorOrBuilder getResourceOrBuilder() {
      if (resourceBuilder_ != null) {
        return resourceBuilder_.getMessageOrBuilder();
      } else {
        return resource_ == null ?
            io.github.nervusos.ipc.v1.ResourceSelector.getDefaultInstance() : resource_;
      }
    }
    /**
     * <pre>
     * 申请控制的 Resource。ControlLease 天生 Resource-scoped（§10.2）。
     *
     * 【必须显式给出】：v1 曾允许留空并隐式取底盘，那条默认已随 v2 移除。
     * 只有 access_mode 为 EXCLUSIVE_CONTROL 的资源能被租约——声明为 SHARED_OBSERVE
     * 的传感器可被路由，但永远拿不到控制权。
     *
     * 提交 OEM 的 Package/Component/Provider 名一律拒绝（同 ResolveEndpoint.selector）。
     * </pre>
     *
     * <code>.nervus.ipc.v1.ResourceSelector resource = 3 [json_name = "resource"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.github.nervusos.ipc.v1.ResourceSelector, io.github.nervusos.ipc.v1.ResourceSelector.Builder, io.github.nervusos.ipc.v1.ResourceSelectorOrBuilder> 
        getResourceFieldBuilder() {
      if (resourceBuilder_ == null) {
        resourceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.github.nervusos.ipc.v1.ResourceSelector, io.github.nervusos.ipc.v1.ResourceSelector.Builder, io.github.nervusos.ipc.v1.ResourceSelectorOrBuilder>(
                getResource(),
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      return resourceBuilder_;
    }

    private long requestedDeadlineNanos_ ;
    /**
     * <pre>
     * 调用者期望的租约时效（纳秒）。这是【期望值】不是承诺：nervud 可按 Policy
     * 收紧（远程 HUMAN lease 尤其短）。0 表示采用系统默认，【不表示】无限。
     * </pre>
     *
     * <code>int64 requested_deadline_nanos = 4 [json_name = "requestedDeadlineNanos"];</code>
     * @return The requestedDeadlineNanos.
     */
    @java.lang.Override
    public long getRequestedDeadlineNanos() {
      return requestedDeadlineNanos_;
    }
    /**
     * <pre>
     * 调用者期望的租约时效（纳秒）。这是【期望值】不是承诺：nervud 可按 Policy
     * 收紧（远程 HUMAN lease 尤其短）。0 表示采用系统默认，【不表示】无限。
     * </pre>
     *
     * <code>int64 requested_deadline_nanos = 4 [json_name = "requestedDeadlineNanos"];</code>
     * @param value The requestedDeadlineNanos to set.
     * @return This builder for chaining.
     */
    public Builder setRequestedDeadlineNanos(long value) {

      requestedDeadlineNanos_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 调用者期望的租约时效（纳秒）。这是【期望值】不是承诺：nervud 可按 Policy
     * 收紧（远程 HUMAN lease 尤其短）。0 表示采用系统默认，【不表示】无限。
     * </pre>
     *
     * <code>int64 requested_deadline_nanos = 4 [json_name = "requestedDeadlineNanos"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestedDeadlineNanos() {
      bitField0_ = (bitField0_ & ~0x00000008);
      requestedDeadlineNanos_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:nervus.ipc.v1.AcquireControl)
  }

  // @@protoc_insertion_point(class_scope:nervus.ipc.v1.AcquireControl)
  private static final io.github.nervusos.ipc.v1.AcquireControl DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.nervusos.ipc.v1.AcquireControl();
  }

  public static io.github.nervusos.ipc.v1.AcquireControl getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AcquireControl>
      PARSER = new com.google.protobuf.AbstractParser<AcquireControl>() {
    @java.lang.Override
    public AcquireControl parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AcquireControl> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AcquireControl> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.nervusos.ipc.v1.AcquireControl getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

