// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/ipc/v1/envelope.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.ipc.v1;

public interface AcquireControlResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nervus.ipc.v1.AcquireControlResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 request_id = 1 [json_name = "requestId"];</code>
   * @return The requestId.
   */
  long getRequestId();

  /**
   * <code>.nervus.ipc.v1.AcquireControlSuccess success = 2 [json_name = "success"];</code>
   * @return Whether the success field is set.
   */
  boolean hasSuccess();
  /**
   * <code>.nervus.ipc.v1.AcquireControlSuccess success = 2 [json_name = "success"];</code>
   * @return The success.
   */
  io.github.nervusos.ipc.v1.AcquireControlSuccess getSuccess();
  /**
   * <code>.nervus.ipc.v1.AcquireControlSuccess success = 2 [json_name = "success"];</code>
   */
  io.github.nervusos.ipc.v1.AcquireControlSuccessOrBuilder getSuccessOrBuilder();

  /**
   * <pre>
   * error_detail 的类型固定为 ControlLeaseErrorDetail：调用者需要"被谁占着"
   * 这类可区分原因才知道该退避还是该抢占，笼统 BUSY 不够（§10.2 规则）。
   * </pre>
   *
   * <code>.nervus.ipc.v1.Failure failure = 3 [json_name = "failure"];</code>
   * @return Whether the failure field is set.
   */
  boolean hasFailure();
  /**
   * <pre>
   * error_detail 的类型固定为 ControlLeaseErrorDetail：调用者需要"被谁占着"
   * 这类可区分原因才知道该退避还是该抢占，笼统 BUSY 不够（§10.2 规则）。
   * </pre>
   *
   * <code>.nervus.ipc.v1.Failure failure = 3 [json_name = "failure"];</code>
   * @return The failure.
   */
  io.github.nervusos.ipc.v1.Failure getFailure();
  /**
   * <pre>
   * error_detail 的类型固定为 ControlLeaseErrorDetail：调用者需要"被谁占着"
   * 这类可区分原因才知道该退避还是该抢占，笼统 BUSY 不够（§10.2 规则）。
   * </pre>
   *
   * <code>.nervus.ipc.v1.Failure failure = 3 [json_name = "failure"];</code>
   */
  io.github.nervusos.ipc.v1.FailureOrBuilder getFailureOrBuilder();

  io.github.nervusos.ipc.v1.AcquireControlResult.OutcomeCase getOutcomeCase();
}
