// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/ipc/v1/envelope.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.ipc.v1;

public interface DispatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nervus.ipc.v1.Dispatch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * nervud 生成的路由 ID，只在 nervud 与【被选中的那条 Service 连接】之间
   * 有效，对调用者与其他 Service 不可见。
   *
   * nervud 侧 route_id 映射到 (目标 Service 连接、endpoint binding generation、
   * 来源连接、来源 request_id、deadline、method schema)。generation 等信息
   * 【不上 wire】——Service 无法伪造它不知道的东西。
   * </pre>
   *
   * <code>uint64 route_id = 1 [json_name = "routeId"];</code>
   * @return The routeId.
   */
  long getRouteId();

  /**
   * <pre>
   * Service 侧 endpoint 句柄，即 RegisterEndpointSuccess.endpoint_id。
   * </pre>
   *
   * <code>uint64 endpoint_id = 2 [json_name = "endpointId"];</code>
   * @return The endpointId.
   */
  long getEndpointId();

  /**
   * <code>uint32 method_id = 3 [json_name = "methodId"];</code>
   * @return The methodId.
   */
  int getMethodId();

  /**
   * <pre>
   * 本次调用【剩余】的时间预算（毫秒），而不是原始 timeout。
   *
   * 排队与转发已经消耗掉一部分，把原始值传下去会让 Service 以为自己有更多
   * 时间，产生「Service 还在算、nervud 已经超时回了 DEADLINE_EXCEEDED」的
   * 撕裂。Service 应据此设置自己的内部 deadline。
   * </pre>
   *
   * <code>uint32 remaining_ms = 4 [json_name = "remainingMs"];</code>
   * @return The remainingMs.
   */
  int getRemainingMs();

  /**
   * <code>bytes payload = 5 [json_name = "payload"];</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <pre>
   * 由 nervud 附加的可信调用者上下文。Service 可以读，但不能用它绕过已经
   * 生效的 nervud Policy，更不能自行创造身份或权限裁决（§10.2）。
   * </pre>
   *
   * <code>.nervus.ipc.v1.CallerContext caller = 6 [json_name = "caller"];</code>
   * @return Whether the caller field is set.
   */
  boolean hasCaller();
  /**
   * <pre>
   * 由 nervud 附加的可信调用者上下文。Service 可以读，但不能用它绕过已经
   * 生效的 nervud Policy，更不能自行创造身份或权限裁决（§10.2）。
   * </pre>
   *
   * <code>.nervus.ipc.v1.CallerContext caller = 6 [json_name = "caller"];</code>
   * @return The caller.
   */
  io.github.nervusos.ipc.v1.CallerContext getCaller();
  /**
   * <pre>
   * 由 nervud 附加的可信调用者上下文。Service 可以读，但不能用它绕过已经
   * 生效的 nervud Policy，更不能自行创造身份或权限裁决（§10.2）。
   * </pre>
   *
   * <code>.nervus.ipc.v1.CallerContext caller = 6 [json_name = "caller"];</code>
   */
  io.github.nervusos.ipc.v1.CallerContextOrBuilder getCallerOrBuilder();
}
