// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/ipc/v1/envelope.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.ipc.v1;

public final class EnvelopeProto {
  private EnvelopeProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      EnvelopeProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_Envelope_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_Envelope_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_Hello_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_Hello_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_HelloAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_HelloAck_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_HelloAckSuccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_HelloAckSuccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_ConnectionLimits_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_ConnectionLimits_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_ResolveEndpoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_ResolveEndpoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_ResourceSelector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_ResourceSelector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_ResolveEndpointResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_ResolveEndpointResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_ResolveEndpointSuccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_ResolveEndpointSuccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_RegisterEndpoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_RegisterEndpoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_RegisterEndpointResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_RegisterEndpointResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_RegisterEndpointSuccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_RegisterEndpointSuccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_UnregisterEndpoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_UnregisterEndpoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_UnregisterEndpointResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_UnregisterEndpointResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_UnregisterEndpointSuccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_UnregisterEndpointSuccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_EndpointDied_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_EndpointDied_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_EndpointRevoked_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_EndpointRevoked_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_Cancel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_Cancel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_Subscribe_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_Subscribe_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_SubscribeResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_SubscribeResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_SubscribeSuccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_SubscribeSuccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_Unsubscribe_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_Unsubscribe_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_UnsubscribeResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_UnsubscribeResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_UnsubscribeSuccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_UnsubscribeSuccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_SubscriptionClosed_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_SubscriptionClosed_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_Dispatch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_Dispatch_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_CallerContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_CallerContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_DispatchResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_DispatchResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_CancelDispatch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_CancelDispatch_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_Ping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_Ping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_Pong_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_Pong_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034nervus/ipc/v1/envelope.proto\022\rnervus.i" +
      "pc.v1\032\032nervus/ipc/v1/status.proto\"\321\r\n\010En" +
      "velope\022%\n\016protocol_major\030\001 \001(\rR\rprotocol" +
      "Major\022%\n\016protocol_minor\030\002 \001(\rR\rprotocolM" +
      "inor\022,\n\005hello\030\n \001(\0132\024.nervus.ipc.v1.Hell" +
      "oH\000R\005hello\0226\n\thello_ack\030\013 \001(\0132\027.nervus.i" +
      "pc.v1.HelloAckH\000R\010helloAck\022K\n\020resolve_en" +
      "dpoint\030\024 \001(\0132\036.nervus.ipc.v1.ResolveEndp" +
      "ointH\000R\017resolveEndpoint\022^\n\027resolve_endpo" +
      "int_result\030\025 \001(\0132$.nervus.ipc.v1.Resolve" +
      "EndpointResultH\000R\025resolveEndpointResult\022" +
      "N\n\021register_endpoint\030\026 \001(\0132\037.nervus.ipc." +
      "v1.RegisterEndpointH\000R\020registerEndpoint\022" +
      "a\n\030register_endpoint_result\030\027 \001(\0132%.nerv" +
      "us.ipc.v1.RegisterEndpointResultH\000R\026regi" +
      "sterEndpointResult\022B\n\rendpoint_died\030\030 \001(" +
      "\0132\033.nervus.ipc.v1.EndpointDiedH\000R\014endpoi" +
      "ntDied\022K\n\020endpoint_revoked\030\031 \001(\0132\036.nervu" +
      "s.ipc.v1.EndpointRevokedH\000R\017endpointRevo" +
      "ked\022T\n\023unregister_endpoint\030\032 \001(\0132!.nervu" +
      "s.ipc.v1.UnregisterEndpointH\000R\022unregiste" +
      "rEndpoint\022g\n\032unregister_endpoint_result\030" +
      "\033 \001(\0132\'.nervus.ipc.v1.UnregisterEndpoint" +
      "ResultH\000R\030unregisterEndpointResult\0222\n\007re" +
      "quest\030\036 \001(\0132\026.nervus.ipc.v1.RequestH\000R\007r" +
      "equest\0225\n\010response\030\037 \001(\0132\027.nervus.ipc.v1" +
      ".ResponseH\000R\010response\022/\n\006cancel\030  \001(\0132\025." +
      "nervus.ipc.v1.CancelH\000R\006cancel\0228\n\tsubscr" +
      "ibe\030( \001(\0132\030.nervus.ipc.v1.SubscribeH\000R\ts" +
      "ubscribe\022K\n\020subscribe_result\030) \001(\0132\036.ner" +
      "vus.ipc.v1.SubscribeResultH\000R\017subscribeR" +
      "esult\022>\n\013unsubscribe\030* \001(\0132\032.nervus.ipc." +
      "v1.UnsubscribeH\000R\013unsubscribe\022,\n\005event\030+" +
      " \001(\0132\024.nervus.ipc.v1.EventH\000R\005event\022Q\n\022u" +
      "nsubscribe_result\030, \001(\0132 .nervus.ipc.v1." +
      "UnsubscribeResultH\000R\021unsubscribeResult\022T" +
      "\n\023subscription_closed\030- \001(\0132!.nervus.ipc" +
      ".v1.SubscriptionClosedH\000R\022subscriptionCl" +
      "osed\0225\n\010dispatch\0302 \001(\0132\027.nervus.ipc.v1.D" +
      "ispatchH\000R\010dispatch\022H\n\017dispatch_result\0303" +
      " \001(\0132\035.nervus.ipc.v1.DispatchResultH\000R\016d" +
      "ispatchResult\022H\n\017cancel_dispatch\0304 \001(\0132\035" +
      ".nervus.ipc.v1.CancelDispatchH\000R\016cancelD" +
      "ispatch\022)\n\004ping\030< \001(\0132\023.nervus.ipc.v1.Pi" +
      "ngH\000R\004ping\022)\n\004pong\030= \001(\0132\023.nervus.ipc.v1" +
      ".PongH\000R\004pongB\006\n\004body\"\201\002\n\005Hello\022,\n\022min_p" +
      "rotocol_major\030\001 \001(\rR\020minProtocolMajor\022,\n" +
      "\022max_protocol_major\030\002 \001(\rR\020maxProtocolMa" +
      "jor\022,\n\022max_protocol_minor\030\003 \001(\rR\020maxProt" +
      "ocolMinor\022\031\n\010sdk_name\030\004 \001(\tR\007sdkName\022\037\n\013" +
      "sdk_version\030\005 \001(\tR\nsdkVersion\0222\n\025declare" +
      "d_component_id\030\006 \001(\tR\023declaredComponentI" +
      "d\"\205\001\n\010HelloAck\022:\n\007success\030\001 \001(\0132\036.nervus" +
      ".ipc.v1.HelloAckSuccessH\000R\007success\0222\n\007fa" +
      "ilure\030\002 \001(\0132\026.nervus.ipc.v1.FailureH\000R\007f" +
      "ailureB\t\n\007outcome\"\332\001\n\017HelloAckSuccess\022%\n" +
      "\016protocol_major\030\001 \001(\rR\rprotocolMajor\022%\n\016" +
      "protocol_minor\030\002 \001(\rR\rprotocolMinor\022\035\n\np" +
      "ackage_id\030\003 \001(\tR\tpackageId\022!\n\014component_" +
      "id\030\004 \001(\tR\013componentId\0227\n\006limits\030\005 \001(\0132\037." +
      "nervus.ipc.v1.ConnectionLimitsR\006limits\"\316" +
      "\003\n\020ConnectionLimits\022&\n\017max_frame_bytes\030\001" +
      " \001(\rR\rmaxFrameBytes\022?\n\034default_method_pa" +
      "yload_bytes\030\002 \001(\rR\031defaultMethodPayloadB" +
      "ytes\0222\n\025max_inflight_requests\030\003 \001(\rR\023max" +
      "InflightRequests\022;\n\032max_inflight_payload" +
      "_bytes\030\004 \001(\004R\027maxInflightPayloadBytes\0227\n" +
      "\030max_outbound_queue_bytes\030\005 \001(\004R\025maxOutb" +
      "oundQueueBytes\022+\n\021max_subscriptions\030\006 \001(" +
      "\rR\020maxSubscriptions\022,\n\022default_timeout_m" +
      "s\030\007 \001(\rR\020defaultTimeoutMs\022$\n\016max_timeout" +
      "_ms\030\010 \001(\rR\014maxTimeoutMs\022&\n\017idle_timeout_" +
      "ms\030\t \001(\rR\ridleTimeoutMs\"\237\002\n\017ResolveEndpo" +
      "int\022\035\n\nrequest_id\030\001 \001(\004R\trequestId\022!\n\014in" +
      "terface_id\030\002 \001(\tR\013interfaceId\022.\n\023min_int" +
      "erface_major\030\003 \001(\rR\021minInterfaceMajor\022.\n" +
      "\023max_interface_major\030\004 \001(\rR\021maxInterface" +
      "Major\022;\n\010selector\030\005 \001(\0132\037.nervus.ipc.v1." +
      "ResourceSelectorR\010selector\022-\n\022explicit_c" +
      "omponent\030\006 \001(\tR\021explicitComponent\":\n\020Res" +
      "ourceSelector\022\022\n\004type\030\001 \001(\tR\004type\022\022\n\004rol" +
      "e\030\002 \001(\tR\004role\"\270\001\n\025ResolveEndpointResult\022" +
      "\035\n\nrequest_id\030\001 \001(\004R\trequestId\022A\n\007succes" +
      "s\030\002 \001(\0132%.nervus.ipc.v1.ResolveEndpointS" +
      "uccessH\000R\007success\0222\n\007failure\030\003 \001(\0132\026.ner" +
      "vus.ipc.v1.FailureH\000R\007failureB\t\n\007outcome" +
      "\"\223\002\n\026ResolveEndpointSuccess\022\037\n\013endpoint_" +
      "id\030\001 \001(\004R\nendpointId\022\'\n\017interface_major\030" +
      "\002 \001(\rR\016interfaceMajor\022\'\n\017interface_minor" +
      "\030\003 \001(\rR\016interfaceMinor\0222\n\025interface_sche" +
      "ma_hash\030\004 \001(\014R\023interfaceSchemaHash\022\'\n\017re" +
      "source_handle\030\005 \001(\tR\016resourceHandle\022)\n\020c" +
      "atalog_revision\030\006 \001(\004R\017catalogRevision\"\203" +
      "\002\n\020RegisterEndpoint\022\035\n\nrequest_id\030\001 \001(\004R" +
      "\trequestId\022!\n\014interface_id\030\002 \001(\tR\013interf" +
      "aceId\022\'\n\017interface_major\030\003 \001(\rR\016interfac" +
      "eMajor\022\'\n\017interface_minor\030\004 \001(\rR\016interfa" +
      "ceMinor\0222\n\025interface_schema_hash\030\005 \001(\014R\023" +
      "interfaceSchemaHash\022\'\n\017resource_handle\030\006" +
      " \001(\tR\016resourceHandle\"\272\001\n\026RegisterEndpoin" +
      "tResult\022\035\n\nrequest_id\030\001 \001(\004R\trequestId\022B" +
      "\n\007success\030\002 \001(\0132&.nervus.ipc.v1.Register" +
      "EndpointSuccessH\000R\007success\0222\n\007failure\030\003 " +
      "\001(\0132\026.nervus.ipc.v1.FailureH\000R\007failureB\t" +
      "\n\007outcome\":\n\027RegisterEndpointSuccess\022\037\n\013" +
      "endpoint_id\030\001 \001(\004R\nendpointId\"j\n\022Unregis" +
      "terEndpoint\022\035\n\nrequest_id\030\001 \001(\004R\trequest" +
      "Id\022\037\n\013endpoint_id\030\002 \001(\004R\nendpointId\022\024\n\005d" +
      "rain\030\003 \001(\010R\005drain\"\276\001\n\030UnregisterEndpoint" +
      "Result\022\035\n\nrequest_id\030\001 \001(\004R\trequestId\022D\n" +
      "\007success\030\002 \001(\0132(.nervus.ipc.v1.Unregiste" +
      "rEndpointSuccessH\000R\007success\0222\n\007failure\030\003" +
      " \001(\0132\026.nervus.ipc.v1.FailureH\000R\007failureB" +
      "\t\n\007outcome\"\033\n\031UnregisterEndpointSuccess\"" +
      "j\n\014EndpointDied\022\037\n\013endpoint_id\030\001 \001(\004R\nen" +
      "dpointId\0229\n\006reason\030\002 \001(\0162!.nervus.ipc.v1" +
      ".EndpointDiedReasonR\006reason\"p\n\017EndpointR" +
      "evoked\022\037\n\013endpoint_id\030\001 \001(\004R\nendpointId\022" +
      "<\n\006reason\030\002 \001(\0162$.nervus.ipc.v1.Endpoint" +
      "RevokedReasonR\006reason\"\237\001\n\007Request\022\035\n\nreq" +
      "uest_id\030\001 \001(\004R\trequestId\022\037\n\013endpoint_id\030" +
      "\002 \001(\004R\nendpointId\022\033\n\tmethod_id\030\003 \001(\rR\010me" +
      "thodId\022\035\n\ntimeout_ms\030\004 \001(\rR\ttimeoutMs\022\030\n" +
      "\007payload\030\005 \001(\014R\007payload\"\234\001\n\010Response\022\035\n\n" +
      "request_id\030\001 \001(\004R\trequestId\0222\n\007success\030\002" +
      " \001(\0132\026.nervus.ipc.v1.SuccessH\000R\007success\022" +
      "2\n\007failure\030\003 \001(\0132\026.nervus.ipc.v1.Failure" +
      "H\000R\007failureB\t\n\007outcome\"\'\n\006Cancel\022\035\n\nrequ" +
      "est_id\030\001 \001(\004R\trequestId\"\200\001\n\tSubscribe\022\035\n" +
      "\nrequest_id\030\001 \001(\004R\trequestId\022\037\n\013endpoint" +
      "_id\030\002 \001(\004R\nendpointId\022\031\n\010event_id\030\003 \001(\rR" +
      "\007eventId\022\030\n\007payload\030\004 \001(\014R\007payload\"\254\001\n\017S" +
      "ubscribeResult\022\035\n\nrequest_id\030\001 \001(\004R\trequ" +
      "estId\022;\n\007success\030\002 \001(\0132\037.nervus.ipc.v1.S" +
      "ubscribeSuccessH\000R\007success\0222\n\007failure\030\003 " +
      "\001(\0132\026.nervus.ipc.v1.FailureH\000R\007failureB\t" +
      "\n\007outcome\"\200\001\n\020SubscribeSuccess\022\'\n\017subscr" +
      "iption_id\030\001 \001(\004R\016subscriptionId\022C\n\016deliv" +
      "ery_class\030\002 \001(\0162\034.nervus.ipc.v1.Delivery" +
      "ClassR\rdeliveryClass\"U\n\013Unsubscribe\022\035\n\nr" +
      "equest_id\030\001 \001(\004R\trequestId\022\'\n\017subscripti" +
      "on_id\030\002 \001(\004R\016subscriptionId\"\260\001\n\021Unsubscr" +
      "ibeResult\022\035\n\nrequest_id\030\001 \001(\004R\trequestId" +
      "\022=\n\007success\030\002 \001(\0132!.nervus.ipc.v1.Unsubs" +
      "cribeSuccessH\000R\007success\0222\n\007failure\030\003 \001(\013" +
      "2\026.nervus.ipc.v1.FailureH\000R\007failureB\t\n\007o" +
      "utcome\"\024\n\022UnsubscribeSuccess\"\274\001\n\005Event\022\'" +
      "\n\017subscription_id\030\001 \001(\004R\016subscriptionId\022" +
      "\032\n\010sequence\030\002 \001(\004R\010sequence\022\037\n\013endpoint_" +
      "id\030\003 \001(\004R\nendpointId\022\031\n\010event_id\030\004 \001(\rR\007" +
      "eventId\022\030\n\007payload\030\005 \001(\014R\007payload\022\030\n\007dro" +
      "pped\030\006 \001(\004R\007dropped\"~\n\022SubscriptionClose" +
      "d\022\'\n\017subscription_id\030\001 \001(\004R\016subscription" +
      "Id\022?\n\006reason\030\002 \001(\0162\'.nervus.ipc.v1.Subsc" +
      "riptionClosedReasonR\006reason\"\326\001\n\010Dispatch" +
      "\022\031\n\010route_id\030\001 \001(\004R\007routeId\022\037\n\013endpoint_" +
      "id\030\002 \001(\004R\nendpointId\022\033\n\tmethod_id\030\003 \001(\rR" +
      "\010methodId\022!\n\014remaining_ms\030\004 \001(\rR\013remaini" +
      "ngMs\022\030\n\007payload\030\005 \001(\014R\007payload\0224\n\006caller" +
      "\030\006 \001(\0132\034.nervus.ipc.v1.CallerContextR\006ca" +
      "ller\"\372\001\n\rCallerContext\022\035\n\npackage_id\030\001 \001" +
      "(\tR\tpackageId\022!\n\014component_id\030\002 \001(\tR\013com" +
      "ponentId\022\020\n\003uid\030\003 \001(\rR\003uid\022\020\n\003gid\030\004 \001(\rR" +
      "\003gid\022\020\n\003pid\030\005 \001(\005R\003pid\022@\n\rtrust_profile\030" +
      "\006 \001(\0162\033.nervus.ipc.v1.TrustProfileR\014trus" +
      "tProfile\022/\n\023granted_permissions\030\007 \003(\tR\022g" +
      "rantedPermissions\"\236\001\n\016DispatchResult\022\031\n\010" +
      "route_id\030\001 \001(\004R\007routeId\0222\n\007success\030\002 \001(\013" +
      "2\026.nervus.ipc.v1.SuccessH\000R\007success\0222\n\007f" +
      "ailure\030\003 \001(\0132\026.nervus.ipc.v1.FailureH\000R\007" +
      "failureB\t\n\007outcome\"h\n\016CancelDispatch\022\031\n\010" +
      "route_id\030\001 \001(\004R\007routeId\022;\n\006reason\030\002 \001(\0162" +
      "#.nervus.ipc.v1.CancelDispatchReasonR\006re" +
      "ason\"\034\n\004Ping\022\024\n\005nonce\030\001 \001(\004R\005nonce\"\034\n\004Po" +
      "ng\022\024\n\005nonce\030\001 \001(\004R\005nonce*\346\001\n\022EndpointDie" +
      "dReason\022$\n ENDPOINT_DIED_REASON_UNSPECIF" +
      "IED\020\000\022%\n!ENDPOINT_DIED_REASON_SERVICE_GO" +
      "NE\020\001\022.\n*ENDPOINT_DIED_REASON_SERVICE_SHU" +
      "TTING_DOWN\020\002\022\'\n#ENDPOINT_DIED_REASON_RES" +
      "OURCE_FAULT\020\003\022*\n&ENDPOINT_DIED_REASON_SE" +
      "RVICE_RESTARTED\020\004*\314\001\n\025EndpointRevokedRea" +
      "son\022\'\n#ENDPOINT_REVOKED_REASON_UNSPECIFI" +
      "ED\020\000\022.\n*ENDPOINT_REVOKED_REASON_PERMISSI" +
      "ON_REVOKED\020\001\022,\n(ENDPOINT_REVOKED_REASON_" +
      "PACKAGE_DISABLED\020\002\022,\n(ENDPOINT_REVOKED_R" +
      "EASON_POLICY_SUSPENDED\020\003*\200\001\n\rDeliveryCla" +
      "ss\022\036\n\032DELIVERY_CLASS_UNSPECIFIED\020\000\022\033\n\027DE" +
      "LIVERY_CLASS_RELIABLE\020\001\022\030\n\024DELIVERY_CLAS" +
      "S_STATE\020\002\022\030\n\024DELIVERY_CLASS_LOSSY\020\003*\202\002\n\030" +
      "SubscriptionClosedReason\022*\n&SUBSCRIPTION" +
      "_CLOSED_REASON_UNSPECIFIED\020\000\022,\n(SUBSCRIP" +
      "TION_CLOSED_REASON_ENDPOINT_DIED\020\001\022/\n+SU" +
      "BSCRIPTION_CLOSED_REASON_ENDPOINT_REVOKE" +
      "D\020\002\022+\n\'SUBSCRIPTION_CLOSED_REASON_BACKPR" +
      "ESSURE\020\003\022.\n*SUBSCRIPTION_CLOSED_REASON_S" +
      "ERVER_SHUTDOWN\020\004*|\n\014TrustProfile\022\035\n\031TRUS" +
      "T_PROFILE_UNSPECIFIED\020\000\022\032\n\026TRUST_PROFILE" +
      "_ORDINARY\020\001\022\025\n\021TRUST_PROFILE_OEM\020\002\022\032\n\026TR" +
      "UST_PROFILE_PLATFORM\020\003*\301\001\n\024CancelDispatc" +
      "hReason\022&\n\"CANCEL_DISPATCH_REASON_UNSPEC" +
      "IFIED\020\000\022+\n\'CANCEL_DISPATCH_REASON_CLIENT" +
      "_CANCELLED\020\001\022,\n(CANCEL_DISPATCH_REASON_D" +
      "EADLINE_EXCEEDED\020\002\022&\n\"CANCEL_DISPATCH_RE" +
      "ASON_CLIENT_GONE\020\003Be\n\031io.github.nervusos" +
      ".ipc.v1B\rEnvelopeProtoP\001Z7github.com/ner" +
      "vus-os/nervus-ipc/go/protocol/ipcv1;ipcv" +
      "1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.github.nervusos.ipc.v1.StatusProto.getDescriptor(),
        });
    internal_static_nervus_ipc_v1_Envelope_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nervus_ipc_v1_Envelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_Envelope_descriptor,
        new java.lang.String[] { "ProtocolMajor", "ProtocolMinor", "Hello", "HelloAck", "ResolveEndpoint", "ResolveEndpointResult", "RegisterEndpoint", "RegisterEndpointResult", "EndpointDied", "EndpointRevoked", "UnregisterEndpoint", "UnregisterEndpointResult", "Request", "Response", "Cancel", "Subscribe", "SubscribeResult", "Unsubscribe", "Event", "UnsubscribeResult", "SubscriptionClosed", "Dispatch", "DispatchResult", "CancelDispatch", "Ping", "Pong", "Body", });
    internal_static_nervus_ipc_v1_Hello_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_nervus_ipc_v1_Hello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_Hello_descriptor,
        new java.lang.String[] { "MinProtocolMajor", "MaxProtocolMajor", "MaxProtocolMinor", "SdkName", "SdkVersion", "DeclaredComponentId", });
    internal_static_nervus_ipc_v1_HelloAck_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_nervus_ipc_v1_HelloAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_HelloAck_descriptor,
        new java.lang.String[] { "Success", "Failure", "Outcome", });
    internal_static_nervus_ipc_v1_HelloAckSuccess_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_nervus_ipc_v1_HelloAckSuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_HelloAckSuccess_descriptor,
        new java.lang.String[] { "ProtocolMajor", "ProtocolMinor", "PackageId", "ComponentId", "Limits", });
    internal_static_nervus_ipc_v1_ConnectionLimits_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_nervus_ipc_v1_ConnectionLimits_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_ConnectionLimits_descriptor,
        new java.lang.String[] { "MaxFrameBytes", "DefaultMethodPayloadBytes", "MaxInflightRequests", "MaxInflightPayloadBytes", "MaxOutboundQueueBytes", "MaxSubscriptions", "DefaultTimeoutMs", "MaxTimeoutMs", "IdleTimeoutMs", });
    internal_static_nervus_ipc_v1_ResolveEndpoint_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_nervus_ipc_v1_ResolveEndpoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_ResolveEndpoint_descriptor,
        new java.lang.String[] { "RequestId", "InterfaceId", "MinInterfaceMajor", "MaxInterfaceMajor", "Selector", "ExplicitComponent", });
    internal_static_nervus_ipc_v1_ResourceSelector_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_nervus_ipc_v1_ResourceSelector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_ResourceSelector_descriptor,
        new java.lang.String[] { "Type", "Role", });
    internal_static_nervus_ipc_v1_ResolveEndpointResult_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_nervus_ipc_v1_ResolveEndpointResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_ResolveEndpointResult_descriptor,
        new java.lang.String[] { "RequestId", "Success", "Failure", "Outcome", });
    internal_static_nervus_ipc_v1_ResolveEndpointSuccess_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_nervus_ipc_v1_ResolveEndpointSuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_ResolveEndpointSuccess_descriptor,
        new java.lang.String[] { "EndpointId", "InterfaceMajor", "InterfaceMinor", "InterfaceSchemaHash", "ResourceHandle", "CatalogRevision", });
    internal_static_nervus_ipc_v1_RegisterEndpoint_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_nervus_ipc_v1_RegisterEndpoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_RegisterEndpoint_descriptor,
        new java.lang.String[] { "RequestId", "InterfaceId", "InterfaceMajor", "InterfaceMinor", "InterfaceSchemaHash", "ResourceHandle", });
    internal_static_nervus_ipc_v1_RegisterEndpointResult_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_nervus_ipc_v1_RegisterEndpointResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_RegisterEndpointResult_descriptor,
        new java.lang.String[] { "RequestId", "Success", "Failure", "Outcome", });
    internal_static_nervus_ipc_v1_RegisterEndpointSuccess_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_nervus_ipc_v1_RegisterEndpointSuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_RegisterEndpointSuccess_descriptor,
        new java.lang.String[] { "EndpointId", });
    internal_static_nervus_ipc_v1_UnregisterEndpoint_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_nervus_ipc_v1_UnregisterEndpoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_UnregisterEndpoint_descriptor,
        new java.lang.String[] { "RequestId", "EndpointId", "Drain", });
    internal_static_nervus_ipc_v1_UnregisterEndpointResult_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_nervus_ipc_v1_UnregisterEndpointResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_UnregisterEndpointResult_descriptor,
        new java.lang.String[] { "RequestId", "Success", "Failure", "Outcome", });
    internal_static_nervus_ipc_v1_UnregisterEndpointSuccess_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_nervus_ipc_v1_UnregisterEndpointSuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_UnregisterEndpointSuccess_descriptor,
        new java.lang.String[] { });
    internal_static_nervus_ipc_v1_EndpointDied_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_nervus_ipc_v1_EndpointDied_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_EndpointDied_descriptor,
        new java.lang.String[] { "EndpointId", "Reason", });
    internal_static_nervus_ipc_v1_EndpointRevoked_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_nervus_ipc_v1_EndpointRevoked_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_EndpointRevoked_descriptor,
        new java.lang.String[] { "EndpointId", "Reason", });
    internal_static_nervus_ipc_v1_Request_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_nervus_ipc_v1_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_Request_descriptor,
        new java.lang.String[] { "RequestId", "EndpointId", "MethodId", "TimeoutMs", "Payload", });
    internal_static_nervus_ipc_v1_Response_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_nervus_ipc_v1_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_Response_descriptor,
        new java.lang.String[] { "RequestId", "Success", "Failure", "Outcome", });
    internal_static_nervus_ipc_v1_Cancel_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_nervus_ipc_v1_Cancel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_Cancel_descriptor,
        new java.lang.String[] { "RequestId", });
    internal_static_nervus_ipc_v1_Subscribe_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_nervus_ipc_v1_Subscribe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_Subscribe_descriptor,
        new java.lang.String[] { "RequestId", "EndpointId", "EventId", "Payload", });
    internal_static_nervus_ipc_v1_SubscribeResult_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_nervus_ipc_v1_SubscribeResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_SubscribeResult_descriptor,
        new java.lang.String[] { "RequestId", "Success", "Failure", "Outcome", });
    internal_static_nervus_ipc_v1_SubscribeSuccess_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_nervus_ipc_v1_SubscribeSuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_SubscribeSuccess_descriptor,
        new java.lang.String[] { "SubscriptionId", "DeliveryClass", });
    internal_static_nervus_ipc_v1_Unsubscribe_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_nervus_ipc_v1_Unsubscribe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_Unsubscribe_descriptor,
        new java.lang.String[] { "RequestId", "SubscriptionId", });
    internal_static_nervus_ipc_v1_UnsubscribeResult_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_nervus_ipc_v1_UnsubscribeResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_UnsubscribeResult_descriptor,
        new java.lang.String[] { "RequestId", "Success", "Failure", "Outcome", });
    internal_static_nervus_ipc_v1_UnsubscribeSuccess_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_nervus_ipc_v1_UnsubscribeSuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_UnsubscribeSuccess_descriptor,
        new java.lang.String[] { });
    internal_static_nervus_ipc_v1_Event_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_nervus_ipc_v1_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_Event_descriptor,
        new java.lang.String[] { "SubscriptionId", "Sequence", "EndpointId", "EventId", "Payload", "Dropped", });
    internal_static_nervus_ipc_v1_SubscriptionClosed_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_nervus_ipc_v1_SubscriptionClosed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_SubscriptionClosed_descriptor,
        new java.lang.String[] { "SubscriptionId", "Reason", });
    internal_static_nervus_ipc_v1_Dispatch_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_nervus_ipc_v1_Dispatch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_Dispatch_descriptor,
        new java.lang.String[] { "RouteId", "EndpointId", "MethodId", "RemainingMs", "Payload", "Caller", });
    internal_static_nervus_ipc_v1_CallerContext_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_nervus_ipc_v1_CallerContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_CallerContext_descriptor,
        new java.lang.String[] { "PackageId", "ComponentId", "Uid", "Gid", "Pid", "TrustProfile", "GrantedPermissions", });
    internal_static_nervus_ipc_v1_DispatchResult_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_nervus_ipc_v1_DispatchResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_DispatchResult_descriptor,
        new java.lang.String[] { "RouteId", "Success", "Failure", "Outcome", });
    internal_static_nervus_ipc_v1_CancelDispatch_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_nervus_ipc_v1_CancelDispatch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_CancelDispatch_descriptor,
        new java.lang.String[] { "RouteId", "Reason", });
    internal_static_nervus_ipc_v1_Ping_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_nervus_ipc_v1_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_Ping_descriptor,
        new java.lang.String[] { "Nonce", });
    internal_static_nervus_ipc_v1_Pong_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_nervus_ipc_v1_Pong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_Pong_descriptor,
        new java.lang.String[] { "Nonce", });
    descriptor.resolveAllFeaturesImmutable();
    io.github.nervusos.ipc.v1.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
