// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/ipc/v1/safety.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.ipc.v1;

/**
 * <pre>
 * HaltReason 是 Safety 触发原因（仅参考）。
 * </pre>
 *
 * Protobuf enum {@code nervus.ipc.v1.HaltReason}
 */
public enum HaltReason
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>HALT_REASON_UNSPECIFIED = 0;</code>
   */
  HALT_REASON_UNSPECIFIED(0),
  /**
   * <pre>
   * 人工/UI 软件急停
   * </pre>
   *
   * <code>HALT_REASON_OPERATOR_ESTOP = 1;</code>
   */
  HALT_REASON_OPERATOR_ESTOP(1),
  /**
   * <pre>
   * deadman / 命令新鲜度失效
   * </pre>
   *
   * <code>HALT_REASON_DEADMAN_TIMEOUT = 2;</code>
   */
  HALT_REASON_DEADMAN_TIMEOUT(2),
  /**
   * <pre>
   * Provider 故障触发
   * </pre>
   *
   * <code>HALT_REASON_PROVIDER_FAULT = 3;</code>
   */
  HALT_REASON_PROVIDER_FAULT(3),
  /**
   * <pre>
   * 与 Provider/MCU 心跳丢失
   * </pre>
   *
   * <code>HALT_REASON_HEARTBEAT_LOST = 4;</code>
   */
  HALT_REASON_HEARTBEAT_LOST(4),
  /**
   * <pre>
   * Supervisor 超时升级
   * </pre>
   *
   * <code>HALT_REASON_SUPERVISOR_ESCALATION = 5;</code>
   */
  HALT_REASON_SUPERVISOR_ESCALATION(5),
  /**
   * <pre>
   * 外部（MCU/独立硬件）上报导致的锁存
   * </pre>
   *
   * <code>HALT_REASON_EXTERNAL_TRIP = 6;</code>
   */
  HALT_REASON_EXTERNAL_TRIP(6),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      HaltReason.class.getName());
  }
  /**
   * <code>HALT_REASON_UNSPECIFIED = 0;</code>
   */
  public static final int HALT_REASON_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * 人工/UI 软件急停
   * </pre>
   *
   * <code>HALT_REASON_OPERATOR_ESTOP = 1;</code>
   */
  public static final int HALT_REASON_OPERATOR_ESTOP_VALUE = 1;
  /**
   * <pre>
   * deadman / 命令新鲜度失效
   * </pre>
   *
   * <code>HALT_REASON_DEADMAN_TIMEOUT = 2;</code>
   */
  public static final int HALT_REASON_DEADMAN_TIMEOUT_VALUE = 2;
  /**
   * <pre>
   * Provider 故障触发
   * </pre>
   *
   * <code>HALT_REASON_PROVIDER_FAULT = 3;</code>
   */
  public static final int HALT_REASON_PROVIDER_FAULT_VALUE = 3;
  /**
   * <pre>
   * 与 Provider/MCU 心跳丢失
   * </pre>
   *
   * <code>HALT_REASON_HEARTBEAT_LOST = 4;</code>
   */
  public static final int HALT_REASON_HEARTBEAT_LOST_VALUE = 4;
  /**
   * <pre>
   * Supervisor 超时升级
   * </pre>
   *
   * <code>HALT_REASON_SUPERVISOR_ESCALATION = 5;</code>
   */
  public static final int HALT_REASON_SUPERVISOR_ESCALATION_VALUE = 5;
  /**
   * <pre>
   * 外部（MCU/独立硬件）上报导致的锁存
   * </pre>
   *
   * <code>HALT_REASON_EXTERNAL_TRIP = 6;</code>
   */
  public static final int HALT_REASON_EXTERNAL_TRIP_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static HaltReason valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static HaltReason forNumber(int value) {
    switch (value) {
      case 0: return HALT_REASON_UNSPECIFIED;
      case 1: return HALT_REASON_OPERATOR_ESTOP;
      case 2: return HALT_REASON_DEADMAN_TIMEOUT;
      case 3: return HALT_REASON_PROVIDER_FAULT;
      case 4: return HALT_REASON_HEARTBEAT_LOST;
      case 5: return HALT_REASON_SUPERVISOR_ESCALATION;
      case 6: return HALT_REASON_EXTERNAL_TRIP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<HaltReason>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      HaltReason> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<HaltReason>() {
          public HaltReason findValueByNumber(int number) {
            return HaltReason.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.github.nervusos.ipc.v1.SafetyProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final HaltReason[] VALUES = values();

  public static HaltReason valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private HaltReason(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:nervus.ipc.v1.HaltReason)
}

