// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/ipc/v1/envelope.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.ipc.v1;

/**
 * <pre>
 * LaunchComponent 请求 nervud 拉起一个已安装的组件。
 *
 * 这是 Launcher（桌面）点开一个 App 时发出的消息，也是会话服务在开机后把桌面
 * 唤起来的方式。
 *
 * ## 它【不】做的事
 *
 * 不返回任何指向被启动组件的句柄，也不建立任何调用关系。启动完成后调用方想跟
 * 它通信，仍要走正常的 ResolveEndpoint —— 「谁能调它」由那条路径上的权限与
 * 可见性裁决决定，不因为「是我把它启动的」而放松。
 *
 * ## 权限
 *
 * 需要 perm.system.launch。这不是普通应用该有的能力：能任意拉起别的组件
 * 意味着能绕过 on-demand 的节能语义、也能把一个刚被停用又被启用的组件立刻拉起。
 * v1 只给 Launcher 与会话服务。
 * </pre>
 *
 * Protobuf type {@code nervus.ipc.v1.LaunchComponent}
 */
public final class LaunchComponent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:nervus.ipc.v1.LaunchComponent)
    LaunchComponentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      LaunchComponent.class.getName());
  }
  // Use LaunchComponent.newBuilder() to construct.
  private LaunchComponent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LaunchComponent() {
    packageId_ = "";
    componentId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.nervusos.ipc.v1.EnvelopeProto.internal_static_nervus_ipc_v1_LaunchComponent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.nervusos.ipc.v1.EnvelopeProto.internal_static_nervus_ipc_v1_LaunchComponent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.nervusos.ipc.v1.LaunchComponent.class, io.github.nervusos.ipc.v1.LaunchComponent.Builder.class);
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  private long requestId_ = 0L;
  /**
   * <pre>
   * 本连接作用域的请求 ID，语义同 Request.request_id（0 保留，首个为 1，不回绕）。
   * </pre>
   *
   * <code>uint64 request_id = 1 [json_name = "requestId"];</code>
   * @return The requestId.
   */
  @java.lang.Override
  public long getRequestId() {
    return requestId_;
  }

  public static final int PACKAGE_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object packageId_ = "";
  /**
   * <pre>
   * 目标 Package。
   * </pre>
   *
   * <code>string package_id = 2 [json_name = "packageId"];</code>
   * @return The packageId.
   */
  @java.lang.Override
  public java.lang.String getPackageId() {
    java.lang.Object ref = packageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packageId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 目标 Package。
   * </pre>
   *
   * <code>string package_id = 2 [json_name = "packageId"];</code>
   * @return The bytes for packageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackageIdBytes() {
    java.lang.Object ref = packageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPONENT_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object componentId_ = "";
  /**
   * <pre>
   * 目标 Component。
   *
   * 【必填】。不做「留空表示该包唯一的 app 组件」这类推断：一个包完全可能有
   * 多个 app 组件，而推断规则会在它从一个变成两个的那天悄悄改变行为——
   * 调用方明确说出要启动谁，是唯一不会在将来变味的语义。
   * </pre>
   *
   * <code>string component_id = 3 [json_name = "componentId"];</code>
   * @return The componentId.
   */
  @java.lang.Override
  public java.lang.String getComponentId() {
    java.lang.Object ref = componentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      componentId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 目标 Component。
   *
   * 【必填】。不做「留空表示该包唯一的 app 组件」这类推断：一个包完全可能有
   * 多个 app 组件，而推断规则会在它从一个变成两个的那天悄悄改变行为——
   * 调用方明确说出要启动谁，是唯一不会在将来变味的语义。
   * </pre>
   *
   * <code>string component_id = 3 [json_name = "componentId"];</code>
   * @return The bytes for componentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getComponentIdBytes() {
    java.lang.Object ref = componentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      componentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestId_ != 0L) {
      output.writeUInt64(1, requestId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(packageId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, packageId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(componentId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, componentId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, requestId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(packageId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, packageId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(componentId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, componentId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.nervusos.ipc.v1.LaunchComponent)) {
      return super.equals(obj);
    }
    io.github.nervusos.ipc.v1.LaunchComponent other = (io.github.nervusos.ipc.v1.LaunchComponent) obj;

    if (getRequestId()
        != other.getRequestId()) return false;
    if (!getPackageId()
        .equals(other.getPackageId())) return false;
    if (!getComponentId()
        .equals(other.getComponentId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRequestId());
    hash = (37 * hash) + PACKAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPackageId().hashCode();
    hash = (37 * hash) + COMPONENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getComponentId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.nervusos.ipc.v1.LaunchComponent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.ipc.v1.LaunchComponent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.ipc.v1.LaunchComponent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.ipc.v1.LaunchComponent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.ipc.v1.LaunchComponent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.ipc.v1.LaunchComponent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.ipc.v1.LaunchComponent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.nervusos.ipc.v1.LaunchComponent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.nervusos.ipc.v1.LaunchComponent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.nervusos.ipc.v1.LaunchComponent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.nervusos.ipc.v1.LaunchComponent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.nervusos.ipc.v1.LaunchComponent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.nervusos.ipc.v1.LaunchComponent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * LaunchComponent 请求 nervud 拉起一个已安装的组件。
   *
   * 这是 Launcher（桌面）点开一个 App 时发出的消息，也是会话服务在开机后把桌面
   * 唤起来的方式。
   *
   * ## 它【不】做的事
   *
   * 不返回任何指向被启动组件的句柄，也不建立任何调用关系。启动完成后调用方想跟
   * 它通信，仍要走正常的 ResolveEndpoint —— 「谁能调它」由那条路径上的权限与
   * 可见性裁决决定，不因为「是我把它启动的」而放松。
   *
   * ## 权限
   *
   * 需要 perm.system.launch。这不是普通应用该有的能力：能任意拉起别的组件
   * 意味着能绕过 on-demand 的节能语义、也能把一个刚被停用又被启用的组件立刻拉起。
   * v1 只给 Launcher 与会话服务。
   * </pre>
   *
   * Protobuf type {@code nervus.ipc.v1.LaunchComponent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nervus.ipc.v1.LaunchComponent)
      io.github.nervusos.ipc.v1.LaunchComponentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.nervusos.ipc.v1.EnvelopeProto.internal_static_nervus_ipc_v1_LaunchComponent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.nervusos.ipc.v1.EnvelopeProto.internal_static_nervus_ipc_v1_LaunchComponent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.nervusos.ipc.v1.LaunchComponent.class, io.github.nervusos.ipc.v1.LaunchComponent.Builder.class);
    }

    // Construct using io.github.nervusos.ipc.v1.LaunchComponent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      requestId_ = 0L;
      packageId_ = "";
      componentId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.nervusos.ipc.v1.EnvelopeProto.internal_static_nervus_ipc_v1_LaunchComponent_descriptor;
    }

    @java.lang.Override
    public io.github.nervusos.ipc.v1.LaunchComponent getDefaultInstanceForType() {
      return io.github.nervusos.ipc.v1.LaunchComponent.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.nervusos.ipc.v1.LaunchComponent build() {
      io.github.nervusos.ipc.v1.LaunchComponent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.nervusos.ipc.v1.LaunchComponent buildPartial() {
      io.github.nervusos.ipc.v1.LaunchComponent result = new io.github.nervusos.ipc.v1.LaunchComponent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.nervusos.ipc.v1.LaunchComponent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.requestId_ = requestId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.packageId_ = packageId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.componentId_ = componentId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.nervusos.ipc.v1.LaunchComponent) {
        return mergeFrom((io.github.nervusos.ipc.v1.LaunchComponent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.nervusos.ipc.v1.LaunchComponent other) {
      if (other == io.github.nervusos.ipc.v1.LaunchComponent.getDefaultInstance()) return this;
      if (other.getRequestId() != 0L) {
        setRequestId(other.getRequestId());
      }
      if (!other.getPackageId().isEmpty()) {
        packageId_ = other.packageId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getComponentId().isEmpty()) {
        componentId_ = other.componentId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              requestId_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              packageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              componentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long requestId_ ;
    /**
     * <pre>
     * 本连接作用域的请求 ID，语义同 Request.request_id（0 保留，首个为 1，不回绕）。
     * </pre>
     *
     * <code>uint64 request_id = 1 [json_name = "requestId"];</code>
     * @return The requestId.
     */
    @java.lang.Override
    public long getRequestId() {
      return requestId_;
    }
    /**
     * <pre>
     * 本连接作用域的请求 ID，语义同 Request.request_id（0 保留，首个为 1，不回绕）。
     * </pre>
     *
     * <code>uint64 request_id = 1 [json_name = "requestId"];</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(long value) {

      requestId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 本连接作用域的请求 ID，语义同 Request.request_id（0 保留，首个为 1，不回绕）。
     * </pre>
     *
     * <code>uint64 request_id = 1 [json_name = "requestId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      requestId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object packageId_ = "";
    /**
     * <pre>
     * 目标 Package。
     * </pre>
     *
     * <code>string package_id = 2 [json_name = "packageId"];</code>
     * @return The packageId.
     */
    public java.lang.String getPackageId() {
      java.lang.Object ref = packageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 目标 Package。
     * </pre>
     *
     * <code>string package_id = 2 [json_name = "packageId"];</code>
     * @return The bytes for packageId.
     */
    public com.google.protobuf.ByteString
        getPackageIdBytes() {
      java.lang.Object ref = packageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 目标 Package。
     * </pre>
     *
     * <code>string package_id = 2 [json_name = "packageId"];</code>
     * @param value The packageId to set.
     * @return This builder for chaining.
     */
    public Builder setPackageId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      packageId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 目标 Package。
     * </pre>
     *
     * <code>string package_id = 2 [json_name = "packageId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageId() {
      packageId_ = getDefaultInstance().getPackageId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 目标 Package。
     * </pre>
     *
     * <code>string package_id = 2 [json_name = "packageId"];</code>
     * @param value The bytes for packageId to set.
     * @return This builder for chaining.
     */
    public Builder setPackageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      packageId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object componentId_ = "";
    /**
     * <pre>
     * 目标 Component。
     *
     * 【必填】。不做「留空表示该包唯一的 app 组件」这类推断：一个包完全可能有
     * 多个 app 组件，而推断规则会在它从一个变成两个的那天悄悄改变行为——
     * 调用方明确说出要启动谁，是唯一不会在将来变味的语义。
     * </pre>
     *
     * <code>string component_id = 3 [json_name = "componentId"];</code>
     * @return The componentId.
     */
    public java.lang.String getComponentId() {
      java.lang.Object ref = componentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        componentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 目标 Component。
     *
     * 【必填】。不做「留空表示该包唯一的 app 组件」这类推断：一个包完全可能有
     * 多个 app 组件，而推断规则会在它从一个变成两个的那天悄悄改变行为——
     * 调用方明确说出要启动谁，是唯一不会在将来变味的语义。
     * </pre>
     *
     * <code>string component_id = 3 [json_name = "componentId"];</code>
     * @return The bytes for componentId.
     */
    public com.google.protobuf.ByteString
        getComponentIdBytes() {
      java.lang.Object ref = componentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        componentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 目标 Component。
     *
     * 【必填】。不做「留空表示该包唯一的 app 组件」这类推断：一个包完全可能有
     * 多个 app 组件，而推断规则会在它从一个变成两个的那天悄悄改变行为——
     * 调用方明确说出要启动谁，是唯一不会在将来变味的语义。
     * </pre>
     *
     * <code>string component_id = 3 [json_name = "componentId"];</code>
     * @param value The componentId to set.
     * @return This builder for chaining.
     */
    public Builder setComponentId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      componentId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 目标 Component。
     *
     * 【必填】。不做「留空表示该包唯一的 app 组件」这类推断：一个包完全可能有
     * 多个 app 组件，而推断规则会在它从一个变成两个的那天悄悄改变行为——
     * 调用方明确说出要启动谁，是唯一不会在将来变味的语义。
     * </pre>
     *
     * <code>string component_id = 3 [json_name = "componentId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearComponentId() {
      componentId_ = getDefaultInstance().getComponentId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 目标 Component。
     *
     * 【必填】。不做「留空表示该包唯一的 app 组件」这类推断：一个包完全可能有
     * 多个 app 组件，而推断规则会在它从一个变成两个的那天悄悄改变行为——
     * 调用方明确说出要启动谁，是唯一不会在将来变味的语义。
     * </pre>
     *
     * <code>string component_id = 3 [json_name = "componentId"];</code>
     * @param value The bytes for componentId to set.
     * @return This builder for chaining.
     */
    public Builder setComponentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      componentId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:nervus.ipc.v1.LaunchComponent)
  }

  // @@protoc_insertion_point(class_scope:nervus.ipc.v1.LaunchComponent)
  private static final io.github.nervusos.ipc.v1.LaunchComponent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.nervusos.ipc.v1.LaunchComponent();
  }

  public static io.github.nervusos.ipc.v1.LaunchComponent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LaunchComponent>
      PARSER = new com.google.protobuf.AbstractParser<LaunchComponent>() {
    @java.lang.Override
    public LaunchComponent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LaunchComponent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LaunchComponent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.nervusos.ipc.v1.LaunchComponent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

