// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/ipc/v1/provider_descriptor.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.ipc.v1;

public interface LocalizedTextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nervus.ipc.v1.LocalizedText)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string zh_cn = 1 [json_name = "zhCn"];</code>
   * @return The zhCn.
   */
  java.lang.String getZhCn();
  /**
   * <code>string zh_cn = 1 [json_name = "zhCn"];</code>
   * @return The bytes for zhCn.
   */
  com.google.protobuf.ByteString
      getZhCnBytes();

  /**
   * <code>string en = 2 [json_name = "en"];</code>
   * @return The en.
   */
  java.lang.String getEn();
  /**
   * <code>string en = 2 [json_name = "en"];</code>
   * @return The bytes for en.
   */
  com.google.protobuf.ByteString
      getEnBytes();
}
