// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/ipc/v1/method_registry.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.ipc.v1;

public final class MethodRegistryProto {
  private MethodRegistryProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      MethodRegistryProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(io.github.nervusos.ipc.v1.MethodRegistryProto.methodMeta);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int METHOD_META_FIELD_NUMBER = 60001;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      io.github.nervusos.ipc.v1.MethodMeta> methodMeta = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        io.github.nervusos.ipc.v1.MethodMeta.class,
        io.github.nervusos.ipc.v1.MethodMeta.getDefaultInstance());
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nervus_ipc_v1_MethodMeta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nervus_ipc_v1_MethodMeta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#nervus/ipc/v1/method_registry.proto\022\rn" +
      "ervus.ipc.v1\032 google/protobuf/descriptor" +
      ".proto\032\034nervus/ipc/v1/transfer.proto\"\312\005\n" +
      "\nMethodMeta\022\033\n\tmethod_id\030\001 \001(\rR\010methodId" +
      "\022/\n\023required_permission\030\002 \001(\tR\022requiredP" +
      "ermission\0227\n\nrisk_class\030\003 \001(\0162\030.nervus.i" +
      "pc.v1.RiskClassR\triskClass\0224\n\026requires_c" +
      "ontrol_lease\030\004 \001(\010R\024requiresControlLease" +
      "\022+\n\021returns_operation\030\005 \001(\010R\020returnsOper" +
      "ation\0226\n\027needs_user_confirmation\030\006 \001(\010R\025" +
      "needsUserConfirmation\022!\n\014request_type\030\007 " +
      "\001(\tR\013requestType\022#\n\rresponse_type\030\010 \001(\tR" +
      "\014responseType\022 \n\014is_read_only\030\t \001(\010R\nisR" +
      "eadOnly\022\033\n\tis_motion\030\n \001(\010R\010isMotion\022,\n\022" +
      "default_timeout_ms\030\013 \001(\rR\020defaultTimeout" +
      "Ms\022$\n\016max_timeout_ms\030\014 \001(\rR\014maxTimeoutMs" +
      "\022*\n\021max_request_bytes\030\r \001(\rR\017maxRequestB" +
      "ytes\022,\n\022max_response_bytes\030\016 \001(\rR\020maxRes" +
      "ponseBytes\0229\n\010transfer\030\017 \001(\0132\035.nervus.ip" +
      "c.v1.TransferPolicyR\010transfer\022*\n\021error_d" +
      "etail_type\030\020 \001(\tR\017errorDetailType*\241\001\n\tRi" +
      "skClass\022\032\n\026RISK_CLASS_UNSPECIFIED\020\000\022\025\n\021R" +
      "ISK_CLASS_NORMAL\020\001\022 \n\034RISK_CLASS_PRIVACY" +
      "_SENSITIVE\020\002\022\037\n\033RISK_CLASS_PHYSICAL_CONT" +
      "ROL\020\003\022\036\n\032RISK_CLASS_CRITICAL_SAFETY\020\004:_\n" +
      "\013method_meta\022!.google.protobuf.EnumValue" +
      "Options\030\341\324\003 \001(\0132\031.nervus.ipc.v1.MethodMe" +
      "taR\nmethodMetaBh\n\031io.github.nervusos.ipc" +
      ".v1B\023MethodRegistryProtoP\001Z4github.com/n" +
      "ervus-os/nervus-ipc/protocol/ipcv1;ipcv1" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          io.github.nervusos.ipc.v1.TransferProto.getDescriptor(),
        });
    internal_static_nervus_ipc_v1_MethodMeta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nervus_ipc_v1_MethodMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_nervus_ipc_v1_MethodMeta_descriptor,
        new java.lang.String[] { "MethodId", "RequiredPermission", "RiskClass", "RequiresControlLease", "ReturnsOperation", "NeedsUserConfirmation", "RequestType", "ResponseType", "IsReadOnly", "IsMotion", "DefaultTimeoutMs", "MaxTimeoutMs", "MaxRequestBytes", "MaxResponseBytes", "Transfer", "ErrorDetailType", });
    methodMeta.internalInit(descriptor.getExtensions().get(0));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
    io.github.nervusos.ipc.v1.TransferProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
