// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/ipc/v1/safety.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.ipc.v1;

public interface ProviderFaultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nervus.ipc.v1.ProviderFault)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 motion_epoch = 1 [json_name = "motionEpoch"];</code>
   * @return The motionEpoch.
   */
  long getMotionEpoch();

  /**
   * <code>.nervus.ipc.v1.FaultCode code = 2 [json_name = "code"];</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.nervus.ipc.v1.FaultCode code = 2 [json_name = "code"];</code>
   * @return The code.
   */
  io.github.nervusos.ipc.v1.FaultCode getCode();
}
