// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/ipc/v1/envelope.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.ipc.v1;

/**
 * <pre>
 * PublishEvent 是 Provider 向 nervud 上报一条事件（本文件扩展，号 53）。
 *
 * 【只出现在 nervud ↔ Service 的连接上】，订阅方既不发送也不接收——它收到的是
 * nervud 扇出后的 Event(43)。
 *
 * # 为什么不能让 Provider 直接发 Event
 *
 * Event 携带 subscription_id，那是【订阅方连接作用域】的句柄。Provider 不知道
 * 有哪些订阅者、更不知道它们各自的句柄，也不该知道——那是别人连接上的东西。
 * 让 Provider 填这个字段等于让它指定「这条消息投递给谁」，而投递决策必须留在
 * nervud：订阅方的权限可能在订阅之后被撤销，Provider 无从得知。
 *
 * # nervud 收到之后做什么
 *
 * 1. 核对 endpoint_id 属于本连接、且仍然存活
 * 2. 按 event_id 查权威 EventMeta；未声明的 event_id 一律拒绝——Provider
 * 不能推一个没在契约里出现过的事件
 * 3. 按 max_payload_bytes 与 max_events_per_second 收紧
 * 4. 扇出给每个订阅者，各自换算成它自己的 subscription_id 与 sequence，
 * 并按 delivery_class 处理背压（RELIABLE 断慢消费者 / STATE 合并 / LOSSY 丢弃）
 *
 * 【没有 PublishEventResult】：上报是单向的。给它配一个结果会让 Provider 的
 * 事件循环变成请求-响应，一个慢订阅者就能拖住整个 Provider——而背压的正确
 * 落点是 nervud 与订阅方之间，不是 nervud 与 Provider 之间。
 * </pre>
 *
 * Protobuf type {@code nervus.ipc.v1.PublishEvent}
 */
public final class PublishEvent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:nervus.ipc.v1.PublishEvent)
    PublishEventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      PublishEvent.class.getName());
  }
  // Use PublishEvent.newBuilder() to construct.
  private PublishEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PublishEvent() {
    payload_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.nervusos.ipc.v1.EnvelopeProto.internal_static_nervus_ipc_v1_PublishEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.nervusos.ipc.v1.EnvelopeProto.internal_static_nervus_ipc_v1_PublishEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.nervusos.ipc.v1.PublishEvent.class, io.github.nervusos.ipc.v1.PublishEvent.Builder.class);
  }

  public static final int ENDPOINT_ID_FIELD_NUMBER = 1;
  private long endpointId_ = 0L;
  /**
   * <pre>
   * Provider 侧 endpoint 句柄，即 RegisterEndpointSuccess.endpoint_id。
   *
   * 用 Provider 自己的句柄而不是订阅方的：nervud 据此确认「这条连接确实拥有
   * 这个 endpoint」，Provider 无法替别的 endpoint 推事件。
   * </pre>
   *
   * <code>uint64 endpoint_id = 1 [json_name = "endpointId"];</code>
   * @return The endpointId.
   */
  @java.lang.Override
  public long getEndpointId() {
    return endpointId_;
  }

  public static final int EVENT_ID_FIELD_NUMBER = 2;
  private int eventId_ = 0;
  /**
   * <pre>
   * schema 中稳定的数字事件 ID。必须在该接口的 EventMeta 里声明过。
   * </pre>
   *
   * <code>uint32 event_id = 2 [json_name = "eventId"];</code>
   * @return The eventId.
   */
  @java.lang.Override
  public int getEventId() {
    return eventId_;
  }

  public static final int PAYLOAD_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * 事件专属 Protobuf bytes，可为空（纯信号事件）。
   * </pre>
   *
   * <code>bytes payload = 3 [json_name = "payload"];</code>
   * @return The payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }

  public static final int MONOTONIC_TIMESTAMP_NANOS_FIELD_NUMBER = 4;
  private long monotonicTimestampNanos_ = 0L;
  /**
   * <pre>
   * Provider 侧的单调时间戳（纳秒），可为 0 表示不提供。
   *
   * nervud 不用它做任何裁决——它只是随事件透传给订阅方，让消费者能算出
   * 「这条数据是什么时候产生的」而不是「什么时候收到的」。
   * </pre>
   *
   * <code>uint64 monotonic_timestamp_nanos = 4 [json_name = "monotonicTimestampNanos"];</code>
   * @return The monotonicTimestampNanos.
   */
  @java.lang.Override
  public long getMonotonicTimestampNanos() {
    return monotonicTimestampNanos_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (endpointId_ != 0L) {
      output.writeUInt64(1, endpointId_);
    }
    if (eventId_ != 0) {
      output.writeUInt32(2, eventId_);
    }
    if (!payload_.isEmpty()) {
      output.writeBytes(3, payload_);
    }
    if (monotonicTimestampNanos_ != 0L) {
      output.writeUInt64(4, monotonicTimestampNanos_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (endpointId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, endpointId_);
    }
    if (eventId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, eventId_);
    }
    if (!payload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, payload_);
    }
    if (monotonicTimestampNanos_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, monotonicTimestampNanos_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.nervusos.ipc.v1.PublishEvent)) {
      return super.equals(obj);
    }
    io.github.nervusos.ipc.v1.PublishEvent other = (io.github.nervusos.ipc.v1.PublishEvent) obj;

    if (getEndpointId()
        != other.getEndpointId()) return false;
    if (getEventId()
        != other.getEventId()) return false;
    if (!getPayload()
        .equals(other.getPayload())) return false;
    if (getMonotonicTimestampNanos()
        != other.getMonotonicTimestampNanos()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENDPOINT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndpointId());
    hash = (37 * hash) + EVENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEventId();
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (37 * hash) + MONOTONIC_TIMESTAMP_NANOS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMonotonicTimestampNanos());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.nervusos.ipc.v1.PublishEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.ipc.v1.PublishEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.ipc.v1.PublishEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.ipc.v1.PublishEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.ipc.v1.PublishEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.nervusos.ipc.v1.PublishEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.nervusos.ipc.v1.PublishEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.nervusos.ipc.v1.PublishEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.nervusos.ipc.v1.PublishEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.nervusos.ipc.v1.PublishEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.nervusos.ipc.v1.PublishEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.nervusos.ipc.v1.PublishEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.nervusos.ipc.v1.PublishEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * PublishEvent 是 Provider 向 nervud 上报一条事件（本文件扩展，号 53）。
   *
   * 【只出现在 nervud ↔ Service 的连接上】，订阅方既不发送也不接收——它收到的是
   * nervud 扇出后的 Event(43)。
   *
   * # 为什么不能让 Provider 直接发 Event
   *
   * Event 携带 subscription_id，那是【订阅方连接作用域】的句柄。Provider 不知道
   * 有哪些订阅者、更不知道它们各自的句柄，也不该知道——那是别人连接上的东西。
   * 让 Provider 填这个字段等于让它指定「这条消息投递给谁」，而投递决策必须留在
   * nervud：订阅方的权限可能在订阅之后被撤销，Provider 无从得知。
   *
   * # nervud 收到之后做什么
   *
   * 1. 核对 endpoint_id 属于本连接、且仍然存活
   * 2. 按 event_id 查权威 EventMeta；未声明的 event_id 一律拒绝——Provider
   * 不能推一个没在契约里出现过的事件
   * 3. 按 max_payload_bytes 与 max_events_per_second 收紧
   * 4. 扇出给每个订阅者，各自换算成它自己的 subscription_id 与 sequence，
   * 并按 delivery_class 处理背压（RELIABLE 断慢消费者 / STATE 合并 / LOSSY 丢弃）
   *
   * 【没有 PublishEventResult】：上报是单向的。给它配一个结果会让 Provider 的
   * 事件循环变成请求-响应，一个慢订阅者就能拖住整个 Provider——而背压的正确
   * 落点是 nervud 与订阅方之间，不是 nervud 与 Provider 之间。
   * </pre>
   *
   * Protobuf type {@code nervus.ipc.v1.PublishEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nervus.ipc.v1.PublishEvent)
      io.github.nervusos.ipc.v1.PublishEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.nervusos.ipc.v1.EnvelopeProto.internal_static_nervus_ipc_v1_PublishEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.nervusos.ipc.v1.EnvelopeProto.internal_static_nervus_ipc_v1_PublishEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.nervusos.ipc.v1.PublishEvent.class, io.github.nervusos.ipc.v1.PublishEvent.Builder.class);
    }

    // Construct using io.github.nervusos.ipc.v1.PublishEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      endpointId_ = 0L;
      eventId_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
      monotonicTimestampNanos_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.nervusos.ipc.v1.EnvelopeProto.internal_static_nervus_ipc_v1_PublishEvent_descriptor;
    }

    @java.lang.Override
    public io.github.nervusos.ipc.v1.PublishEvent getDefaultInstanceForType() {
      return io.github.nervusos.ipc.v1.PublishEvent.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.nervusos.ipc.v1.PublishEvent build() {
      io.github.nervusos.ipc.v1.PublishEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.nervusos.ipc.v1.PublishEvent buildPartial() {
      io.github.nervusos.ipc.v1.PublishEvent result = new io.github.nervusos.ipc.v1.PublishEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.nervusos.ipc.v1.PublishEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.endpointId_ = endpointId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.eventId_ = eventId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.payload_ = payload_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.monotonicTimestampNanos_ = monotonicTimestampNanos_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.nervusos.ipc.v1.PublishEvent) {
        return mergeFrom((io.github.nervusos.ipc.v1.PublishEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.nervusos.ipc.v1.PublishEvent other) {
      if (other == io.github.nervusos.ipc.v1.PublishEvent.getDefaultInstance()) return this;
      if (other.getEndpointId() != 0L) {
        setEndpointId(other.getEndpointId());
      }
      if (other.getEventId() != 0) {
        setEventId(other.getEventId());
      }
      if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
        setPayload(other.getPayload());
      }
      if (other.getMonotonicTimestampNanos() != 0L) {
        setMonotonicTimestampNanos(other.getMonotonicTimestampNanos());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              endpointId_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              eventId_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              payload_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              monotonicTimestampNanos_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long endpointId_ ;
    /**
     * <pre>
     * Provider 侧 endpoint 句柄，即 RegisterEndpointSuccess.endpoint_id。
     *
     * 用 Provider 自己的句柄而不是订阅方的：nervud 据此确认「这条连接确实拥有
     * 这个 endpoint」，Provider 无法替别的 endpoint 推事件。
     * </pre>
     *
     * <code>uint64 endpoint_id = 1 [json_name = "endpointId"];</code>
     * @return The endpointId.
     */
    @java.lang.Override
    public long getEndpointId() {
      return endpointId_;
    }
    /**
     * <pre>
     * Provider 侧 endpoint 句柄，即 RegisterEndpointSuccess.endpoint_id。
     *
     * 用 Provider 自己的句柄而不是订阅方的：nervud 据此确认「这条连接确实拥有
     * 这个 endpoint」，Provider 无法替别的 endpoint 推事件。
     * </pre>
     *
     * <code>uint64 endpoint_id = 1 [json_name = "endpointId"];</code>
     * @param value The endpointId to set.
     * @return This builder for chaining.
     */
    public Builder setEndpointId(long value) {

      endpointId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Provider 侧 endpoint 句柄，即 RegisterEndpointSuccess.endpoint_id。
     *
     * 用 Provider 自己的句柄而不是订阅方的：nervud 据此确认「这条连接确实拥有
     * 这个 endpoint」，Provider 无法替别的 endpoint 推事件。
     * </pre>
     *
     * <code>uint64 endpoint_id = 1 [json_name = "endpointId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEndpointId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      endpointId_ = 0L;
      onChanged();
      return this;
    }

    private int eventId_ ;
    /**
     * <pre>
     * schema 中稳定的数字事件 ID。必须在该接口的 EventMeta 里声明过。
     * </pre>
     *
     * <code>uint32 event_id = 2 [json_name = "eventId"];</code>
     * @return The eventId.
     */
    @java.lang.Override
    public int getEventId() {
      return eventId_;
    }
    /**
     * <pre>
     * schema 中稳定的数字事件 ID。必须在该接口的 EventMeta 里声明过。
     * </pre>
     *
     * <code>uint32 event_id = 2 [json_name = "eventId"];</code>
     * @param value The eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventId(int value) {

      eventId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * schema 中稳定的数字事件 ID。必须在该接口的 EventMeta 里声明过。
     * </pre>
     *
     * <code>uint32 event_id = 2 [json_name = "eventId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEventId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      eventId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 事件专属 Protobuf bytes，可为空（纯信号事件）。
     * </pre>
     *
     * <code>bytes payload = 3 [json_name = "payload"];</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <pre>
     * 事件专属 Protobuf bytes，可为空（纯信号事件）。
     * </pre>
     *
     * <code>bytes payload = 3 [json_name = "payload"];</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      payload_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件专属 Protobuf bytes，可为空（纯信号事件）。
     * </pre>
     *
     * <code>bytes payload = 3 [json_name = "payload"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      bitField0_ = (bitField0_ & ~0x00000004);
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }

    private long monotonicTimestampNanos_ ;
    /**
     * <pre>
     * Provider 侧的单调时间戳（纳秒），可为 0 表示不提供。
     *
     * nervud 不用它做任何裁决——它只是随事件透传给订阅方，让消费者能算出
     * 「这条数据是什么时候产生的」而不是「什么时候收到的」。
     * </pre>
     *
     * <code>uint64 monotonic_timestamp_nanos = 4 [json_name = "monotonicTimestampNanos"];</code>
     * @return The monotonicTimestampNanos.
     */
    @java.lang.Override
    public long getMonotonicTimestampNanos() {
      return monotonicTimestampNanos_;
    }
    /**
     * <pre>
     * Provider 侧的单调时间戳（纳秒），可为 0 表示不提供。
     *
     * nervud 不用它做任何裁决——它只是随事件透传给订阅方，让消费者能算出
     * 「这条数据是什么时候产生的」而不是「什么时候收到的」。
     * </pre>
     *
     * <code>uint64 monotonic_timestamp_nanos = 4 [json_name = "monotonicTimestampNanos"];</code>
     * @param value The monotonicTimestampNanos to set.
     * @return This builder for chaining.
     */
    public Builder setMonotonicTimestampNanos(long value) {

      monotonicTimestampNanos_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Provider 侧的单调时间戳（纳秒），可为 0 表示不提供。
     *
     * nervud 不用它做任何裁决——它只是随事件透传给订阅方，让消费者能算出
     * 「这条数据是什么时候产生的」而不是「什么时候收到的」。
     * </pre>
     *
     * <code>uint64 monotonic_timestamp_nanos = 4 [json_name = "monotonicTimestampNanos"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMonotonicTimestampNanos() {
      bitField0_ = (bitField0_ & ~0x00000008);
      monotonicTimestampNanos_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:nervus.ipc.v1.PublishEvent)
  }

  // @@protoc_insertion_point(class_scope:nervus.ipc.v1.PublishEvent)
  private static final io.github.nervusos.ipc.v1.PublishEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.nervusos.ipc.v1.PublishEvent();
  }

  public static io.github.nervusos.ipc.v1.PublishEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublishEvent>
      PARSER = new com.google.protobuf.AbstractParser<PublishEvent>() {
    @java.lang.Override
    public PublishEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PublishEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PublishEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.nervusos.ipc.v1.PublishEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

