// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/ipc/v1/envelope.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.ipc.v1;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nervus.ipc.v1.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 调用者 SDK 在当前连接内生成的原子递增值（§10.6）。
   *
   * 【0 永久保留】，首个请求为 1，绝不回绕：达到上限时关闭并重建连接。
   * 匹配键是 (内部 connection 对象, request_id)，所以不同连接上的相同数字
   * 互不冲突，即使两个进程同属一个 Package、共享 UID。
   *
   * 同一连接内出现重复的、仍在处理中的 request_id 是协议违规。
   * </pre>
   *
   * <code>uint64 request_id = 1 [json_name = "requestId"];</code>
   * @return The requestId.
   */
  long getRequestId();

  /**
   * <pre>
   * 由 ResolveEndpoint 取得，本连接作用域。
   * </pre>
   *
   * <code>uint64 endpoint_id = 2 [json_name = "endpointId"];</code>
   * @return The endpointId.
   */
  long getEndpointId();

  /**
   * <pre>
   * 接口 schema 中稳定的数字方法 ID。发布后保持稳定，删除后同样保留不用。
   * </pre>
   *
   * <code>uint32 method_id = 3 [json_name = "methodId"];</code>
   * @return The methodId.
   */
  int getMethodId();

  /**
   * <pre>
   * 调用者期望的超时（毫秒）。
   *
   * 【0 表示使用方法默认值，不表示无限】。nervud 按方法最大值收紧，并在接收
   * 时立刻转换成本机【单调时钟】deadline——用墙钟会让一次 NTP 校时把全部
   * 在途调用推向立即超时或永不超时。
   * </pre>
   *
   * <code>uint32 timeout_ms = 4 [json_name = "timeoutMs"];</code>
   * @return The timeoutMs.
   */
  int getTimeoutMs();

  /**
   * <pre>
   * 方法专属 Protobuf 请求的序列化 bytes。类型由
   * endpoint_id + 选中 interface_version + method_id 唯一决定。
   * </pre>
   *
   * <code>bytes payload = 5 [json_name = "payload"];</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
