// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/ipc/v1/safety.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.ipc.v1;

/**
 * <pre>
 * StopPhase 是实际停止进度的相位（架构 §6 / NRCP §14.1）。正常链单调前进；
 * DELIVERY_FAULT / STANDSTILL_TIMEOUT 是任意非终态可进入的终态旁支。无停稳证据能力
 * 的设备封顶在 OUTPUT_DISABLED。
 * </pre>
 *
 * Protobuf enum {@code nervus.ipc.v1.StopPhase}
 */
public enum StopPhase
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>STOP_PHASE_UNSPECIFIED = 0;</code>
   */
  STOP_PHASE_UNSPECIFIED(0),
  /**
   * <code>STOP_PHASE_REQUESTED = 1;</code>
   */
  STOP_PHASE_REQUESTED(1),
  /**
   * <code>STOP_PHASE_SENT = 2;</code>
   */
  STOP_PHASE_SENT(2),
  /**
   * <code>STOP_PHASE_PROVIDER_ACCEPTED = 3;</code>
   */
  STOP_PHASE_PROVIDER_ACCEPTED(3),
  /**
   * <code>STOP_PHASE_MCU_ACKED = 4;</code>
   */
  STOP_PHASE_MCU_ACKED(4),
  /**
   * <code>STOP_PHASE_OUTPUT_DISABLED = 5;</code>
   */
  STOP_PHASE_OUTPUT_DISABLED(5),
  /**
   * <code>STOP_PHASE_STANDSTILL_CONFIRMED = 6;</code>
   */
  STOP_PHASE_STANDSTILL_CONFIRMED(6),
  /**
   * <code>STOP_PHASE_DELIVERY_FAULT = 7;</code>
   */
  STOP_PHASE_DELIVERY_FAULT(7),
  /**
   * <code>STOP_PHASE_STANDSTILL_TIMEOUT = 8;</code>
   */
  STOP_PHASE_STANDSTILL_TIMEOUT(8),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      StopPhase.class.getName());
  }
  /**
   * <code>STOP_PHASE_UNSPECIFIED = 0;</code>
   */
  public static final int STOP_PHASE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>STOP_PHASE_REQUESTED = 1;</code>
   */
  public static final int STOP_PHASE_REQUESTED_VALUE = 1;
  /**
   * <code>STOP_PHASE_SENT = 2;</code>
   */
  public static final int STOP_PHASE_SENT_VALUE = 2;
  /**
   * <code>STOP_PHASE_PROVIDER_ACCEPTED = 3;</code>
   */
  public static final int STOP_PHASE_PROVIDER_ACCEPTED_VALUE = 3;
  /**
   * <code>STOP_PHASE_MCU_ACKED = 4;</code>
   */
  public static final int STOP_PHASE_MCU_ACKED_VALUE = 4;
  /**
   * <code>STOP_PHASE_OUTPUT_DISABLED = 5;</code>
   */
  public static final int STOP_PHASE_OUTPUT_DISABLED_VALUE = 5;
  /**
   * <code>STOP_PHASE_STANDSTILL_CONFIRMED = 6;</code>
   */
  public static final int STOP_PHASE_STANDSTILL_CONFIRMED_VALUE = 6;
  /**
   * <code>STOP_PHASE_DELIVERY_FAULT = 7;</code>
   */
  public static final int STOP_PHASE_DELIVERY_FAULT_VALUE = 7;
  /**
   * <code>STOP_PHASE_STANDSTILL_TIMEOUT = 8;</code>
   */
  public static final int STOP_PHASE_STANDSTILL_TIMEOUT_VALUE = 8;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static StopPhase valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static StopPhase forNumber(int value) {
    switch (value) {
      case 0: return STOP_PHASE_UNSPECIFIED;
      case 1: return STOP_PHASE_REQUESTED;
      case 2: return STOP_PHASE_SENT;
      case 3: return STOP_PHASE_PROVIDER_ACCEPTED;
      case 4: return STOP_PHASE_MCU_ACKED;
      case 5: return STOP_PHASE_OUTPUT_DISABLED;
      case 6: return STOP_PHASE_STANDSTILL_CONFIRMED;
      case 7: return STOP_PHASE_DELIVERY_FAULT;
      case 8: return STOP_PHASE_STANDSTILL_TIMEOUT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<StopPhase>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      StopPhase> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<StopPhase>() {
          public StopPhase findValueByNumber(int number) {
            return StopPhase.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.github.nervusos.ipc.v1.SafetyProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final StopPhase[] VALUES = values();

  public static StopPhase valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private StopPhase(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:nervus.ipc.v1.StopPhase)
}

