// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nervus/interface/camera/v1/camera.proto
// Protobuf Java Version: 4.29.3

package io.github.nervusos.iface.camera.v1;

public interface SetControlsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nervus.interface.camera.v1.SetControlsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .nervus.interface.camera.v1.ControlValue values = 1 [json_name = "values"];</code>
   */
  java.util.List<io.github.nervusos.iface.camera.v1.ControlValue> 
      getValuesList();
  /**
   * <code>repeated .nervus.interface.camera.v1.ControlValue values = 1 [json_name = "values"];</code>
   */
  io.github.nervusos.iface.camera.v1.ControlValue getValues(int index);
  /**
   * <code>repeated .nervus.interface.camera.v1.ControlValue values = 1 [json_name = "values"];</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .nervus.interface.camera.v1.ControlValue values = 1 [json_name = "values"];</code>
   */
  java.util.List<? extends io.github.nervusos.iface.camera.v1.ControlValueOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .nervus.interface.camera.v1.ControlValue values = 1 [json_name = "values"];</code>
   */
  io.github.nervusos.iface.camera.v1.ControlValueOrBuilder getValuesOrBuilder(
      int index);
}
